declare const styles: {
  readonly root: string
  readonly bleed: string
  readonly bar: string
  readonly titleWrap: string
  readonly title: string
  readonly subtitle: string
  readonly spacer: string
  readonly chip: string
  readonly chipDot: string
  readonly chipIcon: string
  readonly status: string
  readonly statusGlyph: string
  readonly score: string
  readonly seg: string
  readonly segBtn: string
  readonly segIcon: string
  readonly panes: string
  readonly pane: string
  readonly paneLabel: string
  readonly scopeDot: string
  readonly paneMeta: string
  readonly well: string
  readonly media: string
  readonly bezel: string
  readonly delta: string
  readonly overlay: string
  readonly overlayFrame: string
  readonly layer: string
  readonly layerTop: string
  readonly handle: string
  readonly grip: string
  readonly gripIcon: string
  readonly ribbon: string
  readonly range: string
  readonly legend: string
  readonly legendHead: string
  readonly legendRow: string
  readonly legendNum: string
  readonly tag: string
  readonly legendText: string
  readonly srOnly: string
}

export default styles
