// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:visor_core/visor_core.dart';

/// Generated stroke-width tokens (raw pixel values).
sealed class VisorStrokeWidths {
  static final VisorStrokeWidthsData instance = VisorStrokeWidthsData(
    thin: 1,
    regular: 1.5,
    medium: 2,
    thick: 2.5,
  );
}
