import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  existsSync,
  readdirSync,
  unlinkSync,
  copyFileSync,
} from "fs"
import { join, basename } from "path"
import { parse as parseYaml } from "yaml"
import { generateThemeData } from "@loworbitstudio/visor-theme-engine"
import { docsAdapter } from "@loworbitstudio/visor-theme-engine/adapters"
import { logger } from "../utils/logger.js"
import { toSlug, toLabel, findRepoRoot } from "../utils/theme-helpers.js"

export interface ThemeSyncOptions {
  dryRun?: boolean
  json?: boolean
}

interface ThemeManifestEntry {
  slug: string
  label: string
  group: string
  defaultMode?: "dark" | "light"
  css: string
  yamlFilename: string
  isCustom: boolean
}

const GLOBALS_BEGIN_MARKER = "/* BEGIN visor-theme-imports — generated by `visor theme sync` */"
const GLOBALS_END_MARKER = "/* END visor-theme-imports */"
const GITIGNORE_BEGIN_MARKER = "# BEGIN visor-custom-theme-css (managed by `visor theme sync` — do not edit manually)"
const GITIGNORE_END_MARKER = "# END visor-custom-theme-css"
const THEME_CONFIG_HEADER = "// This file is auto-generated by `visor theme sync`. Do not edit manually.\n"

/** Scan a directory for .visor.yaml files. Returns empty array if dir doesn't exist. */
function scanThemeDir(dir: string): string[] {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((f) => f.endsWith(".visor.yaml"))
    .map((f) => join(dir, f))
}

/** Extract the raw `group` field from a YAML string without running the full theme pipeline. */
function extractGroup(yamlContent: string): string | undefined {
  const parsed = parseYaml(yamlContent) as Record<string, unknown>
  if (typeof parsed?.group === "string") return parsed.group
  return undefined
}

/** Extract the raw `label` field from a YAML string. */
function extractLabel(yamlContent: string): string | undefined {
  const parsed = parseYaml(yamlContent) as Record<string, unknown>
  if (typeof parsed?.label === "string") return parsed.label
  return undefined
}

/** Extract the raw `default-mode` field from a YAML string. */
function extractDefaultMode(yamlContent: string): "dark" | "light" | undefined {
  const parsed = parseYaml(yamlContent) as Record<string, unknown>
  const v = parsed?.["default-mode"]
  if (v === "dark" || v === "light") return v
  return undefined
}

/** Sort groups: "Visor" always first, then alphabetical. */
function sortGroups(groups: string[]): string[] {
  return [...groups].sort((a, b) => {
    if (a === "Visor") return -1
    if (b === "Visor") return 1
    return a.localeCompare(b)
  })
}

/** Generate the full theme-config.ts content from the manifest. */
function generateThemeConfig(entries: ThemeManifestEntry[]): string {
  // Group entries
  const groupMap = new Map<string, ThemeManifestEntry[]>()
  for (const entry of entries) {
    if (!groupMap.has(entry.group)) groupMap.set(entry.group, [])
    groupMap.get(entry.group)!.push(entry)
  }

  // Sort groups and themes within each group
  const sortedGroupNames = sortGroups([...groupMap.keys()])
  for (const [, groupEntries] of groupMap) {
    groupEntries.sort((a, b) => a.slug.localeCompare(b.slug))
  }

  const groupsTs = sortedGroupNames.map((groupName) => {
    const groupEntries = groupMap.get(groupName)!
    const themesTs = groupEntries
      .map((e) => {
        const modePart = e.defaultMode ? `, defaultMode: "${e.defaultMode}"` : ""
        return `    { value: "${e.slug}", label: "${e.label}", yamlFile: "${e.yamlFilename}"${modePart} },`
      })
      .join("\n")
    return `  {\n    label: "${groupName}",\n    themes: [\n${themesTs}\n    ],\n  },`
  }).join("\n")

  return `${THEME_CONFIG_HEADER}
export interface ThemeEntry {
  value: string;
  label: string;
  /** Filename (without .visor.yaml extension) if a YAML config exists in /public/themes/ */
  yamlFile?: string;
  /** When set, activating this theme forces the docs site into the specified color mode. */
  defaultMode?: "dark" | "light";
}

export interface ThemeGroup {
  label: string;
  themes: ThemeEntry[];
}

export const THEME_GROUPS: ThemeGroup[] = [
${groupsTs}
];

export const ALL_THEMES = THEME_GROUPS.flatMap((g) => g.themes.map((t) => t.value));
`
}

/** Replace or insert the theme imports block in globals.css using marker comments. */
function updateGlobalsImports(content: string, slugs: string[]): string {
  const importLines = [...slugs]
    .sort()
    .map((slug) => `@import './${slug}-theme.css';`)
    .join("\n")
  const newBlock = `${GLOBALS_BEGIN_MARKER}\n${importLines}\n${GLOBALS_END_MARKER}`

  const beginIdx = content.indexOf(GLOBALS_BEGIN_MARKER)
  const endIdx = content.indexOf(GLOBALS_END_MARKER)

  if (beginIdx !== -1 && endIdx !== -1) {
    // Replace the existing block
    return (
      content.slice(0, beginIdx) +
      newBlock +
      content.slice(endIdx + GLOBALS_END_MARKER.length)
    )
  }

  // No markers yet — find the existing theme import block and replace it
  const themeImportPattern = /^@import '\.\/[\w-]+-theme\.css';\n?/gm
  const lines = content.split("\n")
  let firstThemeIdx = -1
  let lastThemeIdx = -1
  for (let i = 0; i < lines.length; i++) {
    if (/^@import '\.\/[\w-]+-theme\.css';/.test(lines[i])) {
      if (firstThemeIdx === -1) firstThemeIdx = i
      lastThemeIdx = i
    }
  }

  if (firstThemeIdx !== -1) {
    // Replace the existing contiguous theme import block with our marked block
    const before = lines.slice(0, firstThemeIdx)
    const after = lines.slice(lastThemeIdx + 1)
    return [...before, newBlock, ...after].join("\n")
  }

  // No existing imports — insert after the last @import line
  void themeImportPattern // suppress unused warning
  const lastImportIdx = lines.reduce(
    (last, line, i) => (line.startsWith("@import") ? i : last),
    -1,
  )
  const insertAt = lastImportIdx + 1
  lines.splice(insertAt, 0, newBlock)
  return lines.join("\n")
}

/** Update the visor-custom-theme-css block in .gitignore. */
function updateGitignoreBlock(content: string, customSlugs: string[]): string {
  const cssLines = customSlugs
    .sort()
    .map((slug) => `packages/docs/app/${slug}-theme.css`)
    .join("\n")
  const newBlock = `${GITIGNORE_BEGIN_MARKER}\n${cssLines}\n${GITIGNORE_END_MARKER}`

  const beginIdx = content.indexOf(GITIGNORE_BEGIN_MARKER)
  const endIdx = content.indexOf(GITIGNORE_END_MARKER)

  if (beginIdx !== -1 && endIdx !== -1) {
    return (
      content.slice(0, beginIdx) +
      newBlock +
      content.slice(endIdx + GITIGNORE_END_MARKER.length)
    )
  }

  // Block not present — append it
  return content.trimEnd() + "\n\n" + newBlock + "\n"
}

export function themeSyncCommand(cwd: string, options: ThemeSyncOptions): void {
  const repoRoot = findRepoRoot(cwd)
  if (!repoRoot) {
    const msg = "Could not locate repo root (packages/docs/ not found). Run from within the visor repo."
    if (options.json) {
      console.log(JSON.stringify({ success: false, error: msg }))
    } else {
      logger.error(msg)
    }
    process.exit(1)
    return
  }

  const themesDir = join(repoRoot, "themes")
  const customThemesDir = join(repoRoot, "custom-themes")
  const docsAppDir = join(repoRoot, "packages", "docs", "app")
  const docsPublicThemesDir = join(repoRoot, "packages", "docs", "public", "themes")
  const themeConfigPath = join(repoRoot, "packages", "docs", "lib", "theme-config.ts")
  const globalsPath = join(docsAppDir, "globals.css")
  const gitignorePath = join(repoRoot, ".gitignore")

  // Discover theme YAMLs
  const stockFiles = scanThemeDir(themesDir)
  const customFiles = scanThemeDir(customThemesDir)

  if (stockFiles.length === 0 && customFiles.length === 0) {
    const msg = `No .visor.yaml files found in themes/ or custom-themes/. Nothing to sync.`
    if (options.json) {
      console.log(JSON.stringify({ success: false, error: msg }))
    } else {
      logger.warn(msg)
    }
    return
  }

  // Build manifest
  const manifest: ThemeManifestEntry[] = []
  const errors: string[] = []

  const processFile = (filePath: string, isCustom: boolean) => {
    let yamlContent: string
    try {
      yamlContent = readFileSync(filePath, "utf-8")
    } catch {
      errors.push(`Could not read: ${filePath}`)
      return
    }

    let data: ReturnType<typeof generateThemeData>
    try {
      data = generateThemeData(yamlContent)
    } catch (err) {
      errors.push(`Failed to parse ${basename(filePath)}: ${err instanceof Error ? err.message : "Unknown error"}`)
      return
    }

    const slug = toSlug(data.config.name)
    const label = extractLabel(yamlContent) ?? toLabel(data.config.name)
    const group = extractGroup(yamlContent) ?? (isCustom ? "Custom" : "Visor")
    const defaultMode = extractDefaultMode(yamlContent)
    const css = docsAdapter({ primitives: data.primitives, tokens: data.tokens, config: data.config })
    // yamlFilename: slug of the file (without .visor.yaml) for public/themes/ reference
    const yamlFilename = basename(filePath).replace(/\.visor\.yaml$/, "")

    manifest.push({ slug, label, group, defaultMode, css, yamlFilename, isCustom })
  }

  for (const f of stockFiles) processFile(f, false)
  for (const f of customFiles) processFile(f, true)

  if (errors.length > 0) {
    if (options.json) {
      console.log(JSON.stringify({ success: false, errors }))
    } else {
      errors.forEach((e) => logger.error(e))
    }
    process.exit(1)
    return
  }

  // Compute new state
  const newThemeConfig = generateThemeConfig(manifest)
  const allSlugs = manifest.map((e) => e.slug)
  const customSlugs = manifest.filter((e) => e.isCustom).map((e) => e.slug)

  let globalsContent: string
  let gitignoreContent: string
  try {
    globalsContent = readFileSync(globalsPath, "utf-8")
    gitignoreContent = existsSync(gitignorePath) ? readFileSync(gitignorePath, "utf-8") : ""
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Could not read docs files"
    if (options.json) {
      console.log(JSON.stringify({ success: false, error: msg }))
    } else {
      logger.error(msg)
    }
    process.exit(1)
    return
  }

  const newGlobals = updateGlobalsImports(globalsContent, allSlugs)
  const newGitignore = customSlugs.length > 0
    ? updateGitignoreBlock(gitignoreContent, customSlugs)
    : gitignoreContent

  // Find stale CSS files in docs/app
  const existingCssFiles = existsSync(docsAppDir)
    ? readdirSync(docsAppDir).filter((f) => f.endsWith("-theme.css"))
    : []
  const newCssSet = new Set(allSlugs.map((s) => `${s}-theme.css`))
  const staleCssFiles = existingCssFiles.filter((f) => !newCssSet.has(f))

  // Find stale public/themes copies
  const existingPublicYamls = existsSync(docsPublicThemesDir)
    ? readdirSync(docsPublicThemesDir).filter((f) => f.endsWith(".visor.yaml"))
    : []
  const newPublicYamlSet = new Set(manifest.map((e) => `${e.yamlFilename}.visor.yaml`))
  const stalePublicYamls = existingPublicYamls.filter((f) => !newPublicYamlSet.has(f))

  if (options.dryRun) {
    const changes = {
      themesDiscovered: manifest.map((e) => ({ slug: e.slug, group: e.group, isCustom: e.isCustom })),
      cssFilesGenerated: allSlugs.map((s) => `packages/docs/app/${s}-theme.css`),
      cssFilesDeleted: staleCssFiles.map((f) => `packages/docs/app/${f}`),
      themeConfig: themeConfigPath,
      globalsCSS: globalsPath,
      gitignore: gitignorePath,
      publicYamlsCopied: manifest.map((e) => `packages/docs/public/themes/${e.yamlFilename}.visor.yaml`),
      publicYamlsDeleted: stalePublicYamls.map((f) => `packages/docs/public/themes/${f}`),
    }
    if (options.json) {
      console.log(JSON.stringify({ success: true, dryRun: true, changes }))
    } else {
      logger.info("Dry run — no files written")
      logger.item(`Themes discovered: ${manifest.length} (${manifest.filter(e => !e.isCustom).length} stock, ${manifest.filter(e => e.isCustom).length} custom)`)
      manifest.forEach((e) => logger.item(`  ${e.slug} — group: ${e.group}`))
      if (staleCssFiles.length > 0) logger.item(`CSS files to delete: ${staleCssFiles.join(", ")}`)
      if (stalePublicYamls.length > 0) logger.item(`Public YAMLs to delete: ${stalePublicYamls.join(", ")}`)
    }
    return
  }

  // Write all files
  try {
    mkdirSync(docsAppDir, { recursive: true })
    mkdirSync(docsPublicThemesDir, { recursive: true })

    // Write CSS files
    for (const entry of manifest) {
      writeFileSync(join(docsAppDir, `${entry.slug}-theme.css`), entry.css, "utf-8")
    }

    // Delete stale CSS files
    for (const stale of staleCssFiles) {
      unlinkSync(join(docsAppDir, stale))
    }

    // Write theme-config.ts
    writeFileSync(themeConfigPath, newThemeConfig, "utf-8")

    // Update globals.css
    writeFileSync(globalsPath, newGlobals, "utf-8")

    // Update .gitignore
    if (existsSync(gitignorePath)) {
      writeFileSync(gitignorePath, newGitignore, "utf-8")
    }

    // Copy YAMLs to public/themes/
    const allSourceFiles = [...stockFiles, ...customFiles]
    for (const srcFile of allSourceFiles) {
      const filename = basename(srcFile)
      copyFileSync(srcFile, join(docsPublicThemesDir, filename))
    }

    // Delete stale public/themes/ copies
    for (const stale of stalePublicYamls) {
      unlinkSync(join(docsPublicThemesDir, stale))
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Write failed"
    if (options.json) {
      console.log(JSON.stringify({ success: false, error: msg }))
    } else {
      logger.error(msg)
    }
    process.exit(2)
    return
  }

  if (options.json) {
    console.log(JSON.stringify({
      success: true,
      themes: manifest.length,
      stock: manifest.filter((e) => !e.isCustom).length,
      custom: manifest.filter((e) => e.isCustom).length,
      staleCssDeleted: staleCssFiles.length,
      staleYamlsDeleted: stalePublicYamls.length,
      slugs: allSlugs,
    }))
  } else {
    logger.success(`Theme sync complete — ${manifest.length} themes registered`)
    logger.item(`Stock: ${manifest.filter(e => !e.isCustom).map(e => e.slug).join(", ")}`)
    if (manifest.filter(e => e.isCustom).length > 0) {
      logger.item(`Custom: ${manifest.filter(e => e.isCustom).map(e => e.slug).join(", ")}`)
    }
    if (staleCssFiles.length > 0) {
      logger.item(`Removed stale CSS: ${staleCssFiles.join(", ")}`)
    }
  }
}
