// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:visor_core/visor_core.dart';

/// Generated spacing tokens.
///
/// Base unit: 4px. Scale derived by multiplication:
/// xs=1×, sm=2×, md=3×, lg=4×, xl=6×, xxl=8×, xxxl=12×.
sealed class VisorSpacing {
  static final VisorSpacingData instance = VisorSpacingData(
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 48,
  );
}
