// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:visor_core/visor_core.dart';

/// Generated typography tokens — Material 3 type-scale + `labelXSmall`.
///
/// Font family is not baked in here; `VisorTheme.build()` applies it
/// globally via `TextTheme.apply(fontFamily: ...)`. Override per-slot
/// values in `.visor.yaml` under `typography.slots`.
sealed class VisorTextStyles {
  static final VisorTextStylesData instance =
      VisorTextStylesData.defaults;
}
