/// visor_core — tokens and theme builder for the Visor design system.
///
/// This package provides:
/// - [ThemeExtension] classes for Visor's semantic token categories
///   ([VisorColors], [VisorMotion], [VisorShadows], [VisorRadius],
///   [VisorSpacing]).
/// - A [VisorTheme] builder that assembles a Material 3 [ThemeData] from a
///   set of Visor tokens.
///
/// Token *data* (the concrete values) is generated by the Visor CLI from a
/// `.visor.yaml` interchange file. Your generated `ui_colors.dart`,
/// `ui_text_styles.dart`, etc. provide the data; this package provides the
/// types and the builder.
library;

export 'src/extensions/visor_colors.dart';
export 'src/extensions/visor_motion.dart';
export 'src/extensions/visor_radius.dart';
export 'src/extensions/visor_shadows.dart';
export 'src/extensions/visor_spacing.dart';
export 'src/builder/visor_theme.dart';
