/// visor_core — tokens and theme builder for the Visor design system.
///
/// This package provides:
/// - [ThemeExtension] data classes for Visor's semantic token categories
///   ([VisorColorsData], [VisorMotionData], [VisorShadowsData],
///   [VisorRadiusData], [VisorSpacingData], [VisorTextStylesData]).
/// - A [VisorTheme] builder that assembles a Material 3 [ThemeData] from a
///   set of Visor tokens.
///
/// Concrete token *values* are generated by the Visor CLI from a
/// `.visor.yaml` interchange file into per-project sealed wrappers
/// (`VisorColors`, `VisorTextStyles`, …) that expose `.light` / `.dark`
/// getters returning the `*Data` instances defined here.
library;

export 'src/extensions/build_context_extensions.dart';
export 'src/extensions/visor_colors.dart';
export 'src/extensions/visor_motion.dart';
export 'src/extensions/visor_radius.dart';
export 'src/extensions/visor_shadows.dart';
export 'src/extensions/visor_spacing.dart';
export 'src/extensions/visor_text_styles.dart';
export 'src/builder/visor_theme.dart';
