// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:visor_core/visor_core.dart';

/// Generated opacity tokens (raw alpha values in [0, 1]).
///
/// Fixed across themes — opacity is a math primitive, not a brand decision.
sealed class VisorOpacity {
  static final VisorOpacityData instance = VisorOpacityData(
    alpha5: 0.05,
    alpha10: 0.1,
    alpha12: 0.12,
    alpha20: 0.2,
    alpha40: 0.4,
    alpha50: 0.5,
    alpha60: 0.6,
    alpha80: 0.8,
  );
}
