// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';

/// Generated motion tokens — durations + default easing curve.
sealed class VisorMotion {
  static final VisorMotionData instance = VisorMotionData(
    durationFast: Duration(milliseconds: 100),
    durationNormal: Duration(milliseconds: 150),
    durationSlow: Duration(milliseconds: 300),
    easing: Cubic(0.4, 0, 0.2, 1),
  );
}
