// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:visor_core/visor_core.dart';

/// Generated border-radius tokens (raw pixel values).
sealed class VisorRadius {
  static final VisorRadiusData instance = VisorRadiusData(
    sm: 4,
    md: 6,
    lg: 12,
    xl: 16,
    pill: 9999,
  );
}
