import { readFile } from 'node:fs/promises';
import type { Rule, RuleResult } from './types.js';

const GLOBALS_PATH = 'packages/docs/app/globals.css';

/**
 * The docs layout renders both wordmark-light and wordmark-dark in the DOM at
 * all times. Without these two CSS rules, both images are visible simultaneously.
 *
 * These rules must live in globals.css — not in any theme CSS file — because theme
 * files are regenerated by `visor theme sync` and would lose them.
 */
export const globalsWordmarkRules: Rule = {
  name: 'globals-wordmark-rules',
  description: 'globals.css contains the dark/light wordmark visibility rules',
  category: 'docs',
  async run(): Promise<RuleResult[]> {
    let content: string;
    try {
      content = await readFile(GLOBALS_PATH, 'utf-8');
    } catch {
      return [{ pass: false, message: `Could not read ${GLOBALS_PATH}`, file: GLOBALS_PATH }];
    }

    const results: RuleResult[] = [];

    const darkRule = '.dark .wordmark-light { display: none; }';
    const lightRule = 'html:not(.dark) .wordmark-dark { display: none; }';

    if (!content.includes(darkRule)) {
      results.push({
        pass: false,
        message: `Missing wordmark rule: "${darkRule}" — without it, the light wordmark shows in dark mode`,
        file: GLOBALS_PATH,
      });
    }

    if (!content.includes(lightRule)) {
      results.push({
        pass: false,
        message: `Missing wordmark rule: "${lightRule}" — without it, the dark wordmark shows in light mode`,
        file: GLOBALS_PATH,
      });
    }

    if (results.length === 0) {
      results.push({ pass: true, message: 'Wordmark visibility rules present', file: GLOBALS_PATH });
    }

    return results;
  },
};
