// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';

/// Generated elevation/shadow tokens.
///
/// Each value is a `List<BoxShadow>` — CSS box-shadow strings
/// supporting multi-layer shadows compile to the same list here.
sealed class VisorShadows {
  static final VisorShadowsData instance = VisorShadowsData(
    xs: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 1), blurRadius: 2, color: Color(0x145B6FFF)),
    ],
    sm: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 1), blurRadius: 3, color: Color(0x1A5B6FFF)),
    ],
    md: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 4), blurRadius: 12, color: Color(0x1F5B6FFF)),
    ],
    lg: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 10), blurRadius: 24, color: Color(0x245B6FFF)),
    ],
    xl: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 20), blurRadius: 40, color: Color(0x295B6FFF)),
    ],
  );
}
