// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';

import '../colors/visor_colors.dart';

/// Assembled Material 3 [ThemeData] for this project.
///
/// Wire into [MaterialApp]:
/// ```dart
/// MaterialApp(
///   theme: VisorAppTheme.light,
///   darkTheme: VisorAppTheme.dark,
/// );
/// ```
sealed class VisorAppTheme {
  static ThemeData get light => VisorTheme.build(
        colors: VisorColors.light,
        brightness: Brightness.light,
      );

  static ThemeData get dark => VisorTheme.build(
        colors: VisorColors.dark,
        brightness: Brightness.dark,
      );

}
