// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.
// Source: .visor.yaml → Visor theme engine → flutter adapter.

import 'dart:ui';

import 'package:visor_core/visor_core.dart';

/// Generated color tokens for the space theme.
///
/// Do not edit this file manually — regenerate from .visor.yaml.
sealed class VisorColors {
  // ========================================================================
  // Anchors
  // ========================================================================
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);

  // ========================================================================
  // Primary scale
  // ========================================================================
  static const Color primary50 = Color(0xFFF2F5FF);
  static const Color primary100 = Color(0xFFE2E9FE);
  static const Color primary200 = Color(0xFFCCD7FF);
  static const Color primary300 = Color(0xFFAABCFF);
  static const Color primary400 = Color(0xFF7B93FF);
  static const Color primary500 = Color(0xFF5B6FFF);
  static const Color primary600 = Color(0xFF3F49D7);
  static const Color primary700 = Color(0xFF2E2DBC);
  static const Color primary800 = Color(0xFF1E168D);
  static const Color primary900 = Color(0xFF100061);
  static const Color primary950 = Color(0xFF04002D);

  // ========================================================================
  // Accent scale
  // ========================================================================
  static const Color accent50 = Color(0xFFF2F5FF);
  static const Color accent100 = Color(0xFFE2E9FE);
  static const Color accent200 = Color(0xFFCCD7FF);
  static const Color accent300 = Color(0xFFAABCFF);
  static const Color accent400 = Color(0xFF7B93FF);
  static const Color accent500 = Color(0xFF5B6FFF);
  static const Color accent600 = Color(0xFF3F49D7);
  static const Color accent700 = Color(0xFF2E2DBC);
  static const Color accent800 = Color(0xFF1E168D);
  static const Color accent900 = Color(0xFF100061);
  static const Color accent950 = Color(0xFF04002D);

  // ========================================================================
  // Neutral scale
  // ========================================================================
  static const Color neutral50 = Color(0xFFF5F5F8);
  static const Color neutral100 = Color(0xFFE7E7ED);
  static const Color neutral200 = Color(0xFFD2D2DD);
  static const Color neutral300 = Color(0xFFB4B4C2);
  static const Color neutral400 = Color(0xFF8A8A98);
  static const Color neutral500 = Color(0xFF6B6B80);
  static const Color neutral600 = Color(0xFF51515D);
  static const Color neutral700 = Color(0xFF3F3F4B);
  static const Color neutral800 = Color(0xFF2B2B36);
  static const Color neutral900 = Color(0xFF191923);
  static const Color neutral950 = Color(0xFF080810);

  // ========================================================================
  // Success scale
  // ========================================================================
  static const Color success50 = Color(0xFFE8FBEB);
  static const Color success100 = Color(0xFFD8F7DC);
  static const Color success500 = Color(0xFF22C55E);
  static const Color success600 = Color(0xFF019341);
  static const Color success700 = Color(0xFF017231);
  static const Color success900 = Color(0xFF002B0E);

  // ========================================================================
  // Warning scale
  // ========================================================================
  static const Color warning50 = Color(0xFFFFF3E6);
  static const Color warning100 = Color(0xFFFFEBD5);
  static const Color warning500 = Color(0xFFF59E0B);
  static const Color warning600 = Color(0xFFB77401);
  static const Color warning700 = Color(0xFF8D5800);
  static const Color warning900 = Color(0xFF361F00);

  // ========================================================================
  // Error scale
  // ========================================================================
  static const Color error50 = Color(0xFFFFF2F0);
  static const Color error100 = Color(0xFFFFE3E0);
  static const Color error500 = Color(0xFFEF4444);
  static const Color error600 = Color(0xFFC3041E);
  static const Color error700 = Color(0xFF990015);
  static const Color error900 = Color(0xFF410004);

  // ========================================================================
  // Info scale
  // ========================================================================
  static const Color info50 = Color(0xFFECF7FF);
  static const Color info100 = Color(0xFFDAF0FF);
  static const Color info500 = Color(0xFF0EA5E9);
  static const Color info600 = Color(0xFF017BAF);
  static const Color info700 = Color(0xFF005F88);
  static const Color info900 = Color(0xFF002437);

  // ========================================================================
  // Opacity variants (pre-computed at codegen)
  // ========================================================================
  static const Color primary500_5o = Color(0x0D5B6FFF);
  static const Color primary500_10o = Color(0x1A5B6FFF);
  static const Color primary500_20o = Color(0x335B6FFF);
  static const Color primary500_40o = Color(0x665B6FFF);
  static const Color primary500_50o = Color(0x805B6FFF);
  static const Color primary500_60o = Color(0x995B6FFF);
  static const Color primary500_80o = Color(0xCC5B6FFF);
  static const Color primary600_5o = Color(0x0D3F49D7);
  static const Color primary600_10o = Color(0x1A3F49D7);
  static const Color primary600_20o = Color(0x333F49D7);
  static const Color primary600_40o = Color(0x663F49D7);
  static const Color primary600_50o = Color(0x803F49D7);
  static const Color primary600_60o = Color(0x993F49D7);
  static const Color primary600_80o = Color(0xCC3F49D7);
  static const Color accent500_5o = Color(0x0D5B6FFF);
  static const Color accent500_10o = Color(0x1A5B6FFF);
  static const Color accent500_20o = Color(0x335B6FFF);
  static const Color accent500_40o = Color(0x665B6FFF);
  static const Color accent500_50o = Color(0x805B6FFF);
  static const Color accent500_60o = Color(0x995B6FFF);
  static const Color accent500_80o = Color(0xCC5B6FFF);
  static const Color white_5o = Color(0x0DFFFFFF);
  static const Color white_10o = Color(0x1AFFFFFF);
  static const Color white_20o = Color(0x33FFFFFF);
  static const Color white_40o = Color(0x66FFFFFF);
  static const Color white_50o = Color(0x80FFFFFF);
  static const Color white_60o = Color(0x99FFFFFF);
  static const Color white_80o = Color(0xCCFFFFFF);
  static const Color black_5o = Color(0x0D000000);
  static const Color black_10o = Color(0x1A000000);
  static const Color black_20o = Color(0x33000000);
  static const Color black_40o = Color(0x66000000);
  static const Color black_50o = Color(0x80000000);
  static const Color black_60o = Color(0x99000000);
  static const Color black_80o = Color(0xCC000000);

  // ========================================================================
  // Semantic — Light
  // ========================================================================
  static final VisorColorsData light = VisorColorsData(
    textPrimary: Color(0xFF1A1630),
    textSecondary: Color(0xB81A1630),
    textTertiary: Color(0xA61A1630),
    textDisabled: Color(0xFFB4B4C2),
    textInverse: Color(0xFFFFFFFF),
    textInverseSecondary: Color(0xFFD2D2DD),
    textLink: Color(0xFF5B6FFF),
    textLinkHover: Color(0xFF2E2DBC),
    textSuccess: Color(0xFF017231),
    textWarning: Color(0xFF8D5800),
    textError: Color(0xFF990015),
    textInfo: Color(0xFF005F88),
    surfacePage: Color(0xFFE0DDEF),
    surfaceCard: Color(0xFFF2F0F8),
    surfaceSubtle: Color(0xFFF5F5F8),
    surfaceMuted: Color(0xFFE7E7ED),
    surfaceOverlay: Color(0xFF191923),
    surfaceInteractiveDefault: Color(0xFFFFFFFF),
    surfaceInteractiveHover: Color(0xFFF5F5F8),
    surfaceInteractiveActive: Color(0xFFE7E7ED),
    surfaceInteractiveDisabled: Color(0xFFF5F5F8),
    surfaceSelected: Color(0xFFE2E9FE),
    surfaceAccentSubtle: Color(0xFFF2F5FF),
    surfaceAccentDefault: Color(0xFF5B6FFF),
    surfaceAccentStrong: Color(0xFF3F49D7),
    surfaceSuccessSubtle: Color(0xFFE8FBEB),
    surfaceSuccessDefault: Color(0xFF22C55E),
    surfaceWarningSubtle: Color(0xFFFFF3E6),
    surfaceWarningDefault: Color(0xFFF59E0B),
    surfaceErrorSubtle: Color(0xFFFFF2F0),
    surfaceErrorDefault: Color(0xFFEF4444),
    surfaceInfoSubtle: Color(0xFFECF7FF),
    surfaceInfoDefault: Color(0xFF0EA5E9),
    borderDefault: Color(0xFFD2D2DD),
    borderMuted: Color(0xFFE7E7ED),
    borderStrong: Color(0xFFB4B4C2),
    borderFocus: Color(0xFF5B6FFF),
    borderDisabled: Color(0xFFE7E7ED),
    borderSuccess: Color(0xFF22C55E),
    borderWarning: Color(0xFFF59E0B),
    borderError: Color(0xFFEF4444),
    borderInfo: Color(0xFF0EA5E9),
    interactivePrimaryBg: Color(0xFF5B6FFF),
    interactivePrimaryBgHover: Color(0xFF2E2DBC),
    interactivePrimaryBgActive: Color(0xFF1E168D),
    interactivePrimaryText: Color(0xFFFFFFFF),
    interactiveSecondaryBg: Color(0xFFFFFFFF),
    interactiveSecondaryBgHover: Color(0xFFF5F5F8),
    interactiveSecondaryBgActive: Color(0xFFE7E7ED),
    interactiveSecondaryText: Color(0xFF191923),
    interactiveSecondaryBorder: Color(0xFFB4B4C2),
    interactiveDestructiveBg: Color(0xFFC3041E),
    interactiveDestructiveBgHover: Color(0xFF990015),
    interactiveDestructiveText: Color(0xFFFFFFFF),
    interactiveGhostBg: Color(0xFFFFFFFF),
    interactiveGhostBgHover: Color(0xFFE7E7ED),
  );

  // ========================================================================
  // Semantic — Dark
  // ========================================================================
  static final VisorColorsData dark = VisorColorsData(
    textPrimary: Color(0xFFE8E8F0),
    textSecondary: Color(0xB8E8E8F0),
    textTertiary: Color(0x80E8E8F0),
    textDisabled: Color(0xFF51515D),
    textInverse: Color(0xFF191923),
    textInverseSecondary: Color(0xFF3F3F4B),
    textLink: Color(0xFF8B9FFF),
    textLinkHover: Color(0xFFAABCFF),
    textSuccess: Color(0xFF22C55E),
    textWarning: Color(0xFFF59E0B),
    textError: Color(0xFFEF4444),
    textInfo: Color(0xFF0EA5E9),
    surfacePage: Color(0xFF080810),
    surfaceCard: Color(0xFF0E0E18),
    surfaceSubtle: Color(0xFF2B2B36),
    surfaceMuted: Color(0xFF0B0B14),
    surfaceOverlay: Color(0xFF080810),
    surfaceInteractiveDefault: Color(0xFF2B2B36),
    surfaceInteractiveHover: Color(0xFF3F3F4B),
    surfaceInteractiveActive: Color(0xFF51515D),
    surfaceInteractiveDisabled: Color(0xFF2B2B36),
    surfaceSelected: Color(0xFF1E168D),
    surfaceAccentSubtle: Color(0xFF100061),
    surfaceAccentDefault: Color(0xFF5B6FFF),
    surfaceAccentStrong: Color(0xFF7B93FF),
    surfaceSuccessSubtle: Color(0xFF002B0E),
    surfaceSuccessDefault: Color(0xFF22C55E),
    surfaceWarningSubtle: Color(0xFF361F00),
    surfaceWarningDefault: Color(0xFFF59E0B),
    surfaceErrorSubtle: Color(0xFF410004),
    surfaceErrorDefault: Color(0xFFEF4444),
    surfaceInfoSubtle: Color(0xFF002437),
    surfaceInfoDefault: Color(0xFF0EA5E9),
    borderDefault: Color(0xFF3F3F4B),
    borderMuted: Color(0xFF2B2B36),
    borderStrong: Color(0xFF51515D),
    borderFocus: Color(0xFF5B6FFF),
    borderDisabled: Color(0xFF2B2B36),
    borderSuccess: Color(0xFF22C55E),
    borderWarning: Color(0xFFF59E0B),
    borderError: Color(0xFFEF4444),
    borderInfo: Color(0xFF0EA5E9),
    interactivePrimaryBg: Color(0xFF5B6FFF),
    interactivePrimaryBgHover: Color(0xFF7B93FF),
    interactivePrimaryBgActive: Color(0xFFAABCFF),
    interactivePrimaryText: Color(0xFFFFFFFF),
    interactiveSecondaryBg: Color(0xFF2B2B36),
    interactiveSecondaryBgHover: Color(0xFF3F3F4B),
    interactiveSecondaryBgActive: Color(0xFF51515D),
    interactiveSecondaryText: Color(0xFFF5F5F8),
    interactiveSecondaryBorder: Color(0xFF51515D),
    interactiveDestructiveBg: Color(0xFFEF4444),
    interactiveDestructiveBgHover: Color(0xFFC3041E),
    interactiveDestructiveText: Color(0xFFFFFFFF),
    interactiveGhostBg: Color(0xFF2B2B36),
    interactiveGhostBgHover: Color(0xFF3F3F4B),
  );
}
