// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';

/// Generated typography tokens — Material 3 type-scale + `labelXSmall`.
///
/// Font family is not baked in here; `VisorTheme.build()` applies it
/// globally via `TextTheme.apply(fontFamily: ...)`. Override per-slot
/// values in `.visor.yaml` under `typography.slots`.
sealed class VisorTextStyles {
  static final VisorTextStylesData instance =
      VisorTextStylesData.defaults.copyWith(
        displayLarge: const TextStyle(
          fontSize: 56,
          fontWeight: FontWeight.w500,
          letterSpacing: -0.5,
        ),
        displayMedium: const TextStyle(
          fontSize: 32,
          fontWeight: FontWeight.w600,
          letterSpacing: -0.25,
        ),
        displaySmall: const TextStyle(
          fontSize: 28,
          fontWeight: FontWeight.w500,
          letterSpacing: 0,
        ),
        headlineLarge: const TextStyle(
          fontSize: 26,
          fontWeight: FontWeight.w500,
          letterSpacing: 0,
        ),
        headlineMedium: const TextStyle(
          fontSize: 22,
          fontWeight: FontWeight.w500,
          letterSpacing: 0,
        ),
        headlineSmall: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w600,
          letterSpacing: 0,
        ),
        titleLarge: const TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w600,
          letterSpacing: 0,
        ),
        titleMedium: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w600,
          letterSpacing: 0.1,
        ),
        titleSmall: const TextStyle(
          fontSize: 13,
          fontWeight: FontWeight.w600,
          letterSpacing: 0.1,
        ),
        bodyLarge: const TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w300,
          letterSpacing: 0.15,
        ),
        bodyMedium: const TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.w400,
          letterSpacing: 0.25,
        ),
        bodySmall: const TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w300,
          letterSpacing: 0.4,
        ),
        labelLarge: const TextStyle(
          fontSize: 17,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.1,
        ),
        labelMedium: const TextStyle(
          fontSize: 15,
          fontWeight: FontWeight.w600,
          letterSpacing: 0.5,
        ),
        labelSmall: const TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.5,
        ),
        labelXSmall: const TextStyle(
          fontSize: 10,
          fontWeight: FontWeight.w500,
          letterSpacing: 0.5,
        ),
      );
}
