import 'package:flutter/material.dart';
import 'package:visor_themes/visor_themes.dart';

/// Font family bundled in `pubspec.yaml` (see `packages/widgetbook/fonts/`).
const String _kSatoshi = 'Satoshi';

/// Reskins a Visor [ThemeData] with the Satoshi font family applied across
/// every TextStyle the chrome and preview surfaces inherit.
///
/// The Visor token pipeline does not bake `fontFamily` into generated themes
/// — consumers apply it at the app boundary. Widgetbook is one such consumer.
ThemeData applySatoshi(ThemeData base) {
  final textTheme = base.textTheme.apply(fontFamily: _kSatoshi);
  final primaryTextTheme = base.primaryTextTheme.apply(fontFamily: _kSatoshi);
  return base.copyWith(
    textTheme: textTheme,
    primaryTextTheme: primaryTextTheme,
    appBarTheme: base.appBarTheme.copyWith(
      titleTextStyle:
          base.appBarTheme.titleTextStyle?.copyWith(fontFamily: _kSatoshi),
      toolbarTextStyle:
          base.appBarTheme.toolbarTextStyle?.copyWith(fontFamily: _kSatoshi),
    ),
  );
}

/// Builds the Widgetbook chrome theme — sidebar, header, addon labels.
///
/// Chrome stays Blackout-dark regardless of which preview theme the user
/// selects. This keeps the navigation surface visually stable while preview
/// themes shift underneath, mirroring how the docs site holds its dark
/// chrome while content theming changes.
ThemeData buildChromeTheme() => applySatoshi(VisorThemes.blackout.dark);

/// Builds the preview theme used inside [ThemeAddon.themeBuilder].
///
/// Layered on top of the per-pair [ThemeData] generated by `visor_themes`,
/// adding only the Satoshi font family — colors, spacing, and component
/// theming all flow through unchanged from the user-selected pair.
ThemeData buildPreviewTheme(ThemeData base) => applySatoshi(base);

/// Reads the active preview theme's [VisorColorsData.surfacePage] for use as
/// the canvas backdrop. Returns Blackout's dark `surfacePage` if the
/// extension is not present (defensive — every Visor-built theme attaches
/// it, but external consumers passing raw [ThemeData] would not).
Color resolveBackdrop(BuildContext context) {
  final colors = Theme.of(context).extension<VisorColorsData>();
  return colors?.surfacePage ?? const Color(0xFF000000);
}
