// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';

/// Generated elevation/shadow tokens.
///
/// Each value is a `List<BoxShadow>` — CSS box-shadow strings
/// supporting multi-layer shadows compile to the same list here.
sealed class VisorShadows {
  static final VisorShadowsData instance = VisorShadowsData(
    xs: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 1), blurRadius: 2, color: Color(0x0A000000)),
    ],
    sm: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 1), blurRadius: 3, color: Color(0x0F000000)),
      BoxShadow(offset: Offset(0, 1), blurRadius: 2, color: Color(0x0A000000)),
    ],
    md: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 4), blurRadius: 6, color: Color(0x0D000000)),
      BoxShadow(offset: Offset(0, 2), blurRadius: 4, color: Color(0x0A000000)),
    ],
    lg: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 10), blurRadius: 15, color: Color(0x0F000000)),
      BoxShadow(offset: Offset(0, 4), blurRadius: 6, color: Color(0x0A000000)),
    ],
    xl: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 20), blurRadius: 25, color: Color(0x0F000000)),
      BoxShadow(offset: Offset(0, 8), blurRadius: 10, color: Color(0x08000000)),
    ],
  );
}
