'use client';

import { useState, useEffect } from 'react';
import { codeToHtml } from 'shiki';
import { ArrowsOut } from '@phosphor-icons/react';
import {
  FullscreenOverlay,
  FullscreenOverlayTrigger,
  FullscreenOverlayContent,
} from '@/components/ui/fullscreen-overlay';

interface BlockPreviewProps {
  children: React.ReactNode;
  code: string;
  title?: string;
}

export function BlockPreview({
  children,
  code,
  title,
}: BlockPreviewProps) {
  const [showCode, setShowCode] = useState(false);
  const [copied, setCopied] = useState(false);
  const [highlightedHTML, setHighlightedHTML] = useState<string | null>(null);

  useEffect(() => {
    if (!showCode) return;
    const isDark = document.documentElement.classList.contains('dark');
    const theme = isDark ? 'github-dark' : 'github-light';

    codeToHtml(code, { lang: 'tsx', theme }).then(setHighlightedHTML);
  }, [showCode, code]);

  async function handleCopy() {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="preview-container">
      <div
        className="preview-render"
        style={{ isolation: 'isolate', color: 'var(--text-primary)', minHeight: '200px', alignItems: 'stretch' }}
      >
        {children}
      </div>
      <div className="preview-footer">
        {title ? <p className="preview-title">{title}</p> : <span />}
        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <FullscreenOverlay>
            <FullscreenOverlayTrigger asChild>
              <button className="preview-toggle" aria-label="Open fullscreen">
                <ArrowsOut size={14} style={{ verticalAlign: 'middle', marginRight: '0.25rem' }} />
                Fullscreen
              </button>
            </FullscreenOverlayTrigger>
            <FullscreenOverlayContent fullbleed>
              <div style={{ isolation: 'isolate', color: 'var(--text-primary)', width: '100%', height: '100%' }}>
                {children}
              </div>
            </FullscreenOverlayContent>
          </FullscreenOverlay>
          {showCode && (
            <button className="preview-copy" onClick={handleCopy}>
              {copied ? 'Copied!' : 'Copy'}
            </button>
          )}
          <button
            className="preview-toggle"
            onClick={() => setShowCode(!showCode)}
          >
            {showCode ? 'Hide Code' : 'Show Code'}
          </button>
        </div>
      </div>
      {showCode && (
        <div className="preview-code">
          {highlightedHTML ? (
            // Safe: highlightedHTML is generated by Shiki from static MDX code strings, not user input
            <div dangerouslySetInnerHTML={{ __html: highlightedHTML }} />
          ) : (
            <pre><code>{code}</code></pre>
          )}
        </div>
      )}
    </div>
  );
}
