// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';

/// Generated elevation/shadow tokens.
///
/// Each value is a `List<BoxShadow>` — CSS box-shadow strings
/// supporting multi-layer shadows compile to the same list here.
sealed class VisorShadows {
  static final VisorShadowsData instance = VisorShadowsData(
    xs: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 1), blurRadius: 2, color: Color(0x33000000)),
    ],
    sm: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 2), blurRadius: 4, color: Color(0x40000000)),
    ],
    md: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 4), blurRadius: 8, color: Color(0x4D000000)),
    ],
    lg: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 8), blurRadius: 16, color: Color(0x59000000)),
    ],
    xl: const <BoxShadow>[
      BoxShadow(offset: Offset(0, 16), blurRadius: 32, color: Color(0x66000000)),
    ],
  );
}
