// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.
// Source: .visor.yaml → Visor theme engine → flutter adapter.

import 'dart:ui';

import 'package:visor_core/visor_core.dart';

/// Generated color tokens for the solespark theme.
///
/// Do not edit this file manually — regenerate from .visor.yaml.
sealed class VisorColors {
  // ========================================================================
  // Anchors
  // ========================================================================
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);

  // ========================================================================
  // Primary scale
  // ========================================================================
  static const Color primary50 = Color(0xFFF4F4FE);
  static const Color primary100 = Color(0xFFF1F1FF);
  static const Color primary200 = Color(0xFFECECFF);
  static const Color primary300 = Color(0xFFE4E5FF);
  static const Color primary400 = Color(0xFFDADAFF);
  static const Color primary500 = Color(0xFF6952D9);
  static const Color primary600 = Color(0xFF5235BB);
  static const Color primary700 = Color(0xFF4219A3);
  static const Color primary800 = Color(0xFF2E067B);
  static const Color primary900 = Color(0xFF1B0052);
  static const Color primary950 = Color(0xFF090029);

  // ========================================================================
  // Accent scale
  // ========================================================================
  static const Color accent50 = Color(0xFFFFF0F9);
  static const Color accent100 = Color(0xFFFFEDF8);
  static const Color accent200 = Color(0xFFFFE9F6);
  static const Color accent300 = Color(0xFFFFE2F3);
  static const Color accent400 = Color(0xFFFFD8EF);
  static const Color accent500 = Color(0xFFFF00C8);
  static const Color accent600 = Color(0xFF950173);
  static const Color accent700 = Color(0xFF76005B);
  static const Color accent800 = Color(0xFF540040);
  static const Color accent900 = Color(0xFF350027);
  static const Color accent950 = Color(0xFF180010);

  // ========================================================================
  // Neutral scale
  // ========================================================================
  static const Color neutral50 = Color(0xFFF4F5F7);
  static const Color neutral100 = Color(0xFFF0F2F6);
  static const Color neutral200 = Color(0xFFEAEEF5);
  static const Color neutral300 = Color(0xFFE2E8F3);
  static const Color neutral400 = Color(0xFFD8DFEC);
  static const Color neutral500 = Color(0xFF6C727E);
  static const Color neutral600 = Color(0xFF505561);
  static const Color neutral700 = Color(0xFF3D424D);
  static const Color neutral800 = Color(0xFF292E38);
  static const Color neutral900 = Color(0xFF171B22);
  static const Color neutral950 = Color(0xFF07090E);

  // ========================================================================
  // Success scale
  // ========================================================================
  static const Color success50 = Color(0xFFE9FBEA);
  static const Color success100 = Color(0xFFDFFDE1);
  static const Color success500 = Color(0xFF34C759);
  static const Color success600 = Color(0xFF006824);
  static const Color success700 = Color(0xFF00511A);
  static const Color success900 = Color(0xFF002207);

  // ========================================================================
  // Warning scale
  // ========================================================================
  static const Color warning50 = Color(0xFFFCF5E1);
  static const Color warning100 = Color(0xFFFFF4D6);
  static const Color warning500 = Color(0xFFFFCC01);
  static const Color warning600 = Color(0xFF695200);
  static const Color warning700 = Color(0xFF524001);
  static const Color warning900 = Color(0xFF231900);

  // ========================================================================
  // Error scale
  // ========================================================================
  static const Color error50 = Color(0xFFFFF2F0);
  static const Color error100 = Color(0xFFFFEFEC);
  static const Color error500 = Color(0xFFFF3B30);
  static const Color error600 = Color(0xFFA30104);
  static const Color error700 = Color(0xFF810103);
  static const Color error900 = Color(0xFF3B0000);

  // ========================================================================
  // Info scale
  // ========================================================================
  static const Color info50 = Color(0xFFEBF7FF);
  static const Color info100 = Color(0xFFE9F6FF);
  static const Color info500 = Color(0xFF5CC4FF);
  static const Color info600 = Color(0xFF005C84);
  static const Color info700 = Color(0xFF004868);
  static const Color info900 = Color(0xFF001D2E);

  // ========================================================================
  // Opacity variants (pre-computed at codegen)
  // ========================================================================
  static const Color primary500_5o = Color(0x0D6952D9);
  static const Color primary500_10o = Color(0x1A6952D9);
  static const Color primary500_20o = Color(0x336952D9);
  static const Color primary500_40o = Color(0x666952D9);
  static const Color primary500_50o = Color(0x806952D9);
  static const Color primary500_60o = Color(0x996952D9);
  static const Color primary500_80o = Color(0xCC6952D9);
  static const Color primary600_5o = Color(0x0D5235BB);
  static const Color primary600_10o = Color(0x1A5235BB);
  static const Color primary600_20o = Color(0x335235BB);
  static const Color primary600_40o = Color(0x665235BB);
  static const Color primary600_50o = Color(0x805235BB);
  static const Color primary600_60o = Color(0x995235BB);
  static const Color primary600_80o = Color(0xCC5235BB);
  static const Color accent500_5o = Color(0x0DFF00C8);
  static const Color accent500_10o = Color(0x1AFF00C8);
  static const Color accent500_20o = Color(0x33FF00C8);
  static const Color accent500_40o = Color(0x66FF00C8);
  static const Color accent500_50o = Color(0x80FF00C8);
  static const Color accent500_60o = Color(0x99FF00C8);
  static const Color accent500_80o = Color(0xCCFF00C8);
  static const Color white_5o = Color(0x0DFFFFFF);
  static const Color white_10o = Color(0x1AFFFFFF);
  static const Color white_20o = Color(0x33FFFFFF);
  static const Color white_40o = Color(0x66FFFFFF);
  static const Color white_50o = Color(0x80FFFFFF);
  static const Color white_60o = Color(0x99FFFFFF);
  static const Color white_80o = Color(0xCCFFFFFF);
  static const Color black_5o = Color(0x0D000000);
  static const Color black_10o = Color(0x1A000000);
  static const Color black_20o = Color(0x33000000);
  static const Color black_40o = Color(0x66000000);
  static const Color black_50o = Color(0x80000000);
  static const Color black_60o = Color(0x99000000);
  static const Color black_80o = Color(0xCC000000);

  // ========================================================================
  // Semantic — Light
  // ========================================================================
  static final VisorColorsData light = VisorColorsData(
    textPrimary: Color(0xFF171B22),
    textSecondary: Color(0xFF505561),
    textTertiary: Color(0xFFD8DFEC),
    textDisabled: Color(0xFFE2E8F3),
    textInverse: Color(0xFFFFFFFF),
    textInverseSecondary: Color(0xFFEAEEF5),
    textLink: Color(0xFF5235BB),
    textLinkHover: Color(0xFF4219A3),
    textSuccess: Color(0xFF00511A),
    textWarning: Color(0xFF524001),
    textError: Color(0xFF810103),
    textInfo: Color(0xFF004868),
    surfacePage: Color(0xFF1A1F22),
    surfaceCard: Color(0xFF242628),
    surfaceSubtle: Color(0xFFF4F5F7),
    surfaceMuted: Color(0xFFF0F2F6),
    surfaceOverlay: Color(0xFF171B22),
    surfaceInteractiveDefault: Color(0xFFFFFFFF),
    surfaceInteractiveHover: Color(0xFFF4F5F7),
    surfaceInteractiveActive: Color(0xFFF0F2F6),
    surfaceInteractiveDisabled: Color(0xFFF4F5F7),
    surfaceSelected: Color(0xFFF4F4FE),
    surfaceAccentSubtle: Color(0xFFF4F4FE),
    surfaceAccentDefault: Color(0xFF6952D9),
    surfaceAccentStrong: Color(0xFF5235BB),
    surfaceSuccessSubtle: Color(0xFFE9FBEA),
    surfaceSuccessDefault: Color(0xFF34C759),
    surfaceWarningSubtle: Color(0xFFFCF5E1),
    surfaceWarningDefault: Color(0xFFFFCC01),
    surfaceErrorSubtle: Color(0xFFFFF2F0),
    surfaceErrorDefault: Color(0xFFFF3B30),
    surfaceInfoSubtle: Color(0xFFEBF7FF),
    surfaceInfoDefault: Color(0xFF5CC4FF),
    borderDefault: Color(0xFFEAEEF5),
    borderMuted: Color(0xFFF0F2F6),
    borderStrong: Color(0xFFE2E8F3),
    borderFocus: Color(0xFF6952D9),
    borderDisabled: Color(0xFFF0F2F6),
    borderSuccess: Color(0xFF34C759),
    borderWarning: Color(0xFFFFCC01),
    borderError: Color(0xFFFF3B30),
    borderInfo: Color(0xFF5CC4FF),
    interactivePrimaryBg: Color(0xFF5235BB),
    interactivePrimaryBgHover: Color(0xFF4219A3),
    interactivePrimaryBgActive: Color(0xFF2E067B),
    interactivePrimaryText: Color(0xFFFFFFFF),
    interactiveSecondaryBg: Color(0xFFFFFFFF),
    interactiveSecondaryBgHover: Color(0xFFF4F5F7),
    interactiveSecondaryBgActive: Color(0xFFF0F2F6),
    interactiveSecondaryText: Color(0xFF171B22),
    interactiveSecondaryBorder: Color(0xFFE2E8F3),
    interactiveDestructiveBg: Color(0xFFA30104),
    interactiveDestructiveBgHover: Color(0xFF810103),
    interactiveDestructiveText: Color(0xFFFFFFFF),
    interactiveGhostBg: Color(0xFFFFFFFF),
    interactiveGhostBgHover: Color(0xFFF0F2F6),
  );

  // ========================================================================
  // Semantic — Dark
  // ========================================================================
  static final VisorColorsData dark = VisorColorsData(
    textPrimary: Color(0xFFF4F5F7),
    textSecondary: Color(0xFFD8DFEC),
    textTertiary: Color(0xFF6C727E),
    textDisabled: Color(0xFF505561),
    textInverse: Color(0xFF171B22),
    textInverseSecondary: Color(0xFF3D424D),
    textLink: Color(0xFFDADAFF),
    textLinkHover: Color(0xFFE4E5FF),
    textSuccess: Color(0xFF34C759),
    textWarning: Color(0xFFFFCC01),
    textError: Color(0xFFFF3B30),
    textInfo: Color(0xFF5CC4FF),
    surfacePage: Color(0xFF1A1F22),
    surfaceCard: Color(0xFF242628),
    surfaceSubtle: Color(0xFF292E38),
    surfaceMuted: Color(0xFF3D424D),
    surfaceOverlay: Color(0xFF07090E),
    surfaceInteractiveDefault: Color(0xFF292E38),
    surfaceInteractiveHover: Color(0xFF3D424D),
    surfaceInteractiveActive: Color(0xFF505561),
    surfaceInteractiveDisabled: Color(0xFF292E38),
    surfaceSelected: Color(0xFF1B0052),
    surfaceAccentSubtle: Color(0xFF1B0052),
    surfaceAccentDefault: Color(0xFF6952D9),
    surfaceAccentStrong: Color(0xFFDADAFF),
    surfaceSuccessSubtle: Color(0xFF002207),
    surfaceSuccessDefault: Color(0xFF34C759),
    surfaceWarningSubtle: Color(0xFF231900),
    surfaceWarningDefault: Color(0xFFFFCC01),
    surfaceErrorSubtle: Color(0xFF3B0000),
    surfaceErrorDefault: Color(0xFFFF3B30),
    surfaceInfoSubtle: Color(0xFF001D2E),
    surfaceInfoDefault: Color(0xFF5CC4FF),
    borderDefault: Color(0xFF3D424D),
    borderMuted: Color(0xFF292E38),
    borderStrong: Color(0xFF505561),
    borderFocus: Color(0xFFDADAFF),
    borderDisabled: Color(0xFF292E38),
    borderSuccess: Color(0xFF34C759),
    borderWarning: Color(0xFFFFCC01),
    borderError: Color(0xFFFF3B30),
    borderInfo: Color(0xFF5CC4FF),
    interactivePrimaryBg: Color(0xFF6952D9),
    interactivePrimaryBgHover: Color(0xFFDADAFF),
    interactivePrimaryBgActive: Color(0xFFE4E5FF),
    interactivePrimaryText: Color(0xFFFFFFFF),
    interactiveSecondaryBg: Color(0xFF292E38),
    interactiveSecondaryBgHover: Color(0xFF3D424D),
    interactiveSecondaryBgActive: Color(0xFF505561),
    interactiveSecondaryText: Color(0xFFF4F5F7),
    interactiveSecondaryBorder: Color(0xFF505561),
    interactiveDestructiveBg: Color(0xFFFF3B30),
    interactiveDestructiveBgHover: Color(0xFFA30104),
    interactiveDestructiveText: Color(0xFFFFFFFF),
    interactiveGhostBg: Color(0xFF292E38),
    interactiveGhostBgHover: Color(0xFF3D424D),
  );
}
