import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdirSync, rmSync, writeFileSync, readFileSync, existsSync, statSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import { spawnSync } from "child_process";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ENSURER_PATH = resolve(__dirname, "../ensure-theme-overlays.mjs");

const CSS_STUB_CONTENT =
  "/* generated by `visor theme sync` — empty when no custom themes are present */\n";
const TS_STUB_CONTENT =
  'import type { ThemeGroup } from "./theme-config";\nexport const customThemeGroups: ThemeGroup[] = [];\n';

let testDir: string;

function runEnsurer(cwd: string): ReturnType<typeof spawnSync> {
  return spawnSync("node", [ENSURER_PATH], {
    cwd,
    encoding: "utf-8",
    env: { ...process.env },
  });
}

/**
 * Create a fake docs root at `testDir` that mirrors the packages/docs structure.
 * The ensurer resolves paths relative to its own location, so we need to
 * temporarily monkey-patch the script's behavior by running it from the test dir.
 * Instead we just call the logic directly via a helper that mirrors what the
 * ensurer does, since we can't easily relocate import.meta.url.
 *
 * We test the ensurer indirectly: run `node ensure-theme-overlays.mjs` pointing
 * at the actual docs directory and verify idempotency, then use a fake dir for
 * the "creates stubs" tests by temporarily moving the real overlays.
 */

describe("ensure-theme-overlays.mjs", () => {
  const docsRoot = resolve(__dirname, "../../");
  const cssPath = resolve(docsRoot, "app", "custom-themes.generated.css");
  const tsPath = resolve(docsRoot, "lib", "theme-config.custom.generated.ts");

  describe("idempotency — real docs directory", () => {
    it("does not error when overlay files already exist", () => {
      // pretest hook should have already created stubs
      const result = runEnsurer(docsRoot);
      expect(result.status).toBe(0);
      expect(result.stderr).toBe("");
    });

    it("does not modify existing overlay files (content unchanged)", () => {
      // Ensure files exist first
      expect(existsSync(cssPath)).toBe(true);
      expect(existsSync(tsPath)).toBe(true);

      const cssBefore = readFileSync(cssPath, "utf-8");
      const tsBefore = readFileSync(tsPath, "utf-8");

      runEnsurer(docsRoot);

      expect(readFileSync(cssPath, "utf-8")).toBe(cssBefore);
      expect(readFileSync(tsPath, "utf-8")).toBe(tsBefore);
    });
  });

  describe("stub creation — fresh environment", () => {
    beforeEach(() => {
      testDir = join(tmpdir(), `visor-ensure-test-${Date.now()}`);
      mkdirSync(join(testDir, "app"), { recursive: true });
      mkdirSync(join(testDir, "lib"), { recursive: true });
      mkdirSync(join(testDir, "scripts"), { recursive: true });
    });

    afterEach(() => {
      rmSync(testDir, { recursive: true, force: true });
    });

    /**
     * The ensurer resolves paths relative to import.meta.url (its own location),
     * so we can't run it from an arbitrary temp dir. Instead, we test the outcome:
     * if the overlay files are missing, the pretest hook creates them before any
     * test module loads. Here we verify the stubs have the expected content.
     */
    it("stubs have valid CSS content (comment-only, no @imports)", () => {
      expect(CSS_STUB_CONTENT).toMatch(/\/\*/);
      expect(CSS_STUB_CONTENT).not.toMatch(/@import/);
    });

    it("stubs have valid TS content (empty array export)", () => {
      expect(TS_STUB_CONTENT).toContain("customThemeGroups: ThemeGroup[] = []");
      expect(TS_STUB_CONTENT).toContain('import type { ThemeGroup }');
    });

    it("ensurer creates css stub when file is missing", () => {
      // Temporarily move the real css overlay out
      const tmpCss = cssPath + ".test-backup";
      const existed = existsSync(cssPath);
      if (existed) rmSync(cssPath);

      try {
        runEnsurer(docsRoot);
        expect(existsSync(cssPath)).toBe(true);
        const content = readFileSync(cssPath, "utf-8");
        expect(content).toContain("empty when no custom themes");
      } finally {
        if (existed && existsSync(tmpCss)) {
          // restore from backup if we had made one — but we didn't, just re-create
        }
        // re-run to restore (ensurer is idempotent, but we deleted the file)
        if (!existsSync(cssPath)) {
          runEnsurer(docsRoot);
        }
      }
    });

    it("ensurer creates ts stub when file is missing", () => {
      const existed = existsSync(tsPath);
      if (existed) rmSync(tsPath);

      try {
        runEnsurer(docsRoot);
        expect(existsSync(tsPath)).toBe(true);
        const content = readFileSync(tsPath, "utf-8");
        expect(content).toContain("customThemeGroups: ThemeGroup[] = []");
      } finally {
        if (!existsSync(tsPath)) {
          runEnsurer(docsRoot);
        }
      }
    });
  });
});
