// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.
// Source: .visor.yaml → Visor theme engine → flutter adapter.

import 'dart:ui';

import 'package:visor_core/visor_core.dart';

/// Generated color tokens for the borderless theme.
///
/// Do not edit this file manually — regenerate from .visor.yaml.
sealed class VisorColors {
  // ========================================================================
  // Anchors
  // ========================================================================
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);

  // ========================================================================
  // Primary scale
  // ========================================================================
  static const Color primary50 = Color(0xFFE9FAEF);
  static const Color primary100 = Color(0xFFDEFAE7);
  static const Color primary200 = Color(0xFFC7FADA);
  static const Color primary300 = Color(0xFFA6F9C7);
  static const Color primary400 = Color(0xFF83F2B2);
  static const Color primary500 = Color(0xFF6BEBA5);
  static const Color primary600 = Color(0xFF23B270);
  static const Color primary700 = Color(0xFF008952);
  static const Color primary800 = Color(0xFF005C35);
  static const Color primary900 = Color(0xFF00321B);
  static const Color primary950 = Color(0xFF000D04);

  // ========================================================================
  // Accent scale
  // ========================================================================
  static const Color accent50 = Color(0xFFE9FAEF);
  static const Color accent100 = Color(0xFFDEFAE7);
  static const Color accent200 = Color(0xFFC7FADA);
  static const Color accent300 = Color(0xFFA6F9C7);
  static const Color accent400 = Color(0xFF83F2B2);
  static const Color accent500 = Color(0xFF6BEBA5);
  static const Color accent600 = Color(0xFF23B270);
  static const Color accent700 = Color(0xFF008952);
  static const Color accent800 = Color(0xFF005C35);
  static const Color accent900 = Color(0xFF00321B);
  static const Color accent950 = Color(0xFF000D04);

  // ========================================================================
  // Neutral scale
  // ========================================================================
  static const Color neutral50 = Color(0xFFF5F5F5);
  static const Color neutral100 = Color(0xFFE0E0E0);
  static const Color neutral200 = Color(0xFFC2C2C2);
  static const Color neutral300 = Color(0xFF979797);
  static const Color neutral400 = Color(0xFF5C5C5C);
  static const Color neutral500 = Color(0xFF333333);
  static const Color neutral600 = Color(0xFF282828);
  static const Color neutral700 = Color(0xFF212121);
  static const Color neutral800 = Color(0xFF181818);
  static const Color neutral900 = Color(0xFF101011);
  static const Color neutral950 = Color(0xFF090909);

  // ========================================================================
  // Success scale
  // ========================================================================
  static const Color success50 = Color(0xFFE8FBEB);
  static const Color success100 = Color(0xFFD8F7DC);
  static const Color success500 = Color(0xFF22C55E);
  static const Color success600 = Color(0xFF019341);
  static const Color success700 = Color(0xFF017231);
  static const Color success900 = Color(0xFF002B0E);

  // ========================================================================
  // Warning scale
  // ========================================================================
  static const Color warning50 = Color(0xFFFFF3E6);
  static const Color warning100 = Color(0xFFFFEBD5);
  static const Color warning500 = Color(0xFFF59E0B);
  static const Color warning600 = Color(0xFFB77401);
  static const Color warning700 = Color(0xFF8D5800);
  static const Color warning900 = Color(0xFF361F00);

  // ========================================================================
  // Error scale
  // ========================================================================
  static const Color error50 = Color(0xFFFFF2F0);
  static const Color error100 = Color(0xFFFFE3E0);
  static const Color error500 = Color(0xFFEF4444);
  static const Color error600 = Color(0xFFC3041E);
  static const Color error700 = Color(0xFF990015);
  static const Color error900 = Color(0xFF410004);

  // ========================================================================
  // Info scale
  // ========================================================================
  static const Color info50 = Color(0xFFECF7FF);
  static const Color info100 = Color(0xFFDAF0FF);
  static const Color info500 = Color(0xFF0EA5E9);
  static const Color info600 = Color(0xFF017BAF);
  static const Color info700 = Color(0xFF005F88);
  static const Color info900 = Color(0xFF002437);

  // ========================================================================
  // Opacity variants (pre-computed at codegen)
  // ========================================================================
  static const Color primary500_5o = Color(0x0D6BEBA5);
  static const Color primary500_10o = Color(0x1A6BEBA5);
  static const Color primary500_20o = Color(0x336BEBA5);
  static const Color primary500_40o = Color(0x666BEBA5);
  static const Color primary500_50o = Color(0x806BEBA5);
  static const Color primary500_60o = Color(0x996BEBA5);
  static const Color primary500_80o = Color(0xCC6BEBA5);
  static const Color primary600_5o = Color(0x0D23B270);
  static const Color primary600_10o = Color(0x1A23B270);
  static const Color primary600_20o = Color(0x3323B270);
  static const Color primary600_40o = Color(0x6623B270);
  static const Color primary600_50o = Color(0x8023B270);
  static const Color primary600_60o = Color(0x9923B270);
  static const Color primary600_80o = Color(0xCC23B270);
  static const Color accent500_5o = Color(0x0D6BEBA5);
  static const Color accent500_10o = Color(0x1A6BEBA5);
  static const Color accent500_20o = Color(0x336BEBA5);
  static const Color accent500_40o = Color(0x666BEBA5);
  static const Color accent500_50o = Color(0x806BEBA5);
  static const Color accent500_60o = Color(0x996BEBA5);
  static const Color accent500_80o = Color(0xCC6BEBA5);
  static const Color white_5o = Color(0x0DFFFFFF);
  static const Color white_10o = Color(0x1AFFFFFF);
  static const Color white_20o = Color(0x33FFFFFF);
  static const Color white_40o = Color(0x66FFFFFF);
  static const Color white_50o = Color(0x80FFFFFF);
  static const Color white_60o = Color(0x99FFFFFF);
  static const Color white_80o = Color(0xCCFFFFFF);
  static const Color black_5o = Color(0x0D000000);
  static const Color black_10o = Color(0x1A000000);
  static const Color black_20o = Color(0x33000000);
  static const Color black_40o = Color(0x66000000);
  static const Color black_50o = Color(0x80000000);
  static const Color black_60o = Color(0x99000000);
  static const Color black_80o = Color(0xCC000000);

  // ========================================================================
  // Semantic — Light
  // ========================================================================
  static final VisorColorsData light = VisorColorsData(
    textPrimary: Color(0xFFF5F5F5),
    textSecondary: Color(0xFFC2C2C2),
    textTertiary: Color(0xFF999999),
    textDisabled: Color(0xFF595959),
    textInverse: Color(0xFFFFFFFF),
    textInverseSecondary: Color(0xFFC2C2C2),
    textLink: Color(0xFF23B270),
    textLinkHover: Color(0xFF008952),
    textSuccess: Color(0xFF017231),
    textWarning: Color(0xFF8D5800),
    textError: Color(0xFF990015),
    textInfo: Color(0xFF005F88),
    surfacePage: Color(0xFF0A0A0C),
    surfaceCard: Color(0xFF111115),
    surfaceSubtle: Color(0xFF0E0E10),
    surfaceMuted: Color(0xFF191919),
    surfaceOverlay: Color(0xFF101011),
    surfaceInteractiveDefault: Color(0x00000000),
    surfaceInteractiveHover: Color(0xFF191919),
    surfaceInteractiveActive: Color(0xFF212124),
    surfaceInteractiveDisabled: Color(0xFF0E0E10),
    surfaceSelected: Color(0xFF212124),
    surfaceAccentSubtle: Color(0xFF1A1A1D),
    surfaceAccentDefault: Color(0xFF6BEBA5),
    surfaceAccentStrong: Color(0xFF23B270),
    surfaceSuccessSubtle: Color(0xFF003814),
    surfaceSuccessDefault: Color(0xFF22C55E),
    surfaceWarningSubtle: Color(0xFF432600),
    surfaceWarningDefault: Color(0xFFF59E0B),
    surfaceErrorSubtle: Color(0xFF4E0006),
    surfaceErrorDefault: Color(0xFFEF4444),
    surfaceInfoSubtle: Color(0xFF002E44),
    surfaceInfoDefault: Color(0xFF0EA5E9),
    borderDefault: Color(0x00000000),
    borderMuted: Color(0x00000000),
    borderStrong: Color(0x00000000),
    borderFocus: Color(0xFF6BEBA5),
    borderDisabled: Color(0x00000000),
    borderSuccess: Color(0xFF22C55E),
    borderWarning: Color(0xFFF59E0B),
    borderError: Color(0xFFEF4444),
    borderInfo: Color(0xFF0EA5E9),
    interactivePrimaryBg: Color(0xFF23B270),
    interactivePrimaryBgHover: Color(0xFF008952),
    interactivePrimaryBgActive: Color(0xFF005C35),
    interactivePrimaryText: Color(0xFFFFFFFF),
    interactiveSecondaryBg: Color(0xFF191919),
    interactiveSecondaryBgHover: Color(0xFF212124),
    interactiveSecondaryBgActive: Color(0xFF2A2A2E),
    interactiveSecondaryText: Color(0xFFF5F5F5),
    interactiveSecondaryBorder: Color(0x00000000),
    interactiveDestructiveBg: Color(0xFFC3041E),
    interactiveDestructiveBgHover: Color(0xFF990015),
    interactiveDestructiveText: Color(0xFFFFFFFF),
    interactiveGhostBg: Color(0x00000000),
    interactiveGhostBgHover: Color(0xFF191919),
  );

  // ========================================================================
  // Semantic — Dark
  // ========================================================================
  static final VisorColorsData dark = VisorColorsData(
    textPrimary: Color(0xFFF5F5F5),
    textSecondary: Color(0xFFC2C2C2),
    textTertiary: Color(0xFF999999),
    textDisabled: Color(0xFF282828),
    textInverse: Color(0xFF101011),
    textInverseSecondary: Color(0xFF212121),
    textLink: Color(0xFF83F2B2),
    textLinkHover: Color(0xFFA6F9C7),
    textSuccess: Color(0xFF22C55E),
    textWarning: Color(0xFFF59E0B),
    textError: Color(0xFFEF4444),
    textInfo: Color(0xFF0EA5E9),
    surfacePage: Color(0xFF0A0A0C),
    surfaceCard: Color(0xFF111115),
    surfaceSubtle: Color(0xFF181818),
    surfaceMuted: Color(0xFF191919),
    surfaceOverlay: Color(0xFF090909),
    surfaceInteractiveDefault: Color(0xFF181818),
    surfaceInteractiveHover: Color(0xFF212121),
    surfaceInteractiveActive: Color(0xFF282828),
    surfaceInteractiveDisabled: Color(0xFF181818),
    surfaceSelected: Color(0xFF005C35),
    surfaceAccentSubtle: Color(0xFF00321B),
    surfaceAccentDefault: Color(0xFF6BEBA5),
    surfaceAccentStrong: Color(0xFF83F2B2),
    surfaceSuccessSubtle: Color(0xFF002B0E),
    surfaceSuccessDefault: Color(0xFF22C55E),
    surfaceWarningSubtle: Color(0xFF361F00),
    surfaceWarningDefault: Color(0xFFF59E0B),
    surfaceErrorSubtle: Color(0xFF410004),
    surfaceErrorDefault: Color(0xFFEF4444),
    surfaceInfoSubtle: Color(0xFF002437),
    surfaceInfoDefault: Color(0xFF0EA5E9),
    borderDefault: Color(0x00000000),
    borderMuted: Color(0x00000000),
    borderStrong: Color(0x00000000),
    borderFocus: Color(0xFF83F2B2),
    borderDisabled: Color(0xFF181818),
    borderSuccess: Color(0xFF22C55E),
    borderWarning: Color(0xFFF59E0B),
    borderError: Color(0xFFEF4444),
    borderInfo: Color(0xFF0EA5E9),
    interactivePrimaryBg: Color(0xFF6BEBA5),
    interactivePrimaryBgHover: Color(0xFF83F2B2),
    interactivePrimaryBgActive: Color(0xFFA6F9C7),
    interactivePrimaryText: Color(0xFFFFFFFF),
    interactiveSecondaryBg: Color(0xFF181818),
    interactiveSecondaryBgHover: Color(0xFF212121),
    interactiveSecondaryBgActive: Color(0xFF282828),
    interactiveSecondaryText: Color(0xFFF5F5F5),
    interactiveSecondaryBorder: Color(0xFF282828),
    interactiveDestructiveBg: Color(0xFFEF4444),
    interactiveDestructiveBgHover: Color(0xFFC3041E),
    interactiveDestructiveText: Color(0xFFFFFFFF),
    interactiveGhostBg: Color(0xFF181818),
    interactiveGhostBgHover: Color(0xFF212121),
  );
}
