// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `npm run themes:apply-flutter`.
//
// Aggregates Dart ThemeData for all Visor themes.
// Access themes via [VisorThemes], e.g. VisorThemes.blackout.light

import 'package:flutter/material.dart';

// Re-export visor_core so consumers access VisorColorsData etc. with
// a single import of this package.
export 'package:visor_core/visor_core.dart';

import 'src/blackout/theme/visor_theme.dart' as blackout_t;
import 'src/borderless/theme/visor_theme.dart' as borderless_t;
import 'src/modern-minimal/theme/visor_theme.dart' as modern_minimal_t;
import 'src/neutral/theme/visor_theme.dart' as neutral_t;
import 'src/space/theme/visor_theme.dart' as space_t;

/// A light/dark [ThemeData] pair for a single Visor theme.
class VisorThemePair {
  final ThemeData light;
  final ThemeData dark;
  const VisorThemePair({required this.light, required this.dark});
}

/// Static access to all Visor-generated Flutter themes.
///
/// Usage:
/// ```dart
/// MaterialApp(
///   theme: VisorThemes.blackout.light,
///   darkTheme: VisorThemes.blackout.dark,
/// );
/// ```
sealed class VisorThemes {
  static VisorThemePair get blackout => VisorThemePair(
    light: blackout_t.VisorAppTheme.light,
    dark: blackout_t.VisorAppTheme.dark,
  );
  static VisorThemePair get borderless => VisorThemePair(
    light: borderless_t.VisorAppTheme.light,
    dark: borderless_t.VisorAppTheme.dark,
  );
  static VisorThemePair get modernMinimal => VisorThemePair(
    light: modern_minimal_t.VisorAppTheme.light,
    dark: modern_minimal_t.VisorAppTheme.dark,
  );
  static VisorThemePair get neutral => VisorThemePair(
    light: neutral_t.VisorAppTheme.light,
    dark: neutral_t.VisorAppTheme.dark,
  );
  static VisorThemePair get space => VisorThemePair(
    light: space_t.VisorAppTheme.light,
    dark: space_t.VisorAppTheme.dark,
  );
}
