// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `npm run themes:apply-flutter`.
//
// Aggregates Dart ThemeData for all Visor themes (4 stock + 7 custom).
// Access themes via [VisorThemes], e.g. VisorThemes.blackout.light

import 'package:flutter/material.dart';

// Re-export visor_core so consumers access VisorColorsData etc. with
// a single import of this package.
export 'package:visor_core/visor_core.dart';

import 'src/blackout/theme/visor_theme.dart' as blackout_t;
import 'src/borderless/theme/visor_theme.dart' as borderless_t;
import 'src/modern-minimal/theme/visor_theme.dart' as modern_minimal_t;
import 'src/neutral/theme/visor_theme.dart' as neutral_t;
import 'src/space/theme/visor_theme.dart' as space_t;
import 'src/blacklight-underground/theme/visor_theme.dart' as blacklight_underground_t;
import 'src/blacklight/theme/visor_theme.dart' as blacklight_t;
import 'src/entr/theme/visor_theme.dart' as entr_t;
import 'src/kaiah/theme/visor_theme.dart' as kaiah_t;
import 'src/reference-app/theme/visor_theme.dart' as reference_app_t;
import 'src/solespark/theme/visor_theme.dart' as solespark_t;
import 'src/veronica/theme/visor_theme.dart' as veronica_t;

/// A light/dark [ThemeData] pair for a single Visor theme.
class VisorThemePair {
  final ThemeData light;
  final ThemeData dark;
  const VisorThemePair({required this.light, required this.dark});
}

/// Static access to all Visor-generated Flutter themes.
///
/// Usage:
/// ```dart
/// MaterialApp(
///   theme: VisorThemes.blackout.light,
///   darkTheme: VisorThemes.blackout.dark,
/// );
/// ```
sealed class VisorThemes {
  static VisorThemePair get blackout => VisorThemePair(
    light: blackout_t.VisorAppTheme.light,
    dark: blackout_t.VisorAppTheme.dark,
  );
  static VisorThemePair get borderless => VisorThemePair(
    light: borderless_t.VisorAppTheme.light,
    dark: borderless_t.VisorAppTheme.dark,
  );
  static VisorThemePair get modernMinimal => VisorThemePair(
    light: modern_minimal_t.VisorAppTheme.light,
    dark: modern_minimal_t.VisorAppTheme.dark,
  );
  static VisorThemePair get neutral => VisorThemePair(
    light: neutral_t.VisorAppTheme.light,
    dark: neutral_t.VisorAppTheme.dark,
  );
  static VisorThemePair get space => VisorThemePair(
    light: space_t.VisorAppTheme.light,
    dark: space_t.VisorAppTheme.dark,
  );
  static VisorThemePair get blacklightUnderground => VisorThemePair(
    light: blacklight_underground_t.VisorAppTheme.light,
    dark: blacklight_underground_t.VisorAppTheme.dark,
  );
  static VisorThemePair get blacklight => VisorThemePair(
    light: blacklight_t.VisorAppTheme.light,
    dark: blacklight_t.VisorAppTheme.dark,
  );
  static VisorThemePair get entr => VisorThemePair(
    light: entr_t.VisorAppTheme.light,
    dark: entr_t.VisorAppTheme.dark,
  );
  static VisorThemePair get kaiah => VisorThemePair(
    light: kaiah_t.VisorAppTheme.light,
    dark: kaiah_t.VisorAppTheme.dark,
  );
  static VisorThemePair get referenceApp => VisorThemePair(
    light: reference_app_t.VisorAppTheme.light,
    dark: reference_app_t.VisorAppTheme.dark,
  );
  static VisorThemePair get solespark => VisorThemePair(
    light: solespark_t.VisorAppTheme.light,
    dark: solespark_t.VisorAppTheme.dark,
  );
  static VisorThemePair get veronica => VisorThemePair(
    light: veronica_t.VisorAppTheme.light,
    dark: veronica_t.VisorAppTheme.dark,
  );
}
