// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';

/// Generated elevation/shadow tokens.
///
/// Each value is a `List<BoxShadow>` — CSS box-shadow strings
/// supporting multi-layer shadows compile to the same list here.
sealed class VisorShadows {
  static final VisorShadowsData instance = VisorShadowsData(
    xs: const <BoxShadow>[],
    sm: const <BoxShadow>[],
    md: const <BoxShadow>[],
    lg: const <BoxShadow>[],
    xl: const <BoxShadow>[],
  );
}
