/**
 * CSS Token Generator
 *
 * Reads token definitions from src/tokens/ and outputs:
 *   dist/tokens.css — all CSS custom properties organized by tier
 *   dist/primitives.css — primitive tokens only
 *   dist/semantic.css — semantic tokens only
 *   dist/themes/light.css — light theme adaptive tokens
 *   dist/themes/dark.css — dark theme adaptive tokens
 *   dist/index.css — full bundle (imports all above)
 */

import { writeFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

import {
  primitiveColors,
  primitiveSpacing,
  primitiveRadius,
  primitiveBorderWidths,
  primitiveFontSizes,
  primitiveFontWeights,
  primitiveLineHeights,
  primitiveShadows,
  primitiveZIndex,
  primitiveFontFamilies,
} from "../tokens/primitives.js";

import {
  semanticText,
  semanticSurface,
  semanticBorder,
  semanticInteractive,
  semanticSpacing,
  semanticTypography,
} from "../tokens/semantic.js";

import {
  adaptiveText,
  adaptiveSurface,
  adaptiveBorder,
} from "../tokens/adaptive.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_DIR = join(__dirname, "../../dist");
const THEMES_DIR = join(DIST_DIR, "themes");

// ============================================================
// Helpers
// ============================================================

function ensureDirs(): void {
  if (!existsSync(DIST_DIR)) mkdirSync(DIST_DIR, { recursive: true });
  if (!existsSync(THEMES_DIR)) mkdirSync(THEMES_DIR, { recursive: true });
}

function header(label: string): string {
  return [
    "/* ============================================",
    `   ${label}`,
    "   Generated by @loworbit/visor-tokens",
    "   DO NOT EDIT — run `npm run build` to regenerate",
    "   ============================================ */",
    "",
  ].join("\n");
}

function sectionComment(label: string): string {
  return `\n/* --- ${label} --- */`;
}

/** Wrap lines in a CSS rule block */
function block(selector: string, declarations: string[]): string {
  if (declarations.length === 0) return "";
  return [selector + " {", ...declarations.map((d) => `  ${d}`), "}", ""].join(
    "\n"
  );
}

/** Convert a token name reference like "color-gray-900" to "var(--color-gray-900)" */
function toVar(ref: string): string {
  return `var(--${ref})`;
}

// ============================================================
// Primitive CSS generation
// ============================================================

function generatePrimitivesCSS(): string {
  const lines: string[] = [];

  // Colors
  lines.push(sectionComment("Primitive: Colors"));
  const colorDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveColors)) {
    colorDecls.push(`--color-${name}: ${value};`);
  }
  lines.push(block(":root", colorDecls));

  // Spacing
  lines.push(sectionComment("Primitive: Spacing"));
  const spacingDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveSpacing)) {
    const rem = px === 0 ? "0" : `${px / 16}rem`;
    spacingDecls.push(`--spacing-${name}: ${rem}; /* ${px}px */`);
  }
  lines.push(block(":root", spacingDecls));

  // Border Radius
  lines.push(sectionComment("Primitive: Border Radius"));
  const radiusDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveRadius)) {
    if (px >= 9999) {
      radiusDecls.push(`--radius-${name}: 9999px;`);
    } else if (px === 0) {
      radiusDecls.push(`--radius-${name}: 0;`);
    } else {
      radiusDecls.push(`--radius-${name}: ${px / 16}rem; /* ${px}px */`);
    }
  }
  lines.push(block(":root", radiusDecls));

  // Border Widths
  lines.push(sectionComment("Primitive: Border Widths"));
  const borderWidthDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveBorderWidths)) {
    borderWidthDecls.push(`--border-width-${name}: ${px}px;`);
  }
  lines.push(block(":root", borderWidthDecls));

  // Font Families
  lines.push(sectionComment("Primitive: Font Families"));
  const fontFamilyDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveFontFamilies)) {
    fontFamilyDecls.push(`--font-${name}: ${value};`);
  }
  lines.push(block(":root", fontFamilyDecls));

  // Font Sizes
  lines.push(sectionComment("Primitive: Font Sizes"));
  const fontSizeDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveFontSizes)) {
    fontSizeDecls.push(`--font-size-${name}: ${px / 16}rem; /* ${px}px */`);
  }
  lines.push(block(":root", fontSizeDecls));

  // Font Weights
  lines.push(sectionComment("Primitive: Font Weights"));
  const fontWeightDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveFontWeights)) {
    fontWeightDecls.push(`--font-weight-${name}: ${value};`);
  }
  lines.push(block(":root", fontWeightDecls));

  // Line Heights
  lines.push(sectionComment("Primitive: Line Heights"));
  const lineHeightDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveLineHeights)) {
    lineHeightDecls.push(`--line-height-${name}: ${value};`);
  }
  lines.push(block(":root", lineHeightDecls));

  // Shadows
  lines.push(sectionComment("Primitive: Shadows"));
  const shadowDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveShadows)) {
    shadowDecls.push(`--shadow-${name}: ${value};`);
  }
  lines.push(block(":root", shadowDecls));

  // Z-index
  lines.push(sectionComment("Primitive: Z-Index"));
  const zIndexDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveZIndex)) {
    zIndexDecls.push(`--z-${name}: ${value};`);
  }
  lines.push(block(":root", zIndexDecls));

  return header("Visor Design Tokens — Primitives") + lines.join("\n");
}

// ============================================================
// Semantic CSS generation
// ============================================================

function generateSemanticCSS(): string {
  const lines: string[] = [];

  // Text
  lines.push(sectionComment("Semantic: Text"));
  const textDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticText)) {
    textDecls.push(`--text-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", textDecls));

  // Surface
  lines.push(sectionComment("Semantic: Surface"));
  const surfaceDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticSurface)) {
    surfaceDecls.push(`--surface-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", surfaceDecls));

  // Border
  lines.push(sectionComment("Semantic: Border"));
  const borderDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticBorder)) {
    borderDecls.push(`--border-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", borderDecls));

  // Interactive
  lines.push(sectionComment("Semantic: Interactive"));
  const interactiveDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticInteractive)) {
    interactiveDecls.push(`--interactive-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", interactiveDecls));

  // Spacing
  lines.push(sectionComment("Semantic: Spacing"));
  const spacingDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticSpacing)) {
    spacingDecls.push(`--${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", spacingDecls));

  // Typography
  lines.push(sectionComment("Semantic: Typography"));
  const typographyDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticTypography)) {
    typographyDecls.push(`--${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", typographyDecls));

  return header("Visor Design Tokens — Semantic") + lines.join("\n");
}

// ============================================================
// Adaptive (theme) CSS generation
// ============================================================

function generateThemeCSS(theme: "light" | "dark"): string {
  const selector = theme === "light" ? ":root" : ".theme-dark";
  const lines: string[] = [];

  lines.push(sectionComment(`Adaptive: Text (${theme})`));
  const textDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveText)) {
    textDecls.push(`--text-${name}: ${toVar(values[theme])};`);
  }
  lines.push(block(selector, textDecls));

  lines.push(sectionComment(`Adaptive: Surface (${theme})`));
  const surfaceDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveSurface)) {
    surfaceDecls.push(`--surface-${name}: ${toVar(values[theme])};`);
  }
  lines.push(block(selector, surfaceDecls));

  lines.push(sectionComment(`Adaptive: Border (${theme})`));
  const borderDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveBorder)) {
    borderDecls.push(`--border-${name}: ${toVar(values[theme])};`);
  }
  lines.push(block(selector, borderDecls));

  const themeLabel = theme === "light" ? "Light Theme" : "Dark Theme";
  return header(`Visor Design Tokens — ${themeLabel}`) + lines.join("\n");
}

// ============================================================
// Full bundle (tokens.css)
// ============================================================

function generateTokensCSS(): string {
  const lines: string[] = [
    header("Visor Design Tokens — Full Bundle"),
    "/* Import order: primitives → semantic → adaptive */",
    "",
    "/* ============================================",
    "   Tier 1: Primitives",
    "   ============================================ */",
  ];

  // Primitives inlined
  const primitivesContent = generatePrimitivesCSS();
  // Strip the header from the primitives content (first 6 lines are header)
  const primitivesBody = primitivesContent
    .split("\n")
    .slice(6)
    .join("\n");
  lines.push(primitivesBody);

  lines.push(
    "/* ============================================",
    "   Tier 2: Semantic",
    "   ============================================ */"
  );
  const semanticContent = generateSemanticCSS();
  const semanticBody = semanticContent.split("\n").slice(6).join("\n");
  lines.push(semanticBody);

  lines.push(
    "/* ============================================",
    "   Tier 3: Adaptive — Light Theme (:root)",
    "   ============================================ */"
  );
  const lightContent = generateThemeCSS("light");
  const lightBody = lightContent.split("\n").slice(6).join("\n");
  lines.push(lightBody);

  lines.push(
    "/* ============================================",
    "   Tier 3: Adaptive — Dark Theme (.theme-dark)",
    "   ============================================ */"
  );
  const darkContent = generateThemeCSS("dark");
  const darkBody = darkContent.split("\n").slice(6).join("\n");
  lines.push(darkBody);

  return lines.join("\n");
}

// ============================================================
// Index CSS (entry point)
// ============================================================

function generateIndexCSS(): string {
  return [
    header("Visor Design Tokens — Index"),
    "/* Full design token bundle */",
    "@import './tokens.css';",
    "",
  ].join("\n");
}

// ============================================================
// Main
// ============================================================

function main(): void {
  console.log("Generating Visor design tokens...\n");

  ensureDirs();

  // Generate primitives.css
  const primitivesCSS = generatePrimitivesCSS();
  writeFileSync(join(DIST_DIR, "primitives.css"), primitivesCSS, "utf-8");
  console.log("✓ dist/primitives.css");

  // Generate semantic.css
  const semanticCSS = generateSemanticCSS();
  writeFileSync(join(DIST_DIR, "semantic.css"), semanticCSS, "utf-8");
  console.log("✓ dist/semantic.css");

  // Generate light theme
  const lightCSS = generateThemeCSS("light");
  writeFileSync(join(THEMES_DIR, "light.css"), lightCSS, "utf-8");
  console.log("✓ dist/themes/light.css");

  // Generate dark theme
  const darkCSS = generateThemeCSS("dark");
  writeFileSync(join(THEMES_DIR, "dark.css"), darkCSS, "utf-8");
  console.log("✓ dist/themes/dark.css");

  // Generate full bundle
  const tokensCSS = generateTokensCSS();
  writeFileSync(join(DIST_DIR, "tokens.css"), tokensCSS, "utf-8");
  console.log("✓ dist/tokens.css");

  // Generate index.css entry point
  const indexCSS = generateIndexCSS();
  writeFileSync(join(DIST_DIR, "index.css"), indexCSS, "utf-8");
  console.log("✓ dist/index.css");

  console.log("\nToken counts:");
  console.log(
    `  Primitive colors: ${Object.keys(primitiveColors).length}`
  );
  console.log(`  Spacing steps: ${Object.keys(primitiveSpacing).length}`);
  console.log(`  Radius steps: ${Object.keys(primitiveRadius).length}`);
  console.log(`  Shadow steps: ${Object.keys(primitiveShadows).length}`);
  console.log(
    `  Semantic text: ${Object.keys(semanticText).length}`
  );
  console.log(
    `  Semantic surface: ${Object.keys(semanticSurface).length}`
  );
  console.log(
    `  Semantic border: ${Object.keys(semanticBorder).length}`
  );
  console.log(
    `  Adaptive text: ${Object.keys(adaptiveText).length} (light + dark)`
  );
  console.log(
    `  Adaptive surface: ${Object.keys(adaptiveSurface).length} (light + dark)`
  );
  console.log(
    `  Adaptive border: ${Object.keys(adaptiveBorder).length} (light + dark)`
  );

  console.log("\n✓ Token generation complete");
}

main();
