/**
 * CSS Token Generator
 *
 * Reads token definitions from src/tokens/ and outputs:
 *   dist/tokens.css — all CSS custom properties organized by tier
 *   dist/primitives.css — primitive tokens only
 *   dist/semantic.css — semantic tokens only
 *   dist/themes/light.css — light theme adaptive tokens
 *   dist/themes/dark.css — dark theme adaptive tokens
 *   dist/index.css — full bundle (imports all above)
 */

import { writeFileSync, readFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

import { generateThemeData } from "@loworbitstudio/visor-theme-engine";
import { docsAdapter } from "@loworbitstudio/visor-theme-engine/adapters";

import {
  primitiveColors,
  primitiveSpacing,
  primitiveRadius,
  primitiveBorderWidths,
  primitiveFontSizes,
  primitiveFontWeights,
  primitiveLineHeights,
  primitiveShadows,
  primitiveShadowsDark,
  primitiveZIndex,
  primitiveFontFamilies,
  primitiveOverlay,
  primitiveFocusRing,
  primitiveMotionDurations,
  primitiveMotionEasings,
} from "../tokens/primitives.js";

import {
  semanticText,
  semanticSurface,
  semanticBorder,
  semanticInteractive,
  semanticSpacing,
  semanticTypography,
  semanticOverlay,
  semanticFocusRing,
  semanticMotionDuration,
  semanticMotionEasing,
  semanticSkeleton,
  semanticChart,
  semanticSidebar,
} from "../tokens/semantic.js";

import {
  adaptiveText,
  adaptiveSurface,
  adaptiveBorder,
  adaptiveInteractive,
  adaptiveSkeleton,
  adaptiveChart,
  adaptiveSidebar,
} from "../tokens/adaptive.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST_DIR = join(__dirname, "../../dist");
const THEMES_DIR = join(DIST_DIR, "themes");
// Repo-root themes dir (packages/tokens/src/generate → ../../../../themes)
const STOCK_THEMES_DIR = join(__dirname, "../../../../themes");

const STOCK_THEMES = ["blackout", "modern-minimal", "neutral", "space"] as const;

// ============================================================
// Helpers
// ============================================================

function ensureDirs(): void {
  if (!existsSync(DIST_DIR)) mkdirSync(DIST_DIR, { recursive: true });
  if (!existsSync(THEMES_DIR)) mkdirSync(THEMES_DIR, { recursive: true });
}

function header(label: string): string {
  return [
    "/* ============================================",
    `   ${label}`,
    "   Generated by @loworbitstudio/visor-core",
    "   DO NOT EDIT — run `npm run build` to regenerate",
    "   ============================================ */",
    "",
  ].join("\n");
}

function sectionComment(label: string): string {
  return `\n/* --- ${label} --- */`;
}

/** Wrap lines in a CSS rule block */
function block(selector: string, declarations: string[]): string {
  if (declarations.length === 0) return "";
  return [selector + " {", ...declarations.map((d) => `  ${d}`), "}", ""].join(
    "\n"
  );
}

/** Convert a token name reference like "color-gray-900" to "var(--color-gray-900)" */
function toVar(ref: string): string {
  return `var(--${ref})`;
}

// ============================================================
// Primitive CSS generation
// ============================================================

function generatePrimitivesCSS(): string {
  const lines: string[] = [];

  // Colors
  lines.push(sectionComment("Primitive: Colors"));
  const colorDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveColors)) {
    colorDecls.push(`--color-${name}: ${value};`);
  }
  lines.push(block(":root", colorDecls));

  // Spacing
  lines.push(sectionComment("Primitive: Spacing"));
  const spacingDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveSpacing)) {
    const rem = px === 0 ? "0" : `${px / 16}rem`;
    spacingDecls.push(`--spacing-${name}: ${rem}; /* ${px}px */`);
  }
  lines.push(block(":root", spacingDecls));

  // Border Radius
  lines.push(sectionComment("Primitive: Border Radius"));
  const radiusDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveRadius)) {
    if (px >= 9999) {
      radiusDecls.push(`--radius-${name}: 9999px;`);
    } else if (px === 0) {
      radiusDecls.push(`--radius-${name}: 0;`);
    } else {
      radiusDecls.push(`--radius-${name}: ${px / 16}rem; /* ${px}px */`);
    }
  }
  lines.push(block(":root", radiusDecls));

  // Border Widths
  lines.push(sectionComment("Primitive: Border Widths"));
  const borderWidthDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveBorderWidths)) {
    borderWidthDecls.push(`--border-width-${name}: ${px}px;`);
  }
  lines.push(block(":root", borderWidthDecls));

  // Font Families
  lines.push(sectionComment("Primitive: Font Families"));
  const fontFamilyDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveFontFamilies)) {
    fontFamilyDecls.push(`--font-${name}: ${value};`);
  }
  lines.push(block(":root", fontFamilyDecls));

  // Font Sizes
  lines.push(sectionComment("Primitive: Font Sizes"));
  const fontSizeDecls: string[] = [];
  for (const [name, px] of Object.entries(primitiveFontSizes)) {
    fontSizeDecls.push(`--font-size-${name}: ${px / 16}rem; /* ${px}px */`);
  }
  lines.push(block(":root", fontSizeDecls));

  // Font Weights
  lines.push(sectionComment("Primitive: Font Weights"));
  const fontWeightDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveFontWeights)) {
    fontWeightDecls.push(`--font-weight-${name}: ${value};`);
  }
  lines.push(block(":root", fontWeightDecls));

  // Line Heights
  lines.push(sectionComment("Primitive: Line Heights"));
  const lineHeightDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveLineHeights)) {
    lineHeightDecls.push(`--line-height-${name}: ${value};`);
  }
  lines.push(block(":root", lineHeightDecls));

  // Shadows
  lines.push(sectionComment("Primitive: Shadows"));
  const shadowDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveShadows)) {
    shadowDecls.push(`--shadow-${name}: ${value};`);
  }
  lines.push(block(":root", shadowDecls));

  // Z-index
  lines.push(sectionComment("Primitive: Z-Index"));
  const zIndexDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveZIndex)) {
    zIndexDecls.push(`--z-${name}: ${value};`);
  }
  lines.push(block(":root", zIndexDecls));

  // Overlay
  lines.push(sectionComment("Primitive: Overlay"));
  const overlayDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveOverlay)) {
    overlayDecls.push(`--overlay-${name}: ${value};`);
  }
  lines.push(block(":root", overlayDecls));

  // Focus Ring
  lines.push(sectionComment("Primitive: Focus Ring"));
  const focusRingDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveFocusRing)) {
    focusRingDecls.push(`--focus-ring-${name}: ${value};`);
  }
  lines.push(block(":root", focusRingDecls));

  // Motion Durations
  lines.push(sectionComment("Primitive: Motion Durations"));
  const motionDurationDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveMotionDurations)) {
    motionDurationDecls.push(`--motion-duration-${name}: ${value};`);
  }
  lines.push(block(":root", motionDurationDecls));

  // Motion Easings
  lines.push(sectionComment("Primitive: Motion Easings"));
  const motionEasingDecls: string[] = [];
  for (const [name, value] of Object.entries(primitiveMotionEasings)) {
    motionEasingDecls.push(`--motion-easing-${name}: ${value};`);
  }
  lines.push(block(":root", motionEasingDecls));

  return header("Visor Design Tokens — Primitives") + lines.join("\n");
}

// ============================================================
// Semantic CSS generation
// ============================================================

function generateSemanticCSS(): string {
  const lines: string[] = [];

  // Text
  lines.push(sectionComment("Semantic: Text"));
  const textDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticText)) {
    textDecls.push(`--text-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", textDecls));

  // Surface
  lines.push(sectionComment("Semantic: Surface"));
  const surfaceDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticSurface)) {
    surfaceDecls.push(`--surface-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", surfaceDecls));

  // Border
  lines.push(sectionComment("Semantic: Border"));
  const borderDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticBorder)) {
    borderDecls.push(`--border-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", borderDecls));

  // Interactive
  lines.push(sectionComment("Semantic: Interactive"));
  const interactiveDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticInteractive)) {
    interactiveDecls.push(`--interactive-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", interactiveDecls));

  // Spacing
  lines.push(sectionComment("Semantic: Spacing"));
  const spacingDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticSpacing)) {
    spacingDecls.push(`--${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", spacingDecls));

  // Typography
  lines.push(sectionComment("Semantic: Typography"));
  const typographyDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticTypography)) {
    typographyDecls.push(`--${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", typographyDecls));

  // Motion Duration
  lines.push(sectionComment("Semantic: Motion Duration"));
  const motionDurationDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticMotionDuration)) {
    motionDurationDecls.push(`--motion-duration-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", motionDurationDecls));

  // Motion Easing
  lines.push(sectionComment("Semantic: Motion Easing"));
  const motionEasingDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticMotionEasing)) {
    motionEasingDecls.push(`--motion-easing-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", motionEasingDecls));

  // Overlay
  lines.push(sectionComment("Semantic: Overlay"));
  const overlaySemanticDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticOverlay)) {
    overlaySemanticDecls.push(`--overlay-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", overlaySemanticDecls));

  // Focus Ring
  lines.push(sectionComment("Semantic: Focus Ring"));
  const focusRingSemanticDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticFocusRing)) {
    focusRingSemanticDecls.push(`--focus-ring-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", focusRingSemanticDecls));

  // Skeleton
  lines.push(sectionComment("Semantic: Skeleton"));
  const skeletonDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticSkeleton)) {
    skeletonDecls.push(`--skeleton-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", skeletonDecls));

  // Chart
  lines.push(sectionComment("Semantic: Chart"));
  const chartDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticChart)) {
    chartDecls.push(`--chart-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", chartDecls));

  // Sidebar
  lines.push(sectionComment("Semantic: Sidebar"));
  const sidebarDecls: string[] = [];
  for (const [name, ref] of Object.entries(semanticSidebar)) {
    sidebarDecls.push(`--sidebar-${name}: ${toVar(ref)};`);
  }
  lines.push(block(":root", sidebarDecls));

  return header("Visor Design Tokens — Semantic") + lines.join("\n");
}

// ============================================================
// Adaptive (theme) CSS generation
// ============================================================

/** Build adaptive token declarations for a given theme variant */
function buildAdaptiveDecls(theme: "light" | "dark"): {
  textDecls: string[];
  surfaceDecls: string[];
  borderDecls: string[];
  interactiveDecls: string[];
  skeletonDecls: string[];
  shadowDecls: string[];
  chartDecls: string[];
  sidebarDecls: string[];
} {
  const textDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveText)) {
    textDecls.push(`--text-${name}: ${toVar(values[theme])};`);
  }

  const surfaceDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveSurface)) {
    surfaceDecls.push(`--surface-${name}: ${toVar(values[theme])};`);
  }

  const borderDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveBorder)) {
    borderDecls.push(`--border-${name}: ${toVar(values[theme])};`);
  }

  const interactiveDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveInteractive)) {
    interactiveDecls.push(`--interactive-${name}: ${toVar(values[theme])};`);
  }

  const skeletonDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveSkeleton)) {
    skeletonDecls.push(`--skeleton-${name}: ${toVar(values[theme])};`);
  }

  // Shadows use raw values (not var() references) so they override per-theme correctly
  const shadowSource = theme === "dark" ? primitiveShadowsDark : primitiveShadows;
  const shadowDecls: string[] = [];
  for (const [name, value] of Object.entries(shadowSource)) {
    shadowDecls.push(`--shadow-${name}: ${value};`);
  }

  const chartDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveChart)) {
    chartDecls.push(`--chart-${name}: ${toVar(values[theme])};`);
  }

  const sidebarDecls: string[] = [];
  for (const [name, values] of Object.entries(adaptiveSidebar)) {
    sidebarDecls.push(`--sidebar-${name}: ${toVar(values[theme])};`);
  }

  return { textDecls, surfaceDecls, borderDecls, interactiveDecls, skeletonDecls, shadowDecls, chartDecls, sidebarDecls };
}

function generateThemeCSS(theme: "light" | "dark"): string {
  const themeLabel = theme === "light" ? "Light Theme" : "Dark Theme";
  const lines: string[] = [];
  const { textDecls, surfaceDecls, borderDecls, interactiveDecls, skeletonDecls, shadowDecls, chartDecls, sidebarDecls } = buildAdaptiveDecls(theme);

  if (theme === "light") {
    // Light theme: applied to :root (default)
    lines.push(sectionComment("Adaptive: Text (light)"));
    lines.push(block(":root", textDecls));

    lines.push(sectionComment("Adaptive: Surface (light)"));
    lines.push(block(":root", surfaceDecls));

    lines.push(sectionComment("Adaptive: Border (light)"));
    lines.push(block(":root", borderDecls));

    lines.push(sectionComment("Adaptive: Interactive (light)"));
    lines.push(block(":root", interactiveDecls));

    lines.push(sectionComment("Adaptive: Skeleton (light)"));
    lines.push(block(":root", skeletonDecls));

    lines.push(sectionComment("Adaptive: Shadows (light)"));
    lines.push(block(":root", shadowDecls));

    lines.push(sectionComment("Adaptive: Chart (light)"));
    lines.push(block(":root", chartDecls));

    lines.push(sectionComment("Adaptive: Sidebar (light)"));
    lines.push(block(":root", sidebarDecls));
  } else {
    // Dark theme: applied to manual selectors
    const darkSelectors = [
      ".dark",
      ".theme-dark",
      '[data-theme="dark"]',
    ];
    const darkSelector = darkSelectors.join(",\n");

    lines.push(sectionComment("Adaptive: Text (dark) — manual toggle"));
    lines.push(block(darkSelector, textDecls));

    lines.push(sectionComment("Adaptive: Surface (dark) — manual toggle"));
    lines.push(block(darkSelector, surfaceDecls));

    lines.push(sectionComment("Adaptive: Border (dark) — manual toggle"));
    lines.push(block(darkSelector, borderDecls));

    lines.push(sectionComment("Adaptive: Interactive (dark) — manual toggle"));
    lines.push(block(darkSelector, interactiveDecls));

    lines.push(sectionComment("Adaptive: Skeleton (dark) — manual toggle"));
    lines.push(block(darkSelector, skeletonDecls));

    lines.push(sectionComment("Adaptive: Shadows (dark) — manual toggle"));
    lines.push(block(darkSelector, shadowDecls));

    lines.push(sectionComment("Adaptive: Chart (dark) — manual toggle"));
    lines.push(block(darkSelector, chartDecls));

    lines.push(sectionComment("Adaptive: Sidebar (dark) — manual toggle"));
    lines.push(block(darkSelector, sidebarDecls));

    // prefers-color-scheme: dark — auto detection
    const mediaRoot = ":root:not(.light):not(.theme-light):not([data-theme=\"light\"])";

    lines.push(sectionComment("Adaptive: Text (dark) — prefers-color-scheme"));
    lines.push(`@media (prefers-color-scheme: dark) {\n${block(mediaRoot, textDecls)}}`);
    lines.push("");

    lines.push(sectionComment("Adaptive: Surface (dark) — prefers-color-scheme"));
    lines.push(`@media (prefers-color-scheme: dark) {\n${block(mediaRoot, surfaceDecls)}}`);
    lines.push("");

    lines.push(sectionComment("Adaptive: Border (dark) — prefers-color-scheme"));
    lines.push(`@media (prefers-color-scheme: dark) {\n${block(mediaRoot, borderDecls)}}`);
    lines.push("");

    lines.push(sectionComment("Adaptive: Interactive (dark) — prefers-color-scheme"));
    lines.push(`@media (prefers-color-scheme: dark) {\n${block(mediaRoot, interactiveDecls)}}`);
    lines.push("");

    lines.push(sectionComment("Adaptive: Skeleton (dark) — prefers-color-scheme"));
    lines.push(`@media (prefers-color-scheme: dark) {\n${block(mediaRoot, skeletonDecls)}}`);
    lines.push("");

    lines.push(sectionComment("Adaptive: Shadows (dark) — prefers-color-scheme"));
    lines.push(`@media (prefers-color-scheme: dark) {\n${block(mediaRoot, shadowDecls)}}`);
    lines.push("");

    lines.push(sectionComment("Adaptive: Chart (dark) — prefers-color-scheme"));
    lines.push(`@media (prefers-color-scheme: dark) {\n${block(mediaRoot, chartDecls)}}`);
    lines.push("");

    lines.push(sectionComment("Adaptive: Sidebar (dark) — prefers-color-scheme"));
    lines.push(`@media (prefers-color-scheme: dark) {\n${block(mediaRoot, sidebarDecls)}}`);
    lines.push("");
  }

  return header(`Visor Design Tokens — ${themeLabel}`) + lines.join("\n");
}

// ============================================================
// Full bundle (tokens.css)
// ============================================================

function generateTokensCSS(): string {
  const lines: string[] = [
    header("Visor Design Tokens — Full Bundle"),
    "/* Import order: primitives → semantic → adaptive */",
    "",
    "/* ============================================",
    "   Tier 1: Primitives",
    "   ============================================ */",
  ];

  // Primitives inlined
  const primitivesContent = generatePrimitivesCSS();
  // Strip the header from the primitives content (first 6 lines are header)
  const primitivesBody = primitivesContent
    .split("\n")
    .slice(6)
    .join("\n");
  lines.push(primitivesBody);

  lines.push(
    "/* ============================================",
    "   Tier 2: Semantic",
    "   ============================================ */"
  );
  const semanticContent = generateSemanticCSS();
  const semanticBody = semanticContent.split("\n").slice(6).join("\n");
  lines.push(semanticBody);

  lines.push(
    "/* ============================================",
    "   Tier 3: Adaptive — Light Theme (:root)",
    "   ============================================ */"
  );
  const lightContent = generateThemeCSS("light");
  const lightBody = lightContent.split("\n").slice(6).join("\n");
  lines.push(lightBody);

  lines.push(
    "/* ============================================",
    "   Tier 3: Adaptive — Dark Theme (.dark, .theme-dark, [data-theme=\"dark\"])",
    "   and @media (prefers-color-scheme: dark)",
    "   ============================================ */"
  );
  const darkContent = generateThemeCSS("dark");
  const darkBody = darkContent.split("\n").slice(6).join("\n");
  lines.push(darkBody);

  lines.push(
    "/* ============================================",
    "   Global: Motion Safety",
    "   ============================================ */"
  );
  lines.push(
    "@media (prefers-reduced-motion: reduce) {",
    "  *, *::before, *::after {",
    "    animation-duration: 0.01ms !important;",
    "    animation-iteration-count: 1 !important;",
    "    transition-duration: 0.01ms !important;",
    "  }",
    "}",
    ""
  );

  return lines.join("\n");
}

// ============================================================
// Index CSS (entry point)
// ============================================================

function generateIndexCSS(): string {
  return [
    header("Visor Design Tokens — Index"),
    "/* Full design token bundle */",
    "@import './tokens.css';",
    "",
  ].join("\n");
}

// ============================================================
// Stock theme CSS generation
// ============================================================

function generateStockThemes(): void {
  for (const slug of STOCK_THEMES) {
    const yamlPath = join(STOCK_THEMES_DIR, `${slug}.visor.yaml`);
    if (!existsSync(yamlPath)) {
      throw new Error(`Stock theme YAML not found: ${yamlPath}`);
    }
    const yaml = readFileSync(yamlPath, "utf-8");
    const data = generateThemeData(yaml);
    const css = docsAdapter({ primitives: data.primitives, tokens: data.tokens, config: data.config });
    writeFileSync(join(THEMES_DIR, `${slug}.css`), css, "utf-8");
    console.log(`✓ dist/themes/${slug}.css`);
  }
}

// ============================================================
// Main
// ============================================================

function main(): void {
  console.log("Generating Visor design tokens...\n");

  ensureDirs();

  // Generate primitives.css
  const primitivesCSS = generatePrimitivesCSS();
  writeFileSync(join(DIST_DIR, "primitives.css"), primitivesCSS, "utf-8");
  console.log("✓ dist/primitives.css");

  // Generate semantic.css
  const semanticCSS = generateSemanticCSS();
  writeFileSync(join(DIST_DIR, "semantic.css"), semanticCSS, "utf-8");
  console.log("✓ dist/semantic.css");

  // Generate light theme
  const lightCSS = generateThemeCSS("light");
  writeFileSync(join(THEMES_DIR, "light.css"), lightCSS, "utf-8");
  console.log("✓ dist/themes/light.css");

  // Generate dark theme
  const darkCSS = generateThemeCSS("dark");
  writeFileSync(join(THEMES_DIR, "dark.css"), darkCSS, "utf-8");
  console.log("✓ dist/themes/dark.css");

  // Generate full bundle
  const tokensCSS = generateTokensCSS();
  writeFileSync(join(DIST_DIR, "tokens.css"), tokensCSS, "utf-8");
  console.log("✓ dist/tokens.css");

  // Generate index.css entry point
  const indexCSS = generateIndexCSS();
  writeFileSync(join(DIST_DIR, "index.css"), indexCSS, "utf-8");
  console.log("✓ dist/index.css");

  // Generate stock themes
  generateStockThemes();

  console.log("\nToken counts:");
  console.log(
    `  Primitive colors: ${Object.keys(primitiveColors).length}`
  );
  console.log(`  Spacing steps: ${Object.keys(primitiveSpacing).length}`);
  console.log(`  Radius steps: ${Object.keys(primitiveRadius).length}`);
  console.log(`  Shadow steps: ${Object.keys(primitiveShadows).length}`);
  console.log(`  Motion durations: ${Object.keys(primitiveMotionDurations).length}`);
  console.log(`  Motion easings: ${Object.keys(primitiveMotionEasings).length}`);
  console.log(
    `  Semantic text: ${Object.keys(semanticText).length}`
  );
  console.log(
    `  Semantic surface: ${Object.keys(semanticSurface).length}`
  );
  console.log(
    `  Semantic border: ${Object.keys(semanticBorder).length}`
  );
  console.log(
    `  Semantic motion duration: ${Object.keys(semanticMotionDuration).length}`
  );
  console.log(
    `  Semantic motion easing: ${Object.keys(semanticMotionEasing).length}`
  );
  console.log(
    `  Adaptive text: ${Object.keys(adaptiveText).length} (light + dark)`
  );
  console.log(
    `  Adaptive surface: ${Object.keys(adaptiveSurface).length} (light + dark)`
  );
  console.log(
    `  Adaptive border: ${Object.keys(adaptiveBorder).length} (light + dark)`
  );
  console.log(
    `  Adaptive interactive: ${Object.keys(adaptiveInteractive).length} (light + dark)`
  );
  console.log(
    `  Semantic chart: ${Object.keys(semanticChart).length}`
  );
  console.log(
    `  Semantic sidebar: ${Object.keys(semanticSidebar).length}`
  );
  console.log(
    `  Adaptive chart: ${Object.keys(adaptiveChart).length} (light + dark)`
  );
  console.log(
    `  Adaptive sidebar: ${Object.keys(adaptiveSidebar).length} (light + dark)`
  );

  console.log("\n✓ Token generation complete");
}

main();
