// This file is auto-generated by `visor theme sync`. Do not edit manually.

export interface ThemeEntry {
  value: string;
  label: string;
  /** Filename (without .visor.yaml extension) if a YAML config exists in /public/themes/ */
  yamlFile?: string;
}

export interface ThemeGroup {
  label: string;
  themes: ThemeEntry[];
}

export const THEME_GROUPS: ThemeGroup[] = [
  {
    label: "Visor",
    themes: [
    { value: "blackout", label: "Blackout", yamlFile: "blackout" },
    { value: "modern-minimal", label: "Modern Minimal", yamlFile: "modern-minimal" },
    { value: "neutral", label: "Neutral", yamlFile: "neutral" },
    { value: "space", label: "Space", yamlFile: "space" },
    ],
  },
  {
    label: "Custom",
    themes: [
    { value: "blacklight", label: "Blacklight", yamlFile: "blacklight" },
    { value: "entr", label: "Entr", yamlFile: "entr" },
    { value: "kaiah", label: "Kaiah", yamlFile: "kaiah" },
    { value: "reference-app", label: "Reference App", yamlFile: "reference-app" },
    { value: "solespark", label: "Solespark", yamlFile: "solespark" },
    { value: "veronica", label: "Veronica", yamlFile: "veronica" },
    ],
  },
];

export const ALL_THEMES = THEME_GROUPS.flatMap((g) => g.themes.map((t) => t.value));
