/**
 * Flutter adapter — emit visor_text_styles.dart.
 *
 * Emits `VisorTextStyles.instance` as `VisorTextStylesData.defaults.copyWith(...)`
 * with per-slot `TextStyle(...)` overrides from `config.typography.slots`.
 * Unspecified slots inherit from `VisorTextStylesData.defaults` (Material 3
 * 2024 scale, shipped in `visor_core`).
 *
 * The generated styles do not bake font family in; font family is applied
 * globally via `ThemeData.fontFamily` and `TextTheme.apply()` inside
 * `VisorTheme.build()`.
 */

import type { AdapterInput } from "../adapters/types.js";
import type { MaterialTextSlot, TextSlotOverride } from "../types.js";
import { MATERIAL_TEXT_SLOTS } from "../types.js";

const DART_HEADER = `// GENERATED BY visor — DO NOT EDIT.
// Regenerate with \`visor theme apply --adapter flutter\`.

import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';
`;

/**
 * Material 3 2024 type-scale defaults — mirror of
 * `VisorTextStylesData.defaults` in `packages/visor-flutter/`. Kept here
 * so the emitter can compute merged TextStyle values for partial
 * overrides without needing to run Dart.
 */
const MATERIAL_3_DEFAULTS: Record<
  MaterialTextSlot,
  { size: number; weight: number; letterSpacing?: number }
> = {
  displayLarge: { size: 57, weight: 400, letterSpacing: -0.25 },
  displayMedium: { size: 45, weight: 400 },
  displaySmall: { size: 36, weight: 400 },
  headlineLarge: { size: 32, weight: 400 },
  headlineMedium: { size: 28, weight: 400 },
  headlineSmall: { size: 24, weight: 400 },
  titleLarge: { size: 22, weight: 400 },
  titleMedium: { size: 16, weight: 500, letterSpacing: 0.15 },
  titleSmall: { size: 14, weight: 500, letterSpacing: 0.1 },
  bodyLarge: { size: 16, weight: 400, letterSpacing: 0.5 },
  bodyMedium: { size: 14, weight: 400, letterSpacing: 0.25 },
  bodySmall: { size: 12, weight: 400, letterSpacing: 0.4 },
  labelLarge: { size: 14, weight: 500, letterSpacing: 0.1 },
  labelMedium: { size: 12, weight: 500, letterSpacing: 0.5 },
  labelSmall: { size: 11, weight: 500, letterSpacing: 0.5 },
  labelXSmall: { size: 10, weight: 500, letterSpacing: 0.5 },
};

export function emitTypographyDart(input: AdapterInput): string {
  const slots = input.config.typography.slots;
  const overriddenSlots = MATERIAL_TEXT_SLOTS.filter((name) => slots[name]);

  const lines: string[] = [];
  lines.push(DART_HEADER);
  lines.push(
    "/// Generated typography tokens — Material 3 type-scale + `labelXSmall`.",
  );
  lines.push("///");
  lines.push(
    "/// Font family is not baked in here; `VisorTheme.build()` applies it",
  );
  lines.push(
    "/// globally via `TextTheme.apply(fontFamily: ...)`. Override per-slot",
  );
  lines.push("/// values in `.visor.yaml` under `typography.slots`.");
  lines.push("sealed class VisorTextStyles {");

  if (overriddenSlots.length === 0) {
    lines.push("  static final VisorTextStylesData instance =");
    lines.push("      VisorTextStylesData.defaults;");
  } else {
    lines.push("  static final VisorTextStylesData instance =");
    lines.push(
      "      VisorTextStylesData.defaults.copyWith(",
    );
    for (const name of overriddenSlots) {
      const override = slots[name]!;
      lines.push(...emitSlot(name, override).map((l) => `        ${l}`));
    }
    lines.push("      );");
  }

  lines.push("}");
  return lines.join("\n") + "\n";
}

/** Emit a single slot override as `<name>: const TextStyle(...)` lines. */
function emitSlot(
  name: MaterialTextSlot,
  override: TextSlotOverride,
): string[] {
  const d = MATERIAL_3_DEFAULTS[name];
  const size = override.size ?? d.size;
  const weight = override.weight ?? d.weight;
  const letterSpacing =
    override["letter-spacing"] !== undefined
      ? override["letter-spacing"]
      : d.letterSpacing;

  const styleLines: string[] = [
    `${name}: const TextStyle(`,
    `  fontSize: ${size},`,
    `  fontWeight: FontWeight.w${weight},`,
  ];
  if (letterSpacing !== undefined) {
    styleLines.push(`  letterSpacing: ${letterSpacing},`);
  }
  styleLines.push(`),`);
  return styleLines;
}
