/**
 * Flutter adapter — emit visor_motion.dart.
 *
 * Translates CSS `<time>` and `<easing-function>` values into Dart
 * `Duration` and `Curve` literals. Supports:
 *
 * - Durations: `"200ms"`, `"0.2s"` → `Duration(milliseconds: 200)`.
 * - Easing keywords: `linear` / `ease` / `ease-in` / `ease-out` /
 *   `ease-in-out` → `Curves.*`.
 * - `cubic-bezier(a, b, c, d)` → `Cubic(a, b, c, d)`.
 * - Unknown easing falls back to `Curves.easeInOut` with a warning.
 */

import type { AdapterInput } from "../adapters/types.js";

const DART_HEADER = `// GENERATED BY visor — DO NOT EDIT.
// Regenerate with \`visor theme apply --adapter flutter\`.

import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';
`;

export function emitMotionDart(input: AdapterInput): string {
  const m = input.config.motion;
  const fast = parseDurationToDart(m["duration-fast"]);
  const normal = parseDurationToDart(m["duration-normal"]);
  const slow = parseDurationToDart(m["duration-slow"]);
  const easing = parseEasingToDart(m.easing);

  const lines: string[] = [];
  lines.push(DART_HEADER);
  lines.push("/// Generated motion tokens — durations + default easing curve.");
  lines.push("sealed class VisorMotion {");
  lines.push("  static final VisorMotionData instance = VisorMotionData(");
  lines.push(`    durationFast: ${fast},`);
  lines.push(`    durationNormal: ${normal},`);
  lines.push(`    durationSlow: ${slow},`);
  lines.push(`    easing: ${easing},`);
  lines.push("  );");
  lines.push("}");
  return lines.join("\n") + "\n";
}

/** Parse a CSS `<time>` string to a Dart `Duration(milliseconds: N)` literal. */
export function parseDurationToDart(css: string): string {
  const trimmed = css.trim().toLowerCase();
  let ms: number;
  if (trimmed.endsWith("ms")) {
    ms = Number(trimmed.slice(0, -2));
  } else if (trimmed.endsWith("s")) {
    ms = Number(trimmed.slice(0, -1)) * 1000;
  } else {
    throw new Error(`Invalid duration "${css}": expected "<N>ms" or "<N>s"`);
  }
  if (!Number.isFinite(ms) || ms < 0) {
    throw new Error(`Invalid duration "${css}": must be a non-negative number`);
  }
  return `Duration(milliseconds: ${Math.round(ms)})`;
}

const KEYWORD_TO_CURVE: Record<string, string> = {
  linear: "Curves.linear",
  ease: "Curves.ease",
  "ease-in": "Curves.easeIn",
  "ease-out": "Curves.easeOut",
  "ease-in-out": "Curves.easeInOut",
};

/** Parse a CSS `<easing-function>` string to a Dart `Curve` expression. */
export function parseEasingToDart(css: string): string {
  const trimmed = css.trim().toLowerCase();

  if (trimmed in KEYWORD_TO_CURVE) {
    return KEYWORD_TO_CURVE[trimmed];
  }

  const cbMatch = trimmed.match(
    /^cubic-bezier\(\s*(-?\d*\.?\d+)\s*,\s*(-?\d*\.?\d+)\s*,\s*(-?\d*\.?\d+)\s*,\s*(-?\d*\.?\d+)\s*\)$/,
  );
  if (cbMatch) {
    const [, a, b, c, d] = cbMatch;
    return `Cubic(${a}, ${b}, ${c}, ${d})`;
  }

  // eslint-disable-next-line no-console
  console.warn(
    `visor: unsupported easing "${css}" — falling back to Curves.easeInOut.`,
  );
  return "Curves.easeInOut";
}
