/**
 * Flutter adapter — emit visor_spacing.dart.
 *
 * Generates `VisorSpacing.instance` from `config.spacing.base` (default 4).
 * Scale: xs=1×, sm=2×, md=3×, lg=4×, xl=6×, xxl=8×, xxxl=12×.
 */

import type { AdapterInput } from "../adapters/types.js";

const DART_HEADER = `// GENERATED BY visor — DO NOT EDIT.
// Regenerate with \`visor theme apply --adapter flutter\`.

import 'package:visor_core/visor_core.dart';
`;

export function emitSpacingDart(input: AdapterInput): string {
  const base = input.config.spacing.base;
  const lines: string[] = [];
  lines.push(DART_HEADER);
  lines.push("/// Generated spacing tokens.");
  lines.push("///");
  lines.push(`/// Base unit: ${base}px. Scale derived by multiplication:`);
  lines.push("/// xs=1×, sm=2×, md=3×, lg=4×, xl=6×, xxl=8×, xxxl=12×.");
  lines.push("sealed class VisorSpacing {");
  lines.push("  static final VisorSpacingData instance = VisorSpacingData(");
  lines.push(`    xs: ${fmt(base * 1)},`);
  lines.push(`    sm: ${fmt(base * 2)},`);
  lines.push(`    md: ${fmt(base * 3)},`);
  lines.push(`    lg: ${fmt(base * 4)},`);
  lines.push(`    xl: ${fmt(base * 6)},`);
  lines.push(`    xxl: ${fmt(base * 8)},`);
  lines.push(`    xxxl: ${fmt(base * 12)},`);
  lines.push("  );");
  lines.push("}");
  return lines.join("\n") + "\n";
}

/** Format a number for Dart, preserving integer literal when whole. */
function fmt(n: number): string {
  return Number.isInteger(n) ? `${n}` : `${n}`;
}
