/**
 * Flutter adapter — emit visor_colors.dart.
 *
 * Generates a Dart file exposing:
 * - Primitive color constants for every generated shade scale
 *   (`VisorColors.primary50..950`, `VisorColors.neutral50..950`, etc.)
 * - Pre-computed opacity variants on primary/accent (compile-time opacity
 *   keeps generated Dart free of runtime `withValues(alpha:)` calls)
 * - `VisorColors.light` and `VisorColors.dark` static getters returning
 *   `VisorColorsData` [ThemeExtension] instances constructed from the
 *   semantic token set.
 */

import type {
  AdapterInput,
} from "../adapters/types.js";
import type {
  ColorRole,
  SemanticTokens,
  ShadeStep,
} from "../types.js";
import { FULL_SHADE_STEPS, SELECTIVE_SHADE_STEPS } from "../shades.js";
import { cssColorToDart, cssColorToOpaqueDart, opacityVariants } from "./color-to-dart.js";

const FULL_SCALE_ROLES: ColorRole[] = ["primary", "accent", "neutral"];
const SELECTIVE_SCALE_ROLES: ColorRole[] = [
  "success",
  "warning",
  "error",
  "info",
];

const DART_HEADER = `// GENERATED BY visor — DO NOT EDIT.
// Regenerate with \`visor theme apply --adapter flutter\`.
// Source: .visor.yaml → Visor theme engine → flutter adapter.

import 'dart:ui';

import 'package:visor_core/visor_core.dart';
`;

/**
 * Emit the full ui_colors.dart contents for the given theme data.
 */
export function emitColorsDart(input: AdapterInput): string {
  const { primitives, tokens } = input;
  const lines: string[] = [];
  lines.push(DART_HEADER);
  lines.push(`/// Generated color tokens for the ${input.config.name} theme.`);
  lines.push("///");
  lines.push("/// Do not edit this file manually — regenerate from .visor.yaml.");
  lines.push("sealed class VisorColors {");

  // White / black anchors
  lines.push("  // ========================================================================");
  lines.push("  // Anchors");
  lines.push("  // ========================================================================");
  lines.push("  static const Color white = Color(0xFFFFFFFF);");
  lines.push("  static const Color black = Color(0xFF000000);");
  lines.push("");

  // Primitive scales
  for (const role of [...FULL_SCALE_ROLES, ...SELECTIVE_SCALE_ROLES]) {
    lines.push(
      `  // ========================================================================`,
    );
    lines.push(`  // ${capitalize(role)} scale`);
    lines.push(
      `  // ========================================================================`,
    );
    const steps: readonly ShadeStep[] = FULL_SCALE_ROLES.includes(role)
      ? FULL_SHADE_STEPS
      : SELECTIVE_SHADE_STEPS;
    const scale = primitives[role] as Record<number, string>;
    for (const step of steps) {
      const value = scale[step];
      lines.push(
        `  static const Color ${role}${step} = ${cssColorToOpaqueDart(value)};`,
      );
    }
    lines.push("");
  }

  // Opacity variants for primary/accent anchors (500/600) + white/black
  lines.push("  // ========================================================================");
  lines.push("  // Opacity variants (pre-computed at codegen)");
  lines.push("  // ========================================================================");
  const opacitySources: Array<{ name: string; css: string }> = [
    { name: "primary500", css: primitives.primary[500] },
    { name: "primary600", css: primitives.primary[600] },
    { name: "accent500", css: primitives.accent[500] },
    { name: "white", css: "#FFFFFF" },
    { name: "black", css: "#000000" },
  ];
  for (const source of opacitySources) {
    const variants = opacityVariants(source.css);
    for (const [suffix, dartColor] of Object.entries(variants)) {
      lines.push(`  static const Color ${source.name}_${suffix} = ${dartColor};`);
    }
  }
  lines.push("");

  // Semantic light / dark instances
  lines.push("  // ========================================================================");
  lines.push("  // Semantic — Light");
  lines.push("  // ========================================================================");
  lines.push(`  static final VisorColorsData light = ${semanticInstance(tokens, "light")};`);
  lines.push("");
  lines.push("  // ========================================================================");
  lines.push("  // Semantic — Dark");
  lines.push("  // ========================================================================");
  lines.push(`  static final VisorColorsData dark = ${semanticInstance(tokens, "dark")};`);
  lines.push("}");
  return lines.join("\n") + "\n";
}

/** Build a `VisorColorsData(...)` expression for light or dark mode. */
function semanticInstance(
  tokens: SemanticTokens,
  mode: "light" | "dark",
): string {
  const parts: string[] = ["VisorColorsData("];
  const emit = (
    field: string,
    category: keyof SemanticTokens,
    tokenName: string,
  ): void => {
    const token = tokens[category][tokenName];
    if (!token) {
      throw new Error(
        `Missing semantic token: ${String(category)}.${tokenName}`,
      );
    }
    parts.push(`    ${field}: ${cssColorToDart(token[mode])},`);
  };

  // text
  emit("textPrimary", "text", "primary");
  emit("textSecondary", "text", "secondary");
  emit("textTertiary", "text", "tertiary");
  emit("textDisabled", "text", "disabled");
  emit("textInverse", "text", "inverse");
  emit("textInverseSecondary", "text", "inverse-secondary");
  emit("textLink", "text", "link");
  emit("textLinkHover", "text", "link-hover");
  emit("textSuccess", "text", "success");
  emit("textWarning", "text", "warning");
  emit("textError", "text", "error");
  emit("textInfo", "text", "info");
  // surface
  emit("surfacePage", "surface", "page");
  emit("surfaceCard", "surface", "card");
  emit("surfaceSubtle", "surface", "subtle");
  emit("surfaceMuted", "surface", "muted");
  emit("surfaceOverlay", "surface", "overlay");
  emit("surfaceInteractiveDefault", "surface", "interactive-default");
  emit("surfaceInteractiveHover", "surface", "interactive-hover");
  emit("surfaceInteractiveActive", "surface", "interactive-active");
  emit("surfaceInteractiveDisabled", "surface", "interactive-disabled");
  emit("surfaceAccentSubtle", "surface", "accent-subtle");
  emit("surfaceAccentDefault", "surface", "accent-default");
  emit("surfaceAccentStrong", "surface", "accent-strong");
  emit("surfaceSuccessSubtle", "surface", "success-subtle");
  emit("surfaceSuccessDefault", "surface", "success-default");
  emit("surfaceWarningSubtle", "surface", "warning-subtle");
  emit("surfaceWarningDefault", "surface", "warning-default");
  emit("surfaceErrorSubtle", "surface", "error-subtle");
  emit("surfaceErrorDefault", "surface", "error-default");
  emit("surfaceInfoSubtle", "surface", "info-subtle");
  emit("surfaceInfoDefault", "surface", "info-default");
  // border
  emit("borderDefault", "border", "default");
  emit("borderMuted", "border", "muted");
  emit("borderStrong", "border", "strong");
  emit("borderFocus", "border", "focus");
  emit("borderDisabled", "border", "disabled");
  emit("borderSuccess", "border", "success");
  emit("borderWarning", "border", "warning");
  emit("borderError", "border", "error");
  emit("borderInfo", "border", "info");
  // interactive
  emit("interactivePrimaryBg", "interactive", "primary-bg");
  emit("interactivePrimaryBgHover", "interactive", "primary-bg-hover");
  emit("interactivePrimaryBgActive", "interactive", "primary-bg-active");
  emit("interactivePrimaryText", "interactive", "primary-text");
  emit("interactiveSecondaryBg", "interactive", "secondary-bg");
  emit("interactiveSecondaryBgHover", "interactive", "secondary-bg-hover");
  emit("interactiveSecondaryBgActive", "interactive", "secondary-bg-active");
  emit("interactiveSecondaryText", "interactive", "secondary-text");
  emit("interactiveSecondaryBorder", "interactive", "secondary-border");
  emit("interactiveDestructiveBg", "interactive", "destructive-bg");
  emit("interactiveDestructiveBgHover", "interactive", "destructive-bg-hover");
  emit("interactiveDestructiveText", "interactive", "destructive-text");
  emit("interactiveGhostBg", "interactive", "ghost-bg");
  emit("interactiveGhostBgHover", "interactive", "ghost-bg-hover");

  parts.push("  )");
  // silence: intentionally keep dart-to-css converter unused reference
  void cssColorToDart;
  return parts.join("\n");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
