/**
 * Flutter adapter — emit visor_opacity.dart.
 *
 * Generates `VisorOpacity.instance` with the canonical Visor opacity scale.
 * Opacity is fixed across themes (Visor decision D3 on VI-245) — no
 * `.visor.yaml` knob, no per-theme override. Every theme ships the same
 * 8-slot scale; the per-theme file exists only so the layout matches the
 * other token categories.
 */

const DART_HEADER = `// GENERATED BY visor — DO NOT EDIT.
// Regenerate with \`visor theme apply --adapter flutter\`.

import 'package:visor_core/visor_core.dart';
`;

export function emitOpacityDart(): string {
  const lines: string[] = [];
  lines.push(DART_HEADER);
  lines.push("/// Generated opacity tokens (raw alpha values in [0, 1]).");
  lines.push("///");
  lines.push("/// Fixed across themes — opacity is a math primitive, not a brand decision.");
  lines.push("sealed class VisorOpacity {");
  lines.push("  static final VisorOpacityData instance = VisorOpacityData(");
  lines.push("    alpha5: 0.05,");
  lines.push("    alpha10: 0.1,");
  lines.push("    alpha12: 0.12,");
  lines.push("    alpha20: 0.2,");
  lines.push("    alpha40: 0.4,");
  lines.push("    alpha50: 0.5,");
  lines.push("    alpha60: 0.6,");
  lines.push("    alpha80: 0.8,");
  lines.push("  );");
  lines.push("}");
  return lines.join("\n") + "\n";
}
