/**
 * Flutter adapter — emit visor_stroke_widths.dart.
 *
 * Generates `VisorStrokeWidths.instance` from
 * `config.strokeWidths.{thin,regular,medium,thick}`. Identity mapping —
 * the resolver supplies sensible defaults for anything the author omits
 * from `.visor.yaml`.
 */

import type { AdapterInput } from "../adapters/types.js";

const DART_HEADER = `// GENERATED BY visor — DO NOT EDIT.
// Regenerate with \`visor theme apply --adapter flutter\`.

import 'package:visor_core/visor_core.dart';
`;

export function emitStrokesDart(input: AdapterInput): string {
  const s = input.config.strokeWidths;
  const lines: string[] = [];
  lines.push(DART_HEADER);
  lines.push("/// Generated stroke-width tokens (raw pixel values).");
  lines.push("sealed class VisorStrokeWidths {");
  lines.push("  static final VisorStrokeWidthsData instance = VisorStrokeWidthsData(");
  lines.push(`    thin: ${s.thin},`);
  lines.push(`    regular: ${s.regular},`);
  lines.push(`    medium: ${s.medium},`);
  lines.push(`    thick: ${s.thick},`);
  lines.push("  );");
  lines.push("}");
  return lines.join("\n") + "\n";
}
