/**
 * Flutter adapter — emit visor_shadows.dart.
 *
 * Parses CSS `box-shadow` strings into Dart `BoxShadow` lists. Grammar:
 *
 *   <offset-x> <offset-y> <blur-radius>? <spread-radius>? <color>
 *
 * Multiple shadows may be comma-separated (commas inside color
 * functions are respected). The `inset` keyword is not representable on
 * Flutter's [BoxShadow] and is rejected.
 */

import type { AdapterInput } from "../adapters/types.js";
import { cssColorToDart } from "./color-to-dart.js";

const DART_HEADER = `// GENERATED BY visor — DO NOT EDIT.
// Regenerate with \`visor theme apply --adapter flutter\`.

import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';
`;

const SHADOW_KEYS = ["xs", "sm", "md", "lg", "xl"] as const;

export function emitShadowsDart(input: AdapterInput): string {
  const s = input.config.shadows;

  const lines: string[] = [];
  lines.push(DART_HEADER);
  lines.push("/// Generated elevation/shadow tokens.");
  lines.push("///");
  lines.push("/// Each value is a `List<BoxShadow>` — CSS box-shadow strings");
  lines.push("/// supporting multi-layer shadows compile to the same list here.");
  lines.push("sealed class VisorShadows {");
  lines.push("  static final VisorShadowsData instance = VisorShadowsData(");
  for (const key of SHADOW_KEYS) {
    const dart = parseShadowListToDart(s[key]);
    lines.push(`    ${key}: ${dart},`);
  }
  lines.push("  );");
  lines.push("}");
  return lines.join("\n") + "\n";
}

/**
 * Parse a CSS box-shadow string (possibly multi-layer) into a Dart
 * `const <BoxShadow>[...]` list literal.
 */
export function parseShadowListToDart(css: string): string {
  const shadows = splitTopLevelCommas(css);
  if (shadows.length === 0) return "const <BoxShadow>[]";
  const parts = shadows.map(parseSingleShadow);
  return `const <BoxShadow>[\n${parts.map((p) => "      " + p).join(",\n")},\n    ]`;
}

function parseSingleShadow(raw: string): string {
  const css = raw.trim();
  if (/\binset\b/i.test(css)) {
    throw new Error(
      `box-shadow 'inset' is not representable on Flutter BoxShadow: "${raw}"`,
    );
  }

  // Color is always at the end — find it by matching supported CSS color
  // forms. Hex, rgb/rgba, hsl/hsla, oklch, oklab.
  const colorRe = /(#[0-9a-f]{3,8}|rgba?\([^)]*\)|hsla?\([^)]*\)|oklch\([^)]*\)|oklab\([^)]*\))\s*$/i;
  const colorMatch = css.match(colorRe);
  if (!colorMatch || colorMatch.index === undefined) {
    throw new Error(`Invalid box-shadow: missing trailing color in "${raw}"`);
  }
  const color = colorMatch[1];
  const lengthsPart = css.slice(0, colorMatch.index).trim();
  const lengths = lengthsPart.split(/\s+/).filter(Boolean);
  if (lengths.length < 2) {
    throw new Error(
      `Invalid box-shadow: need at least x and y offsets in "${raw}"`,
    );
  }
  if (lengths.length > 4) {
    throw new Error(
      `Invalid box-shadow: too many length values in "${raw}" (max 4: x y blur spread)`,
    );
  }

  const [x, y, blur = "0", spread = "0"] = lengths;
  const offsetX = parseLength(x, raw);
  const offsetY = parseLength(y, raw);
  const blurRadius = parseLength(blur, raw);
  const spreadRadius = parseLength(spread, raw);
  const colorDart = cssColorToDart(color);

  const parts: string[] = [
    `offset: Offset(${offsetX}, ${offsetY})`,
    `blurRadius: ${blurRadius}`,
  ];
  if (spreadRadius !== 0) {
    parts.push(`spreadRadius: ${spreadRadius}`);
  }
  parts.push(`color: ${colorDart}`);
  return `BoxShadow(${parts.join(", ")})`;
}

/** Parse a CSS length token (e.g. `"4px"`, `"-2"`, `"0"`) to a number. */
function parseLength(token: string, raw: string): number {
  const cleaned = token.trim().replace(/px$/i, "");
  const n = Number(cleaned);
  if (!Number.isFinite(n)) {
    throw new Error(`Invalid shadow length "${token}" in "${raw}"`);
  }
  return n;
}

/**
 * Split a string on commas that are not inside parentheses. Handles
 * nested parens so `rgba(0, 0, 0, 0.1)` is not split by the inner commas.
 */
function splitTopLevelCommas(input: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let buf = "";
  for (const c of input) {
    if (c === "(") depth++;
    else if (c === ")") depth--;
    if (c === "," && depth === 0) {
      if (buf.trim()) parts.push(buf.trim());
      buf = "";
    } else {
      buf += c;
    }
  }
  if (buf.trim()) parts.push(buf.trim());
  return parts;
}
