/**
 * Flutter adapter — emit visor_theme.dart.
 *
 * Generates the consumer-owned `sealed class VisorAppTheme` wrapper that
 * calls `VisorTheme.build()` with the emitted token instances
 * (`VisorColors.light/dark`, `VisorTextStyles.instance`,
 * `VisorSpacing.instance`, `VisorRadius.instance`, `VisorShadows.instance`,
 * `VisorMotion.instance`).
 */

export interface EmitThemeOptions {
  /** Name of the generated wrapper class. Default: `VisorAppTheme`. */
  themeClassName: string;
  /** Whether to emit the `.light` getter. */
  emitLight: boolean;
  /** Whether to emit the `.dark` getter. */
  emitDark: boolean;
  /** Paths of emitted token files this wrapper depends on (relative imports). */
  tokenImports: string[];
}

export function emitThemeDart(options: EmitThemeOptions): string {
  const { themeClassName, emitLight, emitDark, tokenImports } = options;

  const lines: string[] = [
    `// GENERATED BY visor — DO NOT EDIT.`,
    `// Regenerate with \`visor theme apply --adapter flutter\`.`,
    ``,
    `import 'package:flutter/material.dart';`,
    `import 'package:visor_core/visor_core.dart';`,
    ``,
    ...tokenImports.map((p) => `import '${p}';`),
    ``,
    `/// Assembled Material 3 [ThemeData] for this project.`,
    `///`,
    `/// Wire into [MaterialApp]:`,
    `/// \`\`\`dart`,
    `/// MaterialApp(`,
    `///   theme: ${themeClassName}.light,`,
    `///   darkTheme: ${themeClassName}.dark,`,
    `/// );`,
    `/// \`\`\``,
    `sealed class ${themeClassName} {`,
  ];

  if (emitLight) {
    lines.push(
      `  static ThemeData get light => VisorTheme.build(`,
      `        colors: VisorColors.light,`,
      `        brightness: Brightness.light,`,
      `        textStyles: VisorTextStyles.instance,`,
      `        spacing: VisorSpacing.instance,`,
      `        radius: VisorRadius.instance,`,
      `        shadows: VisorShadows.instance,`,
      `        motion: VisorMotion.instance,`,
      `      );`,
      ``,
    );
  }

  if (emitDark) {
    lines.push(
      `  static ThemeData get dark => VisorTheme.build(`,
      `        colors: VisorColors.dark,`,
      `        brightness: Brightness.dark,`,
      `        textStyles: VisorTextStyles.instance,`,
      `        spacing: VisorSpacing.instance,`,
      `        radius: VisorRadius.instance,`,
      `        shadows: VisorShadows.instance,`,
      `        motion: VisorMotion.instance,`,
      `      );`,
      ``,
    );
  }

  lines.push(`}`);
  lines.push(``);
  return lines.join("\n");
}
