/**
 * Flutter adapter — emit visor_radius.dart.
 *
 * Generates `VisorRadius.instance` from `config.radius.{sm,md,lg,xl,pill}`.
 * Identity mapping — the resolver supplies sensible defaults for anything
 * the author omits from `.visor.yaml`.
 */

import type { AdapterInput } from "../adapters/types.js";

const DART_HEADER = `// GENERATED BY visor — DO NOT EDIT.
// Regenerate with \`visor theme apply --adapter flutter\`.

import 'package:visor_core/visor_core.dart';
`;

export function emitRadiusDart(input: AdapterInput): string {
  const r = input.config.radius;
  const lines: string[] = [];
  lines.push(DART_HEADER);
  lines.push("/// Generated border-radius tokens (raw pixel values).");
  lines.push("sealed class VisorRadius {");
  lines.push("  static final VisorRadiusData instance = VisorRadiusData(");
  lines.push(`    sm: ${r.sm},`);
  lines.push(`    md: ${r.md},`);
  lines.push(`    lg: ${r.lg},`);
  lines.push(`    xl: ${r.xl},`);
  lines.push(`    pill: ${r.pill},`);
  lines.push("  );");
  lines.push("}");
  return lines.join("\n") + "\n";
}
