/**
 * Walks every registry array, reads each `.tsx` file the registry references,
 * and extracts PascalCase React component identifiers. The result is written
 * to `components/devtools/source-inspector/visor-component-names.generated.ts`
 * as a static `Set<string>` so SourceInspector can name-match owner fibers
 * regardless of bundler (Turbopack hashes away `@loworbitstudio/visor` chunk
 * paths; component names stay stable). VI-311.
 *
 * Usage:
 *   npx tsx scripts/generate-visor-component-names.ts
 *   npm run generate:component-names
 *
 * Output is committed and shipped via the SourceInspector registry entry so
 * consumers who run `npx visor add source-inspector` receive it without
 * needing to run codegen themselves.
 */

import * as fs from "node:fs"
import * as path from "node:path"
import { fileURLToPath } from "node:url"

import type { Registry, RegistryItem } from "../registry/schema"
import { ui } from "../registry/registry-ui"
import { blocks } from "../registry/registry-blocks"
import { devtools } from "../registry/registry-devtools"
import { deck } from "../registry/registry-deck"
import { visual } from "../registry/registry-visual"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, "..")
const OUTPUT_PATH = path.join(
  REPO_ROOT,
  "components/devtools/source-inspector/visor-component-names.generated.ts",
)

/**
 * Registries that ship React components. Hooks (`registry-hooks.ts`) and lib
 * helpers (`registry-lib.ts`) are excluded — they are not rendered as fiber
 * owners and would dilute the name set with non-component identifiers.
 */
const COMPONENT_REGISTRIES: Array<{ label: string; items: Registry }> = [
  { label: "ui", items: ui },
  { label: "blocks", items: blocks },
  { label: "deck", items: deck },
  { label: "visual", items: visual },
  { label: "devtools", items: devtools },
]

// PascalCase with at least one lowercase character — excludes all-caps
// constants like `THEMES` that would otherwise widen the set and shadow
// any consumer component coincidentally named the same.
const PASCAL_CASE = /^[A-Z][A-Za-z0-9]*[a-z][A-Za-z0-9]*$/

const COMPONENT_PATTERNS: RegExp[] = [
  /\bexport\s+function\s+([A-Z][A-Za-z0-9]*)\s*[<(]/g,
  /\bexport\s+const\s+([A-Z][A-Za-z0-9]*)\s*[:=]/g,
  /^function\s+([A-Z][A-Za-z0-9]*)\s*[<(]/gm,
  /^const\s+([A-Z][A-Za-z0-9]*)\s*[:=]/gm,
]

const EXPORT_BLOCK = /\bexport\s*\{([^}]+)\}/g

function extractNamesFromSource(source: string): Set<string> {
  const names = new Set<string>()

  for (const pattern of COMPONENT_PATTERNS) {
    for (const match of source.matchAll(pattern)) {
      const name = match[1]
      if (name && PASCAL_CASE.test(name)) names.add(name)
    }
  }

  for (const blockMatch of source.matchAll(EXPORT_BLOCK)) {
    const block = blockMatch[1]
    if (!block) continue
    for (const part of block.split(",")) {
      const trimmed = part.trim()
      if (!trimmed) continue
      const aliasMatch = trimmed.match(/(?:\w+)\s+as\s+([A-Za-z0-9_]+)/)
      const candidate = aliasMatch ? aliasMatch[1] : trimmed.split(/\s+/)[0]
      if (candidate && PASCAL_CASE.test(candidate)) names.add(candidate)
    }
  }

  return names
}

function collectNames(): { names: Set<string>; fileCount: number } {
  const names = new Set<string>()
  let fileCount = 0

  for (const { label, items } of COMPONENT_REGISTRIES) {
    for (const item of items satisfies RegistryItem[]) {
      for (const file of item.files) {
        if (!file.path.endsWith(".tsx")) continue
        const abs = path.join(REPO_ROOT, file.path)
        if (!fs.existsSync(abs)) {
          console.warn(
            `[generate-visor-component-names] missing file referenced by ${label}/${item.name}: ${file.path}`,
          )
          continue
        }
        const source = fs.readFileSync(abs, "utf8")
        for (const name of extractNamesFromSource(source)) names.add(name)
        fileCount++
      }
    }
  }

  return { names, fileCount }
}

function renderOutput(names: Set<string>): string {
  const sorted = Array.from(names).sort((a, b) => a.localeCompare(b))
  const entries = sorted.map((n) => `  ${JSON.stringify(n)},`).join("\n")

  return `// THIS FILE IS GENERATED BY scripts/generate-visor-component-names.ts.
// Do not edit by hand. Re-run \`npm run generate:component-names\` after
// adding, removing, or renaming a Visor component.
//
// Source of truth: registry/registry-{ui,blocks,deck,visual,devtools}.ts
// Used by: components/devtools/source-inspector/* (VI-311)

export const VISOR_COMPONENT_NAMES: ReadonlySet<string> = new Set([
${entries}
])
`
}

function main(): void {
  const { names, fileCount } = collectNames()
  if (names.size === 0) {
    console.error(
      "[generate-visor-component-names] extracted zero component names — refusing to write empty set",
    )
    process.exit(1)
  }

  const output = renderOutput(names)
  fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true })

  const previous = fs.existsSync(OUTPUT_PATH)
    ? fs.readFileSync(OUTPUT_PATH, "utf8")
    : null

  if (previous === output) {
    console.log(
      `[generate-visor-component-names] no change (${names.size} names from ${fileCount} files)`,
    )
    return
  }

  fs.writeFileSync(OUTPUT_PATH, output)
  console.log(
    `[generate-visor-component-names] wrote ${names.size} names from ${fileCount} files → ${path.relative(REPO_ROOT, OUTPUT_PATH)}`,
  )
}

main()
