import 'package:flutter/material.dart';
import 'package:visor_core/visor_core.dart';

/// Builds a minimal [VisorColorsData] suitable for widget tests. The values
/// here are not meaningful — they cover the required constructor surface so
/// `VisorTheme.build()` can produce a working theme.
VisorColorsData testColors({int textPrimaryValue = 0xFF111111}) {
  return VisorColorsData(
    textPrimary: Color(textPrimaryValue),
    textSecondary: const Color(0xFF555555),
    textTertiary: const Color(0xFF888888),
    textDisabled: const Color(0xFFCCCCCC),
    textInverse: const Color(0xFFFFFFFF),
    textInverseSecondary: const Color(0xFFE5E5E5),
    textLink: const Color(0xFF2563EB),
    textLinkHover: const Color(0xFF1D4ED8),
    textSuccess: const Color(0xFF15803D),
    textWarning: const Color(0xFFB45309),
    textError: const Color(0xFFB91C1C),
    textInfo: const Color(0xFF0369A1),
    surfacePage: const Color(0xFFFFFFFF),
    surfaceCard: const Color(0xFFFFFFFF),
    surfaceSubtle: const Color(0xFFF9FAFB),
    surfaceMuted: const Color(0xFFF3F4F6),
    surfaceOverlay: const Color(0xFF111827),
    surfaceInteractiveDefault: const Color(0xFFFFFFFF),
    surfaceInteractiveHover: const Color(0xFFF9FAFB),
    surfaceInteractiveActive: const Color(0xFFF3F4F6),
    surfaceInteractiveDisabled: const Color(0xFFF9FAFB),
    surfaceAccentSubtle: const Color(0xFFEFF6FF),
    surfaceAccentDefault: const Color(0xFF3B82F6),
    surfaceAccentStrong: const Color(0xFF2563EB),
    surfaceSuccessSubtle: const Color(0xFFF0FDF4),
    surfaceSuccessDefault: const Color(0xFF22C55E),
    surfaceWarningSubtle: const Color(0xFFFFFBEB),
    surfaceWarningDefault: const Color(0xFFF59E0B),
    surfaceErrorSubtle: const Color(0xFFFEF2F2),
    surfaceErrorDefault: const Color(0xFFEF4444),
    surfaceInfoSubtle: const Color(0xFFF0F9FF),
    surfaceInfoDefault: const Color(0xFF0EA5E9),
    borderDefault: const Color(0xFFE5E7EB),
    borderMuted: const Color(0xFFF3F4F6),
    borderStrong: const Color(0xFFD1D5DB),
    borderFocus: const Color(0xFF3B82F6),
    borderDisabled: const Color(0xFFF3F4F6),
    borderSuccess: const Color(0xFF22C55E),
    borderWarning: const Color(0xFFF59E0B),
    borderError: const Color(0xFFEF4444),
    borderInfo: const Color(0xFF0EA5E9),
    interactivePrimaryBg: const Color(0xFF2563EB),
    interactivePrimaryBgHover: const Color(0xFF1D4ED8),
    interactivePrimaryBgActive: const Color(0xFF1E40AF),
    interactivePrimaryText: const Color(0xFFFFFFFF),
    interactiveSecondaryBg: const Color(0xFFFFFFFF),
    interactiveSecondaryBgHover: const Color(0xFFF9FAFB),
    interactiveSecondaryBgActive: const Color(0xFFF3F4F6),
    interactiveSecondaryText: const Color(0xFF111827),
    interactiveSecondaryBorder: const Color(0xFFD1D5DB),
    interactiveDestructiveBg: const Color(0xFFDC2626),
    interactiveDestructiveBgHover: const Color(0xFFB91C1C),
    interactiveDestructiveText: const Color(0xFFFFFFFF),
    interactiveGhostBg: const Color(0xFFFFFFFF),
    interactiveGhostBgHover: const Color(0xFFF3F4F6),
  );
}
