/**
 * CSS Generation (Stage 3 + Output)
 *
 * Generates CSS custom property strings matching the existing
 * packages/tokens/src/generate/generate-css.ts output format.
 */

import type {
  GeneratedPrimitives,
  ResolvedThemeConfig,
  SemanticTokens,
  ShadeStep,
  ColorRole,
} from "./types.js";
import { FULL_SHADE_STEPS, SELECTIVE_SHADE_STEPS } from "./shades.js";

// ============================================================
// Helpers
// ============================================================

export function header(label: string): string {
  return [
    "/* ============================================",
    `   ${label}`,
    "   Generated by @loworbitstudio/visor-theme-engine",
    "   DO NOT EDIT — regenerate from .visor.yaml",
    "   ============================================ */",
    "",
  ].join("\n");
}

export function sectionComment(label: string): string {
  return `\n/* --- ${label} --- */`;
}

export function block(selector: string, declarations: string[]): string {
  if (declarations.length === 0) return "";
  return [selector + " {", ...declarations.map((d) => `  ${d}`), "}", ""].join(
    "\n"
  );
}

// ============================================================
// Primitives CSS
// ============================================================

/** Color roles that produce full scales vs. selective scales. */
const FULL_SCALE_ROLES: ColorRole[] = ["primary", "accent", "neutral"];
const SELECTIVE_SCALE_ROLES: ColorRole[] = [
  "success",
  "warning",
  "error",
  "info",
];

function generateColorPrimitives(primitives: GeneratedPrimitives): string {
  const decls: string[] = [];

  // White and black constants
  decls.push("--color-white: #ffffff;");
  decls.push("--color-black: #000000;");

  const allRoles: ColorRole[] = [...FULL_SCALE_ROLES, ...SELECTIVE_SCALE_ROLES];

  for (const role of allRoles) {
    const scale = primitives[role];
    const steps: ShadeStep[] = FULL_SCALE_ROLES.includes(role)
      ? FULL_SHADE_STEPS
      : SELECTIVE_SHADE_STEPS;

    for (const step of steps) {
      const value = (scale as Record<number, string>)[step];
      decls.push(`--color-${role}-${step}: ${value};`);
    }
  }

  return decls.join("\n  ");
}

function generateSpacingPrimitives(config: ResolvedThemeConfig): string[] {
  const base = config.spacing.base;
  const multipliers = [0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20, 24];

  return multipliers.map((m) => {
    const px = base * m;
    const rem = px === 0 ? "0" : `${px / 16}rem`;
    return `--spacing-${m}: ${rem}; /* ${px}px */`;
  });
}

function generateRadiusPrimitives(config: ResolvedThemeConfig): string[] {
  const decls: string[] = [];
  decls.push("--radius-none: 0;");
  decls.push(
    `--radius-sm: ${config.radius.sm / 16}rem; /* ${config.radius.sm}px */`
  );
  decls.push(
    `--radius-md: ${config.radius.md / 16}rem; /* ${config.radius.md}px */`
  );
  decls.push(
    `--radius-lg: ${config.radius.lg / 16}rem; /* ${config.radius.lg}px */`
  );
  decls.push(
    `--radius-xl: ${config.radius.xl / 16}rem; /* ${config.radius.xl}px */`
  );
  // 2xl and 3xl are derived from the scale
  decls.push(
    `--radius-2xl: ${(config.radius.xl * 1.333) / 16}rem; /* ${Math.round(config.radius.xl * 1.333)}px */`
  );
  decls.push(
    `--radius-3xl: ${(config.radius.xl * 2) / 16}rem; /* ${config.radius.xl * 2}px */`
  );
  decls.push(`--radius-full: ${config.radius.pill}px;`);
  return decls;
}

function generateShadowPrimitives(config: ResolvedThemeConfig): string[] {
  return [
    `--shadow-xs: ${config.shadows.xs};`,
    `--shadow-sm: ${config.shadows.sm};`,
    `--shadow-md: ${config.shadows.md};`,
    `--shadow-lg: ${config.shadows.lg};`,
    `--shadow-xl: ${config.shadows.xl};`,
  ];
}

function generateTypographyPrimitives(config: ResolvedThemeConfig): string[] {
  const decls: string[] = [];

  // Font-size scale — applied to wrapper/root, cascades to em-relative elements
  const scale = config.typography.scale;
  decls.push(`font-size: ${scale === 1 ? "1rem" : `${scale}rem`};`);

  // Font families
  decls.push(`--font-heading: ${config.typography.heading.family};`);
  decls.push(`--font-sans: ${config.typography.body.family};`);
  decls.push(`--font-body: ${config.typography.body.family};`);
  decls.push(`--font-mono: ${config.typography.mono.family};`);

  // Font sizes (matching Visor defaults — not configurable via .visor.yaml yet)
  const fontSizes: Record<string, number> = {
    xs: 12,
    sm: 14,
    base: 16,
    lg: 18,
    xl: 20,
    "2xl": 24,
    "3xl": 30,
    "4xl": 36,
  };
  for (const [name, px] of Object.entries(fontSizes)) {
    decls.push(`--font-size-${name}: ${px / 16}rem; /* ${px}px */`);
  }

  // Font weights
  decls.push(`--font-weight-normal: ${config.typography.body.weight};`);
  decls.push("--font-weight-medium: 500;");
  decls.push(`--font-weight-semibold: ${config.typography.heading.weight};`);
  decls.push("--font-weight-bold: 700;");

  // Line heights
  const lineHeights: Record<string, number> = {
    none: 1,
    tight: 1.25,
    snug: 1.375,
    normal: 1.5,
    relaxed: 1.625,
    loose: 2,
  };
  for (const [name, value] of Object.entries(lineHeights)) {
    decls.push(`--line-height-${name}: ${value};`);
  }

  return decls;
}

function generateMotionPrimitives(config: ResolvedThemeConfig): string[] {
  const decls: string[] = [];

  // Durations — emit the full primitive set, mapping from config's 3 semantic durations
  decls.push(`--motion-duration-100: ${config.motion["duration-fast"]};`);
  decls.push("--motion-duration-150: 150ms;");
  decls.push(`--motion-duration-200: ${config.motion["duration-normal"]};`);
  decls.push("--motion-duration-300: 300ms;");
  decls.push(`--motion-duration-500: ${config.motion["duration-slow"]};`);
  decls.push("--motion-duration-800: 800ms;");

  // Easings
  decls.push("--motion-easing-linear: linear;");
  decls.push("--motion-easing-ease-in: cubic-bezier(0.4, 0, 1, 1);");
  decls.push("--motion-easing-ease-out: cubic-bezier(0, 0, 0.2, 1);");
  decls.push(`--motion-easing-ease-in-out: ${config.motion.easing};`);
  decls.push(
    "--motion-easing-spring: cubic-bezier(0.34, 1.56, 0.64, 1);"
  );

  return decls;
}

function generateMiscPrimitives(): string[] {
  return [
    // Border widths
    "--border-width-1: 1px;",
    "--border-width-2: 2px;",
    "--border-width-3: 3px;",
    "--border-width-4: 4px;",
    // Z-index
    "--z-base: 0;",
    "--z-raised: 1;",
    "--z-dropdown: 1000;",
    "--z-sticky: 1100;",
    "--z-modal: 1300;",
    "--z-popover: 1400;",
    "--z-toast: 1500;",
    // Overlay
    "--overlay-bg: rgba(0, 0, 0, 0.5);",
    // Focus ring
    "--focus-ring-width: 2px;",
    "--focus-ring-offset: 2px;",
  ];
}

export function generatePrimitivesCss(
  primitives: GeneratedPrimitives,
  config: ResolvedThemeConfig
): string {
  const lines: string[] = [];

  lines.push(sectionComment("Primitive: Colors"));
  lines.push(
    block(":root", [generateColorPrimitives(primitives)])
  );

  lines.push(sectionComment("Primitive: Spacing"));
  lines.push(block(":root", generateSpacingPrimitives(config)));

  lines.push(sectionComment("Primitive: Border Radius"));
  lines.push(block(":root", generateRadiusPrimitives(config)));

  lines.push(sectionComment("Primitive: Typography"));
  lines.push(block(":root", generateTypographyPrimitives(config)));

  lines.push(sectionComment("Primitive: Shadows"));
  lines.push(block(":root", generateShadowPrimitives(config)));

  lines.push(sectionComment("Primitive: Motion"));
  lines.push(block(":root", generateMotionPrimitives(config)));

  lines.push(sectionComment("Primitive: Miscellaneous"));
  lines.push(block(":root", generateMiscPrimitives()));

  return header("Visor Theme — Primitives") + lines.join("\n");
}

// ============================================================
// Semantic CSS
// ============================================================

export function generateSemanticCss(tokens: SemanticTokens): string {
  const lines: string[] = [];

  // Text
  lines.push(sectionComment("Semantic: Text"));
  const textDecls = Object.entries(tokens.text).map(
    ([name, { light }]) => `--text-${name}: ${light};`
  );
  lines.push(block(":root", textDecls));

  // Surface
  lines.push(sectionComment("Semantic: Surface"));
  const surfaceDecls = Object.entries(tokens.surface).map(
    ([name, { light }]) => `--surface-${name}: ${light};`
  );
  lines.push(block(":root", surfaceDecls));

  // Border
  lines.push(sectionComment("Semantic: Border"));
  const borderDecls = Object.entries(tokens.border).map(
    ([name, { light }]) => `--border-${name}: ${light};`
  );
  lines.push(block(":root", borderDecls));

  // Interactive
  lines.push(sectionComment("Semantic: Interactive"));
  const interactiveDecls = Object.entries(tokens.interactive).map(
    ([name, { light }]) => `--interactive-${name}: ${light};`
  );
  lines.push(block(":root", interactiveDecls));

  return header("Visor Theme — Semantic") + lines.join("\n");
}

// ============================================================
// Adaptive CSS (Light / Dark)
// ============================================================

function buildAdaptiveDecls(
  tokens: SemanticTokens,
  theme: "light" | "dark"
): {
  textDecls: string[];
  surfaceDecls: string[];
  borderDecls: string[];
  interactiveDecls: string[];
} {
  const textDecls = Object.entries(tokens.text).map(
    ([name, values]) => `--text-${name}: ${values[theme]};`
  );
  const surfaceDecls = Object.entries(tokens.surface).map(
    ([name, values]) => `--surface-${name}: ${values[theme]};`
  );
  const borderDecls = Object.entries(tokens.border).map(
    ([name, values]) => `--border-${name}: ${values[theme]};`
  );
  const interactiveDecls = Object.entries(tokens.interactive).map(
    ([name, values]) => `--interactive-${name}: ${values[theme]};`
  );

  return { textDecls, surfaceDecls, borderDecls, interactiveDecls };
}

export function generateLightCss(tokens: SemanticTokens): string {
  const lines: string[] = [];
  const { textDecls, surfaceDecls, borderDecls, interactiveDecls } =
    buildAdaptiveDecls(tokens, "light");

  lines.push(sectionComment("Adaptive: Text (light)"));
  lines.push(block(":root", textDecls));

  lines.push(sectionComment("Adaptive: Surface (light)"));
  lines.push(block(":root", surfaceDecls));

  lines.push(sectionComment("Adaptive: Border (light)"));
  lines.push(block(":root", borderDecls));

  lines.push(sectionComment("Adaptive: Interactive (light)"));
  lines.push(block(":root", interactiveDecls));

  return header("Visor Theme — Light") + lines.join("\n");
}

export function generateDarkCss(tokens: SemanticTokens): string {
  const lines: string[] = [];
  const { textDecls, surfaceDecls, borderDecls, interactiveDecls } =
    buildAdaptiveDecls(tokens, "dark");

  const darkSelectors = [".dark", ".theme-dark", '[data-theme="dark"]'];
  const darkSelector = darkSelectors.join(",\n");
  const prefersSelector =
    ':root:not(.light):not(.theme-light):not([data-theme="light"])';

  // Manual toggle selectors
  lines.push(sectionComment("Adaptive: Text (dark) — manual toggle"));
  lines.push(block(darkSelector, textDecls));

  lines.push(sectionComment("Adaptive: Surface (dark) — manual toggle"));
  lines.push(block(darkSelector, surfaceDecls));

  lines.push(sectionComment("Adaptive: Border (dark) — manual toggle"));
  lines.push(block(darkSelector, borderDecls));

  lines.push(sectionComment("Adaptive: Interactive (dark) — manual toggle"));
  lines.push(block(darkSelector, interactiveDecls));

  // prefers-color-scheme: dark
  lines.push(
    sectionComment("Adaptive: Text (dark) — prefers-color-scheme")
  );
  lines.push(
    `@media (prefers-color-scheme: dark) {\n${block(prefersSelector, textDecls)}}`
  );
  lines.push("");

  lines.push(
    sectionComment("Adaptive: Surface (dark) — prefers-color-scheme")
  );
  lines.push(
    `@media (prefers-color-scheme: dark) {\n${block(prefersSelector, surfaceDecls)}}`
  );
  lines.push("");

  lines.push(
    sectionComment("Adaptive: Border (dark) — prefers-color-scheme")
  );
  lines.push(
    `@media (prefers-color-scheme: dark) {\n${block(prefersSelector, borderDecls)}}`
  );
  lines.push("");

  lines.push(
    sectionComment("Adaptive: Interactive (dark) — prefers-color-scheme")
  );
  lines.push(
    `@media (prefers-color-scheme: dark) {\n${block(prefersSelector, interactiveDecls)}}`
  );
  lines.push("");

  return header("Visor Theme — Dark") + lines.join("\n");
}

// ============================================================
// Full Bundle
// ============================================================

export function generateFullBundleCss(
  primitives: GeneratedPrimitives,
  tokens: SemanticTokens,
  config: ResolvedThemeConfig
): string {
  const lines: string[] = [
    header("Visor Theme — Full Bundle"),
    "/* Import order: primitives → adaptive (light) → adaptive (dark) */",
    "",
  ];

  // Tier 1: Primitives
  lines.push(
    "/* ============================================",
    "   Tier 1: Primitives",
    "   ============================================ */"
  );
  const primitivesBody = generatePrimitivesCss(primitives, config)
    .split("\n")
    .slice(6)
    .join("\n");
  lines.push(primitivesBody);

  // Tier 3: Adaptive — Light
  lines.push(
    "/* ============================================",
    "   Tier 3: Adaptive — Light Theme (:root)",
    "   ============================================ */"
  );
  const lightBody = generateLightCss(tokens).split("\n").slice(6).join("\n");
  lines.push(lightBody);

  // Tier 3: Adaptive — Dark
  lines.push(
    "/* ============================================",
    '   Tier 3: Adaptive — Dark Theme (.dark, .theme-dark, [data-theme="dark"])',
    "   and @media (prefers-color-scheme: dark)",
    "   ============================================ */"
  );
  const darkBody = generateDarkCss(tokens).split("\n").slice(6).join("\n");
  lines.push(darkBody);

  return lines.join("\n");
}
