import 'package:flutter/material.dart';

/// Visor's semantic color tokens as a Flutter [ThemeExtension].
///
/// Mirrors the CSS semantic token set from the `.visor.yaml` interchange
/// format: `text.*`, `surface.*`, `border.*`, and `interactive.*`. These
/// tokens are theme-agnostic — widgets reference them via
/// `Theme.of(context).extension<VisorColors>()`, never literal [Color]
/// values.
///
/// The concrete `VisorColors.light` / `VisorColors.dark` instances are
/// generated by the Visor CLI from your project's `.visor.yaml` and live
/// in your project's `ui_colors.dart`. This class defines the *shape*;
/// generated code supplies the *values*.
@immutable
class VisorColors extends ThemeExtension<VisorColors> {
  const VisorColors({
    // text
    required this.textPrimary,
    required this.textSecondary,
    required this.textTertiary,
    required this.textDisabled,
    required this.textInverse,
    required this.textInverseSecondary,
    required this.textLink,
    required this.textLinkHover,
    required this.textSuccess,
    required this.textWarning,
    required this.textError,
    required this.textInfo,
    // surface
    required this.surfacePage,
    required this.surfaceCard,
    required this.surfaceSubtle,
    required this.surfaceMuted,
    required this.surfaceOverlay,
    required this.surfaceInteractiveDefault,
    required this.surfaceInteractiveHover,
    required this.surfaceInteractiveActive,
    required this.surfaceInteractiveDisabled,
    required this.surfaceAccentSubtle,
    required this.surfaceAccentDefault,
    required this.surfaceAccentStrong,
    required this.surfaceSuccessSubtle,
    required this.surfaceSuccessDefault,
    required this.surfaceWarningSubtle,
    required this.surfaceWarningDefault,
    required this.surfaceErrorSubtle,
    required this.surfaceErrorDefault,
    required this.surfaceInfoSubtle,
    required this.surfaceInfoDefault,
    // border
    required this.borderDefault,
    required this.borderMuted,
    required this.borderStrong,
    required this.borderFocus,
    required this.borderDisabled,
    required this.borderSuccess,
    required this.borderWarning,
    required this.borderError,
    required this.borderInfo,
    // interactive
    required this.interactivePrimaryBg,
    required this.interactivePrimaryBgHover,
    required this.interactivePrimaryBgActive,
    required this.interactivePrimaryText,
    required this.interactiveSecondaryBg,
    required this.interactiveSecondaryBgHover,
    required this.interactiveSecondaryBgActive,
    required this.interactiveSecondaryText,
    required this.interactiveSecondaryBorder,
    required this.interactiveDestructiveBg,
    required this.interactiveDestructiveBgHover,
    required this.interactiveDestructiveText,
    required this.interactiveGhostBg,
    required this.interactiveGhostBgHover,
  });

  // ==========================================================================
  // Text
  // ==========================================================================
  final Color textPrimary;
  final Color textSecondary;
  final Color textTertiary;
  final Color textDisabled;
  final Color textInverse;
  final Color textInverseSecondary;
  final Color textLink;
  final Color textLinkHover;
  final Color textSuccess;
  final Color textWarning;
  final Color textError;
  final Color textInfo;

  // ==========================================================================
  // Surface
  // ==========================================================================
  final Color surfacePage;
  final Color surfaceCard;
  final Color surfaceSubtle;
  final Color surfaceMuted;
  final Color surfaceOverlay;
  final Color surfaceInteractiveDefault;
  final Color surfaceInteractiveHover;
  final Color surfaceInteractiveActive;
  final Color surfaceInteractiveDisabled;
  final Color surfaceAccentSubtle;
  final Color surfaceAccentDefault;
  final Color surfaceAccentStrong;
  final Color surfaceSuccessSubtle;
  final Color surfaceSuccessDefault;
  final Color surfaceWarningSubtle;
  final Color surfaceWarningDefault;
  final Color surfaceErrorSubtle;
  final Color surfaceErrorDefault;
  final Color surfaceInfoSubtle;
  final Color surfaceInfoDefault;

  // ==========================================================================
  // Border
  // ==========================================================================
  final Color borderDefault;
  final Color borderMuted;
  final Color borderStrong;
  final Color borderFocus;
  final Color borderDisabled;
  final Color borderSuccess;
  final Color borderWarning;
  final Color borderError;
  final Color borderInfo;

  // ==========================================================================
  // Interactive
  // ==========================================================================
  final Color interactivePrimaryBg;
  final Color interactivePrimaryBgHover;
  final Color interactivePrimaryBgActive;
  final Color interactivePrimaryText;
  final Color interactiveSecondaryBg;
  final Color interactiveSecondaryBgHover;
  final Color interactiveSecondaryBgActive;
  final Color interactiveSecondaryText;
  final Color interactiveSecondaryBorder;
  final Color interactiveDestructiveBg;
  final Color interactiveDestructiveBgHover;
  final Color interactiveDestructiveText;
  final Color interactiveGhostBg;
  final Color interactiveGhostBgHover;

  @override
  VisorColors copyWith({
    Color? textPrimary,
    Color? textSecondary,
    Color? textTertiary,
    Color? textDisabled,
    Color? textInverse,
    Color? textInverseSecondary,
    Color? textLink,
    Color? textLinkHover,
    Color? textSuccess,
    Color? textWarning,
    Color? textError,
    Color? textInfo,
    Color? surfacePage,
    Color? surfaceCard,
    Color? surfaceSubtle,
    Color? surfaceMuted,
    Color? surfaceOverlay,
    Color? surfaceInteractiveDefault,
    Color? surfaceInteractiveHover,
    Color? surfaceInteractiveActive,
    Color? surfaceInteractiveDisabled,
    Color? surfaceAccentSubtle,
    Color? surfaceAccentDefault,
    Color? surfaceAccentStrong,
    Color? surfaceSuccessSubtle,
    Color? surfaceSuccessDefault,
    Color? surfaceWarningSubtle,
    Color? surfaceWarningDefault,
    Color? surfaceErrorSubtle,
    Color? surfaceErrorDefault,
    Color? surfaceInfoSubtle,
    Color? surfaceInfoDefault,
    Color? borderDefault,
    Color? borderMuted,
    Color? borderStrong,
    Color? borderFocus,
    Color? borderDisabled,
    Color? borderSuccess,
    Color? borderWarning,
    Color? borderError,
    Color? borderInfo,
    Color? interactivePrimaryBg,
    Color? interactivePrimaryBgHover,
    Color? interactivePrimaryBgActive,
    Color? interactivePrimaryText,
    Color? interactiveSecondaryBg,
    Color? interactiveSecondaryBgHover,
    Color? interactiveSecondaryBgActive,
    Color? interactiveSecondaryText,
    Color? interactiveSecondaryBorder,
    Color? interactiveDestructiveBg,
    Color? interactiveDestructiveBgHover,
    Color? interactiveDestructiveText,
    Color? interactiveGhostBg,
    Color? interactiveGhostBgHover,
  }) {
    return VisorColors(
      textPrimary: textPrimary ?? this.textPrimary,
      textSecondary: textSecondary ?? this.textSecondary,
      textTertiary: textTertiary ?? this.textTertiary,
      textDisabled: textDisabled ?? this.textDisabled,
      textInverse: textInverse ?? this.textInverse,
      textInverseSecondary: textInverseSecondary ?? this.textInverseSecondary,
      textLink: textLink ?? this.textLink,
      textLinkHover: textLinkHover ?? this.textLinkHover,
      textSuccess: textSuccess ?? this.textSuccess,
      textWarning: textWarning ?? this.textWarning,
      textError: textError ?? this.textError,
      textInfo: textInfo ?? this.textInfo,
      surfacePage: surfacePage ?? this.surfacePage,
      surfaceCard: surfaceCard ?? this.surfaceCard,
      surfaceSubtle: surfaceSubtle ?? this.surfaceSubtle,
      surfaceMuted: surfaceMuted ?? this.surfaceMuted,
      surfaceOverlay: surfaceOverlay ?? this.surfaceOverlay,
      surfaceInteractiveDefault:
          surfaceInteractiveDefault ?? this.surfaceInteractiveDefault,
      surfaceInteractiveHover:
          surfaceInteractiveHover ?? this.surfaceInteractiveHover,
      surfaceInteractiveActive:
          surfaceInteractiveActive ?? this.surfaceInteractiveActive,
      surfaceInteractiveDisabled:
          surfaceInteractiveDisabled ?? this.surfaceInteractiveDisabled,
      surfaceAccentSubtle: surfaceAccentSubtle ?? this.surfaceAccentSubtle,
      surfaceAccentDefault: surfaceAccentDefault ?? this.surfaceAccentDefault,
      surfaceAccentStrong: surfaceAccentStrong ?? this.surfaceAccentStrong,
      surfaceSuccessSubtle: surfaceSuccessSubtle ?? this.surfaceSuccessSubtle,
      surfaceSuccessDefault:
          surfaceSuccessDefault ?? this.surfaceSuccessDefault,
      surfaceWarningSubtle: surfaceWarningSubtle ?? this.surfaceWarningSubtle,
      surfaceWarningDefault:
          surfaceWarningDefault ?? this.surfaceWarningDefault,
      surfaceErrorSubtle: surfaceErrorSubtle ?? this.surfaceErrorSubtle,
      surfaceErrorDefault: surfaceErrorDefault ?? this.surfaceErrorDefault,
      surfaceInfoSubtle: surfaceInfoSubtle ?? this.surfaceInfoSubtle,
      surfaceInfoDefault: surfaceInfoDefault ?? this.surfaceInfoDefault,
      borderDefault: borderDefault ?? this.borderDefault,
      borderMuted: borderMuted ?? this.borderMuted,
      borderStrong: borderStrong ?? this.borderStrong,
      borderFocus: borderFocus ?? this.borderFocus,
      borderDisabled: borderDisabled ?? this.borderDisabled,
      borderSuccess: borderSuccess ?? this.borderSuccess,
      borderWarning: borderWarning ?? this.borderWarning,
      borderError: borderError ?? this.borderError,
      borderInfo: borderInfo ?? this.borderInfo,
      interactivePrimaryBg: interactivePrimaryBg ?? this.interactivePrimaryBg,
      interactivePrimaryBgHover:
          interactivePrimaryBgHover ?? this.interactivePrimaryBgHover,
      interactivePrimaryBgActive:
          interactivePrimaryBgActive ?? this.interactivePrimaryBgActive,
      interactivePrimaryText:
          interactivePrimaryText ?? this.interactivePrimaryText,
      interactiveSecondaryBg:
          interactiveSecondaryBg ?? this.interactiveSecondaryBg,
      interactiveSecondaryBgHover:
          interactiveSecondaryBgHover ?? this.interactiveSecondaryBgHover,
      interactiveSecondaryBgActive:
          interactiveSecondaryBgActive ?? this.interactiveSecondaryBgActive,
      interactiveSecondaryText:
          interactiveSecondaryText ?? this.interactiveSecondaryText,
      interactiveSecondaryBorder:
          interactiveSecondaryBorder ?? this.interactiveSecondaryBorder,
      interactiveDestructiveBg:
          interactiveDestructiveBg ?? this.interactiveDestructiveBg,
      interactiveDestructiveBgHover:
          interactiveDestructiveBgHover ?? this.interactiveDestructiveBgHover,
      interactiveDestructiveText:
          interactiveDestructiveText ?? this.interactiveDestructiveText,
      interactiveGhostBg: interactiveGhostBg ?? this.interactiveGhostBg,
      interactiveGhostBgHover:
          interactiveGhostBgHover ?? this.interactiveGhostBgHover,
    );
  }

  @override
  VisorColors lerp(ThemeExtension<VisorColors>? other, double t) {
    if (other is! VisorColors) return this;
    return VisorColors(
      textPrimary: Color.lerp(textPrimary, other.textPrimary, t)!,
      textSecondary: Color.lerp(textSecondary, other.textSecondary, t)!,
      textTertiary: Color.lerp(textTertiary, other.textTertiary, t)!,
      textDisabled: Color.lerp(textDisabled, other.textDisabled, t)!,
      textInverse: Color.lerp(textInverse, other.textInverse, t)!,
      textInverseSecondary:
          Color.lerp(textInverseSecondary, other.textInverseSecondary, t)!,
      textLink: Color.lerp(textLink, other.textLink, t)!,
      textLinkHover: Color.lerp(textLinkHover, other.textLinkHover, t)!,
      textSuccess: Color.lerp(textSuccess, other.textSuccess, t)!,
      textWarning: Color.lerp(textWarning, other.textWarning, t)!,
      textError: Color.lerp(textError, other.textError, t)!,
      textInfo: Color.lerp(textInfo, other.textInfo, t)!,
      surfacePage: Color.lerp(surfacePage, other.surfacePage, t)!,
      surfaceCard: Color.lerp(surfaceCard, other.surfaceCard, t)!,
      surfaceSubtle: Color.lerp(surfaceSubtle, other.surfaceSubtle, t)!,
      surfaceMuted: Color.lerp(surfaceMuted, other.surfaceMuted, t)!,
      surfaceOverlay: Color.lerp(surfaceOverlay, other.surfaceOverlay, t)!,
      surfaceInteractiveDefault: Color.lerp(
        surfaceInteractiveDefault,
        other.surfaceInteractiveDefault,
        t,
      )!,
      surfaceInteractiveHover: Color.lerp(
        surfaceInteractiveHover,
        other.surfaceInteractiveHover,
        t,
      )!,
      surfaceInteractiveActive: Color.lerp(
        surfaceInteractiveActive,
        other.surfaceInteractiveActive,
        t,
      )!,
      surfaceInteractiveDisabled: Color.lerp(
        surfaceInteractiveDisabled,
        other.surfaceInteractiveDisabled,
        t,
      )!,
      surfaceAccentSubtle:
          Color.lerp(surfaceAccentSubtle, other.surfaceAccentSubtle, t)!,
      surfaceAccentDefault:
          Color.lerp(surfaceAccentDefault, other.surfaceAccentDefault, t)!,
      surfaceAccentStrong:
          Color.lerp(surfaceAccentStrong, other.surfaceAccentStrong, t)!,
      surfaceSuccessSubtle:
          Color.lerp(surfaceSuccessSubtle, other.surfaceSuccessSubtle, t)!,
      surfaceSuccessDefault:
          Color.lerp(surfaceSuccessDefault, other.surfaceSuccessDefault, t)!,
      surfaceWarningSubtle:
          Color.lerp(surfaceWarningSubtle, other.surfaceWarningSubtle, t)!,
      surfaceWarningDefault:
          Color.lerp(surfaceWarningDefault, other.surfaceWarningDefault, t)!,
      surfaceErrorSubtle:
          Color.lerp(surfaceErrorSubtle, other.surfaceErrorSubtle, t)!,
      surfaceErrorDefault:
          Color.lerp(surfaceErrorDefault, other.surfaceErrorDefault, t)!,
      surfaceInfoSubtle:
          Color.lerp(surfaceInfoSubtle, other.surfaceInfoSubtle, t)!,
      surfaceInfoDefault:
          Color.lerp(surfaceInfoDefault, other.surfaceInfoDefault, t)!,
      borderDefault: Color.lerp(borderDefault, other.borderDefault, t)!,
      borderMuted: Color.lerp(borderMuted, other.borderMuted, t)!,
      borderStrong: Color.lerp(borderStrong, other.borderStrong, t)!,
      borderFocus: Color.lerp(borderFocus, other.borderFocus, t)!,
      borderDisabled: Color.lerp(borderDisabled, other.borderDisabled, t)!,
      borderSuccess: Color.lerp(borderSuccess, other.borderSuccess, t)!,
      borderWarning: Color.lerp(borderWarning, other.borderWarning, t)!,
      borderError: Color.lerp(borderError, other.borderError, t)!,
      borderInfo: Color.lerp(borderInfo, other.borderInfo, t)!,
      interactivePrimaryBg:
          Color.lerp(interactivePrimaryBg, other.interactivePrimaryBg, t)!,
      interactivePrimaryBgHover: Color.lerp(
        interactivePrimaryBgHover,
        other.interactivePrimaryBgHover,
        t,
      )!,
      interactivePrimaryBgActive: Color.lerp(
        interactivePrimaryBgActive,
        other.interactivePrimaryBgActive,
        t,
      )!,
      interactivePrimaryText:
          Color.lerp(interactivePrimaryText, other.interactivePrimaryText, t)!,
      interactiveSecondaryBg:
          Color.lerp(interactiveSecondaryBg, other.interactiveSecondaryBg, t)!,
      interactiveSecondaryBgHover: Color.lerp(
        interactiveSecondaryBgHover,
        other.interactiveSecondaryBgHover,
        t,
      )!,
      interactiveSecondaryBgActive: Color.lerp(
        interactiveSecondaryBgActive,
        other.interactiveSecondaryBgActive,
        t,
      )!,
      interactiveSecondaryText: Color.lerp(
        interactiveSecondaryText,
        other.interactiveSecondaryText,
        t,
      )!,
      interactiveSecondaryBorder: Color.lerp(
        interactiveSecondaryBorder,
        other.interactiveSecondaryBorder,
        t,
      )!,
      interactiveDestructiveBg: Color.lerp(
        interactiveDestructiveBg,
        other.interactiveDestructiveBg,
        t,
      )!,
      interactiveDestructiveBgHover: Color.lerp(
        interactiveDestructiveBgHover,
        other.interactiveDestructiveBgHover,
        t,
      )!,
      interactiveDestructiveText: Color.lerp(
        interactiveDestructiveText,
        other.interactiveDestructiveText,
        t,
      )!,
      interactiveGhostBg:
          Color.lerp(interactiveGhostBg, other.interactiveGhostBg, t)!,
      interactiveGhostBgHover: Color.lerp(
        interactiveGhostBgHover,
        other.interactiveGhostBgHover,
        t,
      )!,
    );
  }
}
