// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.
// Source: .visor.yaml → Visor theme engine → flutter adapter.

import 'dart:ui';

import 'package:visor_core/visor_core.dart';

/// Generated color tokens for the blackout theme.
///
/// Do not edit this file manually — regenerate from .visor.yaml.
sealed class VisorColors {
  // ========================================================================
  // Anchors
  // ========================================================================
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);

  // ========================================================================
  // Primary scale
  // ========================================================================
  static const Color primary50 = Color(0xFFF5F5F5);
  static const Color primary100 = Color(0xFFF2F2F2);
  static const Color primary200 = Color(0xFFEDEDED);
  static const Color primary300 = Color(0xFFE6E6E6);
  static const Color primary400 = Color(0xFFDCDCDC);
  static const Color primary500 = Color(0xFF666666);
  static const Color primary600 = Color(0xFF555555);
  static const Color primary700 = Color(0xFF424242);
  static const Color primary800 = Color(0xFF2E2E2E);
  static const Color primary900 = Color(0xFF1B1B1B);
  static const Color primary950 = Color(0xFF090909);

  // ========================================================================
  // Accent scale
  // ========================================================================
  static const Color accent50 = Color(0xFFF5F5F5);
  static const Color accent100 = Color(0xFFF2F2F2);
  static const Color accent200 = Color(0xFFEDEDED);
  static const Color accent300 = Color(0xFFE6E6E6);
  static const Color accent400 = Color(0xFFDCDCDC);
  static const Color accent500 = Color(0xFF666666);
  static const Color accent600 = Color(0xFF555555);
  static const Color accent700 = Color(0xFF424242);
  static const Color accent800 = Color(0xFF2E2E2E);
  static const Color accent900 = Color(0xFF1B1B1B);
  static const Color accent950 = Color(0xFF090909);

  // ========================================================================
  // Neutral scale
  // ========================================================================
  static const Color neutral50 = Color(0xFFF5F5F5);
  static const Color neutral100 = Color(0xFFF1F1F1);
  static const Color neutral200 = Color(0xFFEAEAEA);
  static const Color neutral300 = Color(0xFFE0E0E0);
  static const Color neutral400 = Color(0xFFD2D2D2);
  static const Color neutral500 = Color(0xFF333333);
  static const Color neutral600 = Color(0xFF555555);
  static const Color neutral700 = Color(0xFF424242);
  static const Color neutral800 = Color(0xFF2E2E2E);
  static const Color neutral900 = Color(0xFF1B1B1B);
  static const Color neutral950 = Color(0xFF090909);

  // ========================================================================
  // Success scale
  // ========================================================================
  static const Color success50 = Color(0xFFE8FBEB);
  static const Color success100 = Color(0xFFDEFDE3);
  static const Color success500 = Color(0xFF22C55E);
  static const Color success600 = Color(0xFF00672B);
  static const Color success700 = Color(0xFF005120);
  static const Color success900 = Color(0xFF002209);

  // ========================================================================
  // Warning scale
  // ========================================================================
  static const Color warning50 = Color(0xFFFFF3E6);
  static const Color warning100 = Color(0xFFFFF1E3);
  static const Color warning500 = Color(0xFFF59E0B);
  static const Color warning600 = Color(0xFF774A01);
  static const Color warning700 = Color(0xFF5E3900);
  static const Color warning900 = Color(0xFF281600);

  // ========================================================================
  // Error scale
  // ========================================================================
  static const Color error50 = Color(0xFFFFF2F0);
  static const Color error100 = Color(0xFFFFEFED);
  static const Color error500 = Color(0xFFEF4444);
  static const Color error600 = Color(0xFFA30016);
  static const Color error700 = Color(0xFF81000F);
  static const Color error900 = Color(0xFF3A0003);

  // ========================================================================
  // Info scale
  // ========================================================================
  static const Color info50 = Color(0xFFECF7FF);
  static const Color info100 = Color(0xFFE8F5FF);
  static const Color info500 = Color(0xFF0EA5E9);
  static const Color info600 = Color(0xFF005C85);
  static const Color info700 = Color(0xFF004869);
  static const Color info900 = Color(0xFF001D2E);

  // ========================================================================
  // Opacity variants (pre-computed at codegen)
  // ========================================================================
  static const Color primary500_5o = Color(0x0D666666);
  static const Color primary500_10o = Color(0x1A666666);
  static const Color primary500_20o = Color(0x33666666);
  static const Color primary500_40o = Color(0x66666666);
  static const Color primary500_50o = Color(0x80666666);
  static const Color primary500_60o = Color(0x99666666);
  static const Color primary500_80o = Color(0xCC666666);
  static const Color primary600_5o = Color(0x0D555555);
  static const Color primary600_10o = Color(0x1A555555);
  static const Color primary600_20o = Color(0x33555555);
  static const Color primary600_40o = Color(0x66555555);
  static const Color primary600_50o = Color(0x80555555);
  static const Color primary600_60o = Color(0x99555555);
  static const Color primary600_80o = Color(0xCC555555);
  static const Color accent500_5o = Color(0x0D666666);
  static const Color accent500_10o = Color(0x1A666666);
  static const Color accent500_20o = Color(0x33666666);
  static const Color accent500_40o = Color(0x66666666);
  static const Color accent500_50o = Color(0x80666666);
  static const Color accent500_60o = Color(0x99666666);
  static const Color accent500_80o = Color(0xCC666666);
  static const Color white_5o = Color(0x0DFFFFFF);
  static const Color white_10o = Color(0x1AFFFFFF);
  static const Color white_20o = Color(0x33FFFFFF);
  static const Color white_40o = Color(0x66FFFFFF);
  static const Color white_50o = Color(0x80FFFFFF);
  static const Color white_60o = Color(0x99FFFFFF);
  static const Color white_80o = Color(0xCCFFFFFF);
  static const Color black_5o = Color(0x0D000000);
  static const Color black_10o = Color(0x1A000000);
  static const Color black_20o = Color(0x33000000);
  static const Color black_40o = Color(0x66000000);
  static const Color black_50o = Color(0x80000000);
  static const Color black_60o = Color(0x99000000);
  static const Color black_80o = Color(0xCC000000);

  // ========================================================================
  // Semantic — Light
  // ========================================================================
  static final VisorColorsData light = VisorColorsData(
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFFFFFFF),
    textTertiary: Color(0xFFFFFFFF),
    textDisabled: Color(0xFFFFFFFF),
    textInverse: Color(0xFFFFFFFF),
    textInverseSecondary: Color(0xFFEAEAEA),
    textLink: Color(0xFF555555),
    textLinkHover: Color(0xFF424242),
    textSuccess: Color(0xFF005120),
    textWarning: Color(0xFF5E3900),
    textError: Color(0xFF81000F),
    textInfo: Color(0xFF004869),
    surfacePage: Color(0xFF0A0A0A),
    surfaceCard: Color(0xFFFFFFFF),
    surfaceSubtle: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFFFFFFF),
    surfaceOverlay: Color(0xFF1B1B1B),
    surfaceInteractiveDefault: Color(0xFF000000),
    surfaceInteractiveHover: Color(0xFFFFFFFF),
    surfaceInteractiveActive: Color(0xFFFFFFFF),
    surfaceInteractiveDisabled: Color(0xFFFFFFFF),
    surfaceAccentSubtle: Color(0xFFF5F5F5),
    surfaceAccentDefault: Color(0xFF666666),
    surfaceAccentStrong: Color(0xFF555555),
    surfaceSuccessSubtle: Color(0xFFE8FBEB),
    surfaceSuccessDefault: Color(0xFF22C55E),
    surfaceWarningSubtle: Color(0xFFFFF3E6),
    surfaceWarningDefault: Color(0xFFF59E0B),
    surfaceErrorSubtle: Color(0xFFFFF2F0),
    surfaceErrorDefault: Color(0xFFEF4444),
    surfaceInfoSubtle: Color(0xFFECF7FF),
    surfaceInfoDefault: Color(0xFF0EA5E9),
    borderDefault: Color(0xFFFFFFFF),
    borderMuted: Color(0xFFFFFFFF),
    borderStrong: Color(0xFFFFFFFF),
    borderFocus: Color(0xFF666666),
    borderDisabled: Color(0xFFF1F1F1),
    borderSuccess: Color(0xFF22C55E),
    borderWarning: Color(0xFFF59E0B),
    borderError: Color(0xFFEF4444),
    borderInfo: Color(0xFF0EA5E9),
    interactivePrimaryBg: Color(0xFF555555),
    interactivePrimaryBgHover: Color(0xFF424242),
    interactivePrimaryBgActive: Color(0xFF2E2E2E),
    interactivePrimaryText: Color(0xFFFFFFFF),
    interactiveSecondaryBg: Color(0xFFFFFFFF),
    interactiveSecondaryBgHover: Color(0xFFF5F5F5),
    interactiveSecondaryBgActive: Color(0xFFF1F1F1),
    interactiveSecondaryText: Color(0xFF1B1B1B),
    interactiveSecondaryBorder: Color(0xFFE0E0E0),
    interactiveDestructiveBg: Color(0xFFA30016),
    interactiveDestructiveBgHover: Color(0xFF81000F),
    interactiveDestructiveText: Color(0xFFFFFFFF),
    interactiveGhostBg: Color(0xFFFFFFFF),
    interactiveGhostBgHover: Color(0xFFF1F1F1),
  );

  // ========================================================================
  // Semantic — Dark
  // ========================================================================
  static final VisorColorsData dark = VisorColorsData(
    textPrimary: Color(0xFFFFFFFF),
    textSecondary: Color(0xFFFFFFFF),
    textTertiary: Color(0xFFFFFFFF),
    textDisabled: Color(0xFFFFFFFF),
    textInverse: Color(0xFF1B1B1B),
    textInverseSecondary: Color(0xFF424242),
    textLink: Color(0xFFDCDCDC),
    textLinkHover: Color(0xFFE6E6E6),
    textSuccess: Color(0xFF22C55E),
    textWarning: Color(0xFFF59E0B),
    textError: Color(0xFFEF4444),
    textInfo: Color(0xFF0EA5E9),
    surfacePage: Color(0xFF000000),
    surfaceCard: Color(0xFFFFFFFF),
    surfaceSubtle: Color(0xFFFFFFFF),
    surfaceMuted: Color(0xFFFFFFFF),
    surfaceOverlay: Color(0xFF090909),
    surfaceInteractiveDefault: Color(0xFF2E2E2E),
    surfaceInteractiveHover: Color(0xFF424242),
    surfaceInteractiveActive: Color(0xFF555555),
    surfaceInteractiveDisabled: Color(0xFF2E2E2E),
    surfaceAccentSubtle: Color(0xFF1B1B1B),
    surfaceAccentDefault: Color(0xFF666666),
    surfaceAccentStrong: Color(0xFFDCDCDC),
    surfaceSuccessSubtle: Color(0xFF002209),
    surfaceSuccessDefault: Color(0xFF22C55E),
    surfaceWarningSubtle: Color(0xFF281600),
    surfaceWarningDefault: Color(0xFFF59E0B),
    surfaceErrorSubtle: Color(0xFF3A0003),
    surfaceErrorDefault: Color(0xFFEF4444),
    surfaceInfoSubtle: Color(0xFF001D2E),
    surfaceInfoDefault: Color(0xFF0EA5E9),
    borderDefault: Color(0xFFFFFFFF),
    borderMuted: Color(0xFFFFFFFF),
    borderStrong: Color(0xFFFFFFFF),
    borderFocus: Color(0xFFDCDCDC),
    borderDisabled: Color(0xFF2E2E2E),
    borderSuccess: Color(0xFF22C55E),
    borderWarning: Color(0xFFF59E0B),
    borderError: Color(0xFFEF4444),
    borderInfo: Color(0xFF0EA5E9),
    interactivePrimaryBg: Color(0xFF666666),
    interactivePrimaryBgHover: Color(0xFFDCDCDC),
    interactivePrimaryBgActive: Color(0xFFE6E6E6),
    interactivePrimaryText: Color(0xFFFFFFFF),
    interactiveSecondaryBg: Color(0xFF2E2E2E),
    interactiveSecondaryBgHover: Color(0xFF424242),
    interactiveSecondaryBgActive: Color(0xFF555555),
    interactiveSecondaryText: Color(0xFFF5F5F5),
    interactiveSecondaryBorder: Color(0xFF555555),
    interactiveDestructiveBg: Color(0xFFEF4444),
    interactiveDestructiveBgHover: Color(0xFFA30016),
    interactiveDestructiveText: Color(0xFFFFFFFF),
    interactiveGhostBg: Color(0xFF2E2E2E),
    interactiveGhostBgHover: Color(0xFF424242),
  );
}
