/**
 * Flutter Adapter
 *
 * Generates a Dart package (or token-only file set) from Visor theme data,
 * matching the Low Orbit canonical `packages/ui/` structure:
 *
 * ```
 * packages/ui/
 * ├── pubspec.yaml
 * ├── lib/
 * │   ├── ui.dart                        # barrel
 * │   └── src/
 * │       ├── colors/ui_colors.dart      # primitives + VisorColors.light/dark
 * │       └── theme/ui_theme.dart        # VisorAppTheme.{light,dark}
 * ```
 *
 * Token categories not yet emitted (typography, spacing, radius, shadows,
 * motion) fall back to `visor_core` defaults — the consumer's app renders
 * correctly with what's available and gets richer theming as future
 * adapter phases land.
 */

import type {
  AdapterFileMap,
  AdapterInput,
  FlutterAdapterOptions,
} from "./types.js";
import { emitColorsDart } from "../flutter/emit-colors.js";

/**
 * Generate a Flutter token package from theme engine output.
 *
 * @returns File map keyed by path relative to the output directory.
 */
export function flutterAdapter(
  input: AdapterInput,
  options?: FlutterAdapterOptions,
): AdapterFileMap {
  const packageName = options?.packageName ?? "ui";
  const themeClassName = options?.themeClassName ?? "VisorAppTheme";
  const visorCoreVersion = options?.visorCoreVersion ?? "^0.1.0";
  const tokensOnly = options?.tokensOnly ?? false;
  const lightOnly = options?.lightOnly ?? false;
  const darkOnly = options?.darkOnly ?? false;

  const files: Record<string, string> = {};

  // Always emit the colors token file.
  files["lib/src/colors/ui_colors.dart"] = emitColorsDart(input);

  // Skip the package scaffolding when --tokens-only.
  if (!tokensOnly) {
    files["pubspec.yaml"] = emitPubspec(packageName, visorCoreVersion);
    files["lib/ui.dart"] = emitBarrel();
    files["lib/src/theme/ui_theme.dart"] = emitThemeDart(
      themeClassName,
      { lightOnly, darkOnly },
    );
  }

  return { files };
}

function emitPubspec(packageName: string, visorCoreVersion: string): string {
  return [
    `name: ${packageName}`,
    `description: Generated Visor tokens for this project. Regenerate with \`visor theme apply\`.`,
    `version: 0.1.0+1`,
    `publish_to: none`,
    ``,
    `environment:`,
    `  sdk: ^3.5.0`,
    `  flutter: ^3.24.0`,
    ``,
    `dependencies:`,
    `  flutter:`,
    `    sdk: flutter`,
    `  visor_core: ${visorCoreVersion}`,
    ``,
    `dev_dependencies:`,
    `  flutter_test:`,
    `    sdk: flutter`,
    ``,
    `flutter:`,
    `  uses-material-design: true`,
    ``,
  ].join("\n");
}

function emitBarrel(): string {
  return [
    `/// Generated barrel for the Visor tokens package.`,
    `library;`,
    ``,
    `export 'src/colors/ui_colors.dart';`,
    `export 'src/theme/ui_theme.dart';`,
    ``,
    `// Re-export visor_core so consumers can access ThemeExtensions with a`,
    `// single import of this package.`,
    `export 'package:visor_core/visor_core.dart';`,
    ``,
  ].join("\n");
}

function emitThemeDart(
  className: string,
  opts: { lightOnly: boolean; darkOnly: boolean },
): string {
  const emitLight = !opts.darkOnly;
  const emitDark = !opts.lightOnly;

  const lines: string[] = [
    `// GENERATED BY visor — DO NOT EDIT.`,
    `// Regenerate with \`visor theme apply --adapter flutter\`.`,
    ``,
    `import 'package:flutter/material.dart';`,
    `import 'package:visor_core/visor_core.dart';`,
    ``,
    `import '../colors/ui_colors.dart';`,
    ``,
    `/// Assembled Material 3 [ThemeData] for this project.`,
    `///`,
    `/// Wire into [MaterialApp]:`,
    `/// \`\`\`dart`,
    `/// MaterialApp(`,
    `///   theme: ${className}.light,`,
    `///   darkTheme: ${className}.dark,`,
    `/// );`,
    `/// \`\`\``,
    `sealed class ${className} {`,
  ];

  if (emitLight) {
    lines.push(
      `  static ThemeData get light => VisorTheme.build(`,
      `        colors: UIColors.light,`,
      `        brightness: Brightness.light,`,
      `      );`,
      ``,
    );
  }

  if (emitDark) {
    lines.push(
      `  static ThemeData get dark => VisorTheme.build(`,
      `        colors: UIColors.dark,`,
      `        brightness: Brightness.dark,`,
      `      );`,
      ``,
    );
  }

  lines.push(`}`);
  lines.push(``);
  return lines.join("\n");
}
