// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.

import 'package:visor_core/visor_core.dart';

/// Generated border-radius tokens (raw pixel values).
sealed class VisorRadius {
  static final VisorRadiusData instance = VisorRadiusData(
    sm: 2,
    md: 4,
    lg: 8,
    xl: 12,
    pill: 9999,
  );
}
