// GENERATED BY visor — DO NOT EDIT.
// Regenerate with `visor theme apply --adapter flutter`.
// Source: .visor.yaml → Visor theme engine → flutter adapter.

import 'dart:ui';

import 'package:visor_core/visor_core.dart';

/// Generated color tokens for the entr theme.
///
/// Do not edit this file manually — regenerate from .visor.yaml.
sealed class VisorColors {
  // ========================================================================
  // Anchors
  // ========================================================================
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);

  // ========================================================================
  // Primary scale
  // ========================================================================
  static const Color primary50 = Color(0xFFE9FAF1);
  static const Color primary100 = Color(0xFFDEFCEC);
  static const Color primary200 = Color(0xFFCAFFE4);
  static const Color primary300 = Color(0xFFB8FFDC);
  static const Color primary400 = Color(0xFF9BFFD0);
  static const Color primary500 = Color(0xFF10B981);
  static const Color primary600 = Color(0xFF006645);
  static const Color primary700 = Color(0xFF005035);
  static const Color primary800 = Color(0xFF003824);
  static const Color primary900 = Color(0xFF002114);
  static const Color primary950 = Color(0xFF000D06);

  // ========================================================================
  // Accent scale
  // ========================================================================
  static const Color accent50 = Color(0xFFF0F6FF);
  static const Color accent100 = Color(0xFFECF3FF);
  static const Color accent200 = Color(0xFFE7F0FF);
  static const Color accent300 = Color(0xFFDEEBFF);
  static const Color accent400 = Color(0xFFD3E4FF);
  static const Color accent500 = Color(0xFF3B82F6);
  static const Color accent600 = Color(0xFF004CB7);
  static const Color accent700 = Color(0xFF003B92);
  static const Color accent800 = Color(0xFF002869);
  static const Color accent900 = Color(0xFF001743);
  static const Color accent950 = Color(0xFF000721);

  // ========================================================================
  // Neutral scale
  // ========================================================================
  static const Color neutral50 = Color(0xFFF4F5F7);
  static const Color neutral100 = Color(0xFFF0F2F6);
  static const Color neutral200 = Color(0xFFEAEEF5);
  static const Color neutral300 = Color(0xFFE2E8F3);
  static const Color neutral400 = Color(0xFFD8DFEC);
  static const Color neutral500 = Color(0xFF6C727E);
  static const Color neutral600 = Color(0xFF505561);
  static const Color neutral700 = Color(0xFF3D424D);
  static const Color neutral800 = Color(0xFF292E38);
  static const Color neutral900 = Color(0xFF171B22);
  static const Color neutral950 = Color(0xFF07090E);

  // ========================================================================
  // Success scale
  // ========================================================================
  static const Color success50 = Color(0xFFE8FBEB);
  static const Color success100 = Color(0xFFDEFDE3);
  static const Color success500 = Color(0xFF22C55E);
  static const Color success600 = Color(0xFF00672B);
  static const Color success700 = Color(0xFF005120);
  static const Color success900 = Color(0xFF002209);

  // ========================================================================
  // Warning scale
  // ========================================================================
  static const Color warning50 = Color(0xFFFFF3E6);
  static const Color warning100 = Color(0xFFFFF1E3);
  static const Color warning500 = Color(0xFFF59E0B);
  static const Color warning600 = Color(0xFF774A01);
  static const Color warning700 = Color(0xFF5E3900);
  static const Color warning900 = Color(0xFF281600);

  // ========================================================================
  // Error scale
  // ========================================================================
  static const Color error50 = Color(0xFFFFF2F0);
  static const Color error100 = Color(0xFFFFEFED);
  static const Color error500 = Color(0xFFEF4444);
  static const Color error600 = Color(0xFFA30016);
  static const Color error700 = Color(0xFF81000F);
  static const Color error900 = Color(0xFF3A0003);

  // ========================================================================
  // Info scale
  // ========================================================================
  static const Color info50 = Color(0xFFECF7FF);
  static const Color info100 = Color(0xFFE8F5FF);
  static const Color info500 = Color(0xFF0EA5E9);
  static const Color info600 = Color(0xFF005C85);
  static const Color info700 = Color(0xFF004869);
  static const Color info900 = Color(0xFF001D2E);

  // ========================================================================
  // Opacity variants (pre-computed at codegen)
  // ========================================================================
  static const Color primary500_5o = Color(0x0D10B981);
  static const Color primary500_10o = Color(0x1A10B981);
  static const Color primary500_20o = Color(0x3310B981);
  static const Color primary500_40o = Color(0x6610B981);
  static const Color primary500_50o = Color(0x8010B981);
  static const Color primary500_60o = Color(0x9910B981);
  static const Color primary500_80o = Color(0xCC10B981);
  static const Color primary600_5o = Color(0x0D006645);
  static const Color primary600_10o = Color(0x1A006645);
  static const Color primary600_20o = Color(0x33006645);
  static const Color primary600_40o = Color(0x66006645);
  static const Color primary600_50o = Color(0x80006645);
  static const Color primary600_60o = Color(0x99006645);
  static const Color primary600_80o = Color(0xCC006645);
  static const Color accent500_5o = Color(0x0D3B82F6);
  static const Color accent500_10o = Color(0x1A3B82F6);
  static const Color accent500_20o = Color(0x333B82F6);
  static const Color accent500_40o = Color(0x663B82F6);
  static const Color accent500_50o = Color(0x803B82F6);
  static const Color accent500_60o = Color(0x993B82F6);
  static const Color accent500_80o = Color(0xCC3B82F6);
  static const Color white_5o = Color(0x0DFFFFFF);
  static const Color white_10o = Color(0x1AFFFFFF);
  static const Color white_20o = Color(0x33FFFFFF);
  static const Color white_40o = Color(0x66FFFFFF);
  static const Color white_50o = Color(0x80FFFFFF);
  static const Color white_60o = Color(0x99FFFFFF);
  static const Color white_80o = Color(0xCCFFFFFF);
  static const Color black_5o = Color(0x0D000000);
  static const Color black_10o = Color(0x1A000000);
  static const Color black_20o = Color(0x33000000);
  static const Color black_40o = Color(0x66000000);
  static const Color black_50o = Color(0x80000000);
  static const Color black_60o = Color(0x99000000);
  static const Color black_80o = Color(0xCC000000);

  // ========================================================================
  // Semantic — Light
  // ========================================================================
  static final VisorColorsData light = VisorColorsData(
    textPrimary: Color(0xFF171B22),
    textSecondary: Color(0xFF505561),
    textTertiary: Color(0xFFD8DFEC),
    textDisabled: Color(0xFFE2E8F3),
    textInverse: Color(0xFFFFFFFF),
    textInverseSecondary: Color(0xFFEAEEF5),
    textLink: Color(0xFF006645),
    textLinkHover: Color(0xFF005035),
    textSuccess: Color(0xFF005120),
    textWarning: Color(0xFF5E3900),
    textError: Color(0xFF81000F),
    textInfo: Color(0xFF004869),
    surfacePage: Color(0xFF111827),
    surfaceCard: Color(0xFF1F2937),
    surfaceSubtle: Color(0xFFF4F5F7),
    surfaceMuted: Color(0xFFF0F2F6),
    surfaceOverlay: Color(0xFF171B22),
    surfaceInteractiveDefault: Color(0xFFFFFFFF),
    surfaceInteractiveHover: Color(0xFFF4F5F7),
    surfaceInteractiveActive: Color(0xFFF0F2F6),
    surfaceInteractiveDisabled: Color(0xFFF4F5F7),
    surfaceAccentSubtle: Color(0xFFE9FAF1),
    surfaceAccentDefault: Color(0xFF10B981),
    surfaceAccentStrong: Color(0xFF006645),
    surfaceSuccessSubtle: Color(0xFFE8FBEB),
    surfaceSuccessDefault: Color(0xFF22C55E),
    surfaceWarningSubtle: Color(0xFFFFF3E6),
    surfaceWarningDefault: Color(0xFFF59E0B),
    surfaceErrorSubtle: Color(0xFFFFF2F0),
    surfaceErrorDefault: Color(0xFFEF4444),
    surfaceInfoSubtle: Color(0xFFECF7FF),
    surfaceInfoDefault: Color(0xFF0EA5E9),
    borderDefault: Color(0xFFEAEEF5),
    borderMuted: Color(0xFFF0F2F6),
    borderStrong: Color(0xFFE2E8F3),
    borderFocus: Color(0xFF10B981),
    borderDisabled: Color(0xFFF0F2F6),
    borderSuccess: Color(0xFF22C55E),
    borderWarning: Color(0xFFF59E0B),
    borderError: Color(0xFFEF4444),
    borderInfo: Color(0xFF0EA5E9),
    interactivePrimaryBg: Color(0xFF006645),
    interactivePrimaryBgHover: Color(0xFF005035),
    interactivePrimaryBgActive: Color(0xFF003824),
    interactivePrimaryText: Color(0xFFFFFFFF),
    interactiveSecondaryBg: Color(0xFFFFFFFF),
    interactiveSecondaryBgHover: Color(0xFFF4F5F7),
    interactiveSecondaryBgActive: Color(0xFFF0F2F6),
    interactiveSecondaryText: Color(0xFF171B22),
    interactiveSecondaryBorder: Color(0xFFE2E8F3),
    interactiveDestructiveBg: Color(0xFFA30016),
    interactiveDestructiveBgHover: Color(0xFF81000F),
    interactiveDestructiveText: Color(0xFFFFFFFF),
    interactiveGhostBg: Color(0xFFFFFFFF),
    interactiveGhostBgHover: Color(0xFFF0F2F6),
  );

  // ========================================================================
  // Semantic — Dark
  // ========================================================================
  static final VisorColorsData dark = VisorColorsData(
    textPrimary: Color(0xFFF4F5F7),
    textSecondary: Color(0xFFD8DFEC),
    textTertiary: Color(0xFF6C727E),
    textDisabled: Color(0xFF505561),
    textInverse: Color(0xFF171B22),
    textInverseSecondary: Color(0xFF3D424D),
    textLink: Color(0xFF9BFFD0),
    textLinkHover: Color(0xFFB8FFDC),
    textSuccess: Color(0xFF22C55E),
    textWarning: Color(0xFFF59E0B),
    textError: Color(0xFFEF4444),
    textInfo: Color(0xFF0EA5E9),
    surfacePage: Color(0xFF111827),
    surfaceCard: Color(0xFF1F2937),
    surfaceSubtle: Color(0xFF292E38),
    surfaceMuted: Color(0xFF3D424D),
    surfaceOverlay: Color(0xFF07090E),
    surfaceInteractiveDefault: Color(0xFF292E38),
    surfaceInteractiveHover: Color(0xFF3D424D),
    surfaceInteractiveActive: Color(0xFF505561),
    surfaceInteractiveDisabled: Color(0xFF292E38),
    surfaceAccentSubtle: Color(0xFF002114),
    surfaceAccentDefault: Color(0xFF10B981),
    surfaceAccentStrong: Color(0xFF9BFFD0),
    surfaceSuccessSubtle: Color(0xFF002209),
    surfaceSuccessDefault: Color(0xFF22C55E),
    surfaceWarningSubtle: Color(0xFF281600),
    surfaceWarningDefault: Color(0xFFF59E0B),
    surfaceErrorSubtle: Color(0xFF3A0003),
    surfaceErrorDefault: Color(0xFFEF4444),
    surfaceInfoSubtle: Color(0xFF001D2E),
    surfaceInfoDefault: Color(0xFF0EA5E9),
    borderDefault: Color(0xFF3D424D),
    borderMuted: Color(0xFF292E38),
    borderStrong: Color(0xFF505561),
    borderFocus: Color(0xFF9BFFD0),
    borderDisabled: Color(0xFF292E38),
    borderSuccess: Color(0xFF22C55E),
    borderWarning: Color(0xFFF59E0B),
    borderError: Color(0xFFEF4444),
    borderInfo: Color(0xFF0EA5E9),
    interactivePrimaryBg: Color(0xFF10B981),
    interactivePrimaryBgHover: Color(0xFF9BFFD0),
    interactivePrimaryBgActive: Color(0xFFB8FFDC),
    interactivePrimaryText: Color(0xFFFFFFFF),
    interactiveSecondaryBg: Color(0xFF292E38),
    interactiveSecondaryBgHover: Color(0xFF3D424D),
    interactiveSecondaryBgActive: Color(0xFF505561),
    interactiveSecondaryText: Color(0xFFF4F5F7),
    interactiveSecondaryBorder: Color(0xFF505561),
    interactiveDestructiveBg: Color(0xFFEF4444),
    interactiveDestructiveBgHover: Color(0xFFA30016),
    interactiveDestructiveText: Color(0xFFFFFFFF),
    interactiveGhostBg: Color(0xFF292E38),
    interactiveGhostBgHover: Color(0xFF3D424D),
  );
}
